// Code generated by go-swagger; DO NOT EDIT.

package p_cloud_snapshots

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/IBM-Cloud/power-go-client/power/models"
)

// NewPcloudCloudinstancesSnapshotsCloneParams creates a new PcloudCloudinstancesSnapshotsCloneParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPcloudCloudinstancesSnapshotsCloneParams() *PcloudCloudinstancesSnapshotsCloneParams {
	return &PcloudCloudinstancesSnapshotsCloneParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPcloudCloudinstancesSnapshotsCloneParamsWithTimeout creates a new PcloudCloudinstancesSnapshotsCloneParams object
// with the ability to set a timeout on a request.
func NewPcloudCloudinstancesSnapshotsCloneParamsWithTimeout(timeout time.Duration) *PcloudCloudinstancesSnapshotsCloneParams {
	return &PcloudCloudinstancesSnapshotsCloneParams{
		timeout: timeout,
	}
}

// NewPcloudCloudinstancesSnapshotsCloneParamsWithContext creates a new PcloudCloudinstancesSnapshotsCloneParams object
// with the ability to set a context for a request.
func NewPcloudCloudinstancesSnapshotsCloneParamsWithContext(ctx context.Context) *PcloudCloudinstancesSnapshotsCloneParams {
	return &PcloudCloudinstancesSnapshotsCloneParams{
		Context: ctx,
	}
}

// NewPcloudCloudinstancesSnapshotsCloneParamsWithHTTPClient creates a new PcloudCloudinstancesSnapshotsCloneParams object
// with the ability to set a custom HTTPClient for a request.
func NewPcloudCloudinstancesSnapshotsCloneParamsWithHTTPClient(client *http.Client) *PcloudCloudinstancesSnapshotsCloneParams {
	return &PcloudCloudinstancesSnapshotsCloneParams{
		HTTPClient: client,
	}
}

/*
PcloudCloudinstancesSnapshotsCloneParams contains all the parameters to send to the API endpoint

	for the pcloud cloudinstances snapshots clone operation.

	Typically these are written to a http.Request.
*/
type PcloudCloudinstancesSnapshotsCloneParams struct {

	/* Body.

	   PVM Instance snapshot clone parameters
	*/
	Body *models.CloneSnapshotRequest

	/* CloudInstanceID.

	   Cloud Instance ID of a PCloud Instance
	*/
	CloudInstanceID string

	/* SnapshotID.

	   PVM Instance snapshot id
	*/
	SnapshotID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the pcloud cloudinstances snapshots clone params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PcloudCloudinstancesSnapshotsCloneParams) WithDefaults() *PcloudCloudinstancesSnapshotsCloneParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the pcloud cloudinstances snapshots clone params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PcloudCloudinstancesSnapshotsCloneParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the pcloud cloudinstances snapshots clone params
func (o *PcloudCloudinstancesSnapshotsCloneParams) WithTimeout(timeout time.Duration) *PcloudCloudinstancesSnapshotsCloneParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the pcloud cloudinstances snapshots clone params
func (o *PcloudCloudinstancesSnapshotsCloneParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the pcloud cloudinstances snapshots clone params
func (o *PcloudCloudinstancesSnapshotsCloneParams) WithContext(ctx context.Context) *PcloudCloudinstancesSnapshotsCloneParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the pcloud cloudinstances snapshots clone params
func (o *PcloudCloudinstancesSnapshotsCloneParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the pcloud cloudinstances snapshots clone params
func (o *PcloudCloudinstancesSnapshotsCloneParams) WithHTTPClient(client *http.Client) *PcloudCloudinstancesSnapshotsCloneParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the pcloud cloudinstances snapshots clone params
func (o *PcloudCloudinstancesSnapshotsCloneParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the pcloud cloudinstances snapshots clone params
func (o *PcloudCloudinstancesSnapshotsCloneParams) WithBody(body *models.CloneSnapshotRequest) *PcloudCloudinstancesSnapshotsCloneParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the pcloud cloudinstances snapshots clone params
func (o *PcloudCloudinstancesSnapshotsCloneParams) SetBody(body *models.CloneSnapshotRequest) {
	o.Body = body
}

// WithCloudInstanceID adds the cloudInstanceID to the pcloud cloudinstances snapshots clone params
func (o *PcloudCloudinstancesSnapshotsCloneParams) WithCloudInstanceID(cloudInstanceID string) *PcloudCloudinstancesSnapshotsCloneParams {
	o.SetCloudInstanceID(cloudInstanceID)
	return o
}

// SetCloudInstanceID adds the cloudInstanceId to the pcloud cloudinstances snapshots clone params
func (o *PcloudCloudinstancesSnapshotsCloneParams) SetCloudInstanceID(cloudInstanceID string) {
	o.CloudInstanceID = cloudInstanceID
}

// WithSnapshotID adds the snapshotID to the pcloud cloudinstances snapshots clone params
func (o *PcloudCloudinstancesSnapshotsCloneParams) WithSnapshotID(snapshotID string) *PcloudCloudinstancesSnapshotsCloneParams {
	o.SetSnapshotID(snapshotID)
	return o
}

// SetSnapshotID adds the snapshotId to the pcloud cloudinstances snapshots clone params
func (o *PcloudCloudinstancesSnapshotsCloneParams) SetSnapshotID(snapshotID string) {
	o.SnapshotID = snapshotID
}

// WriteToRequest writes these params to a swagger request
func (o *PcloudCloudinstancesSnapshotsCloneParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param cloud_instance_id
	if err := r.SetPathParam("cloud_instance_id", o.CloudInstanceID); err != nil {
		return err
	}

	// path param snapshot_id
	if err := r.SetPathParam("snapshot_id", o.SnapshotID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
