// Code generated by go-swagger; DO NOT EDIT.

package p_cloud_snapshots

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/IBM-Cloud/power-go-client/power/models"
)

// PcloudV2CloudinstancesSnapshotsGetReader is a Reader for the PcloudV2CloudinstancesSnapshotsGet structure.
type PcloudV2CloudinstancesSnapshotsGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PcloudV2CloudinstancesSnapshotsGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPcloudV2CloudinstancesSnapshotsGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPcloudV2CloudinstancesSnapshotsGetBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPcloudV2CloudinstancesSnapshotsGetUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPcloudV2CloudinstancesSnapshotsGetForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPcloudV2CloudinstancesSnapshotsGetNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPcloudV2CloudinstancesSnapshotsGetInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /pcloud/v2/cloud-instances/{cloud_instance_id}/snapshots/{snapshot_id}] pcloud.v2.cloudinstances.snapshots.get", response, response.Code())
	}
}

// NewPcloudV2CloudinstancesSnapshotsGetOK creates a PcloudV2CloudinstancesSnapshotsGetOK with default headers values
func NewPcloudV2CloudinstancesSnapshotsGetOK() *PcloudV2CloudinstancesSnapshotsGetOK {
	return &PcloudV2CloudinstancesSnapshotsGetOK{}
}

/*
PcloudV2CloudinstancesSnapshotsGetOK describes a response with status code 200, with default header values.

OK
*/
type PcloudV2CloudinstancesSnapshotsGetOK struct {
	Payload *models.SnapshotV2
}

// IsSuccess returns true when this pcloud v2 cloudinstances snapshots get o k response has a 2xx status code
func (o *PcloudV2CloudinstancesSnapshotsGetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this pcloud v2 cloudinstances snapshots get o k response has a 3xx status code
func (o *PcloudV2CloudinstancesSnapshotsGetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud v2 cloudinstances snapshots get o k response has a 4xx status code
func (o *PcloudV2CloudinstancesSnapshotsGetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this pcloud v2 cloudinstances snapshots get o k response has a 5xx status code
func (o *PcloudV2CloudinstancesSnapshotsGetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this pcloud v2 cloudinstances snapshots get o k response a status code equal to that given
func (o *PcloudV2CloudinstancesSnapshotsGetOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the pcloud v2 cloudinstances snapshots get o k response
func (o *PcloudV2CloudinstancesSnapshotsGetOK) Code() int {
	return 200
}

func (o *PcloudV2CloudinstancesSnapshotsGetOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /pcloud/v2/cloud-instances/{cloud_instance_id}/snapshots/{snapshot_id}][%d] pcloudV2CloudinstancesSnapshotsGetOK %s", 200, payload)
}

func (o *PcloudV2CloudinstancesSnapshotsGetOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /pcloud/v2/cloud-instances/{cloud_instance_id}/snapshots/{snapshot_id}][%d] pcloudV2CloudinstancesSnapshotsGetOK %s", 200, payload)
}

func (o *PcloudV2CloudinstancesSnapshotsGetOK) GetPayload() *models.SnapshotV2 {
	return o.Payload
}

func (o *PcloudV2CloudinstancesSnapshotsGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SnapshotV2)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPcloudV2CloudinstancesSnapshotsGetBadRequest creates a PcloudV2CloudinstancesSnapshotsGetBadRequest with default headers values
func NewPcloudV2CloudinstancesSnapshotsGetBadRequest() *PcloudV2CloudinstancesSnapshotsGetBadRequest {
	return &PcloudV2CloudinstancesSnapshotsGetBadRequest{}
}

/*
PcloudV2CloudinstancesSnapshotsGetBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PcloudV2CloudinstancesSnapshotsGetBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this pcloud v2 cloudinstances snapshots get bad request response has a 2xx status code
func (o *PcloudV2CloudinstancesSnapshotsGetBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this pcloud v2 cloudinstances snapshots get bad request response has a 3xx status code
func (o *PcloudV2CloudinstancesSnapshotsGetBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud v2 cloudinstances snapshots get bad request response has a 4xx status code
func (o *PcloudV2CloudinstancesSnapshotsGetBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this pcloud v2 cloudinstances snapshots get bad request response has a 5xx status code
func (o *PcloudV2CloudinstancesSnapshotsGetBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this pcloud v2 cloudinstances snapshots get bad request response a status code equal to that given
func (o *PcloudV2CloudinstancesSnapshotsGetBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the pcloud v2 cloudinstances snapshots get bad request response
func (o *PcloudV2CloudinstancesSnapshotsGetBadRequest) Code() int {
	return 400
}

func (o *PcloudV2CloudinstancesSnapshotsGetBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /pcloud/v2/cloud-instances/{cloud_instance_id}/snapshots/{snapshot_id}][%d] pcloudV2CloudinstancesSnapshotsGetBadRequest %s", 400, payload)
}

func (o *PcloudV2CloudinstancesSnapshotsGetBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /pcloud/v2/cloud-instances/{cloud_instance_id}/snapshots/{snapshot_id}][%d] pcloudV2CloudinstancesSnapshotsGetBadRequest %s", 400, payload)
}

func (o *PcloudV2CloudinstancesSnapshotsGetBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *PcloudV2CloudinstancesSnapshotsGetBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPcloudV2CloudinstancesSnapshotsGetUnauthorized creates a PcloudV2CloudinstancesSnapshotsGetUnauthorized with default headers values
func NewPcloudV2CloudinstancesSnapshotsGetUnauthorized() *PcloudV2CloudinstancesSnapshotsGetUnauthorized {
	return &PcloudV2CloudinstancesSnapshotsGetUnauthorized{}
}

/*
PcloudV2CloudinstancesSnapshotsGetUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PcloudV2CloudinstancesSnapshotsGetUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this pcloud v2 cloudinstances snapshots get unauthorized response has a 2xx status code
func (o *PcloudV2CloudinstancesSnapshotsGetUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this pcloud v2 cloudinstances snapshots get unauthorized response has a 3xx status code
func (o *PcloudV2CloudinstancesSnapshotsGetUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud v2 cloudinstances snapshots get unauthorized response has a 4xx status code
func (o *PcloudV2CloudinstancesSnapshotsGetUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this pcloud v2 cloudinstances snapshots get unauthorized response has a 5xx status code
func (o *PcloudV2CloudinstancesSnapshotsGetUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this pcloud v2 cloudinstances snapshots get unauthorized response a status code equal to that given
func (o *PcloudV2CloudinstancesSnapshotsGetUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the pcloud v2 cloudinstances snapshots get unauthorized response
func (o *PcloudV2CloudinstancesSnapshotsGetUnauthorized) Code() int {
	return 401
}

func (o *PcloudV2CloudinstancesSnapshotsGetUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /pcloud/v2/cloud-instances/{cloud_instance_id}/snapshots/{snapshot_id}][%d] pcloudV2CloudinstancesSnapshotsGetUnauthorized %s", 401, payload)
}

func (o *PcloudV2CloudinstancesSnapshotsGetUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /pcloud/v2/cloud-instances/{cloud_instance_id}/snapshots/{snapshot_id}][%d] pcloudV2CloudinstancesSnapshotsGetUnauthorized %s", 401, payload)
}

func (o *PcloudV2CloudinstancesSnapshotsGetUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *PcloudV2CloudinstancesSnapshotsGetUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPcloudV2CloudinstancesSnapshotsGetForbidden creates a PcloudV2CloudinstancesSnapshotsGetForbidden with default headers values
func NewPcloudV2CloudinstancesSnapshotsGetForbidden() *PcloudV2CloudinstancesSnapshotsGetForbidden {
	return &PcloudV2CloudinstancesSnapshotsGetForbidden{}
}

/*
PcloudV2CloudinstancesSnapshotsGetForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type PcloudV2CloudinstancesSnapshotsGetForbidden struct {
	Payload *models.Error
}

// IsSuccess returns true when this pcloud v2 cloudinstances snapshots get forbidden response has a 2xx status code
func (o *PcloudV2CloudinstancesSnapshotsGetForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this pcloud v2 cloudinstances snapshots get forbidden response has a 3xx status code
func (o *PcloudV2CloudinstancesSnapshotsGetForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud v2 cloudinstances snapshots get forbidden response has a 4xx status code
func (o *PcloudV2CloudinstancesSnapshotsGetForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this pcloud v2 cloudinstances snapshots get forbidden response has a 5xx status code
func (o *PcloudV2CloudinstancesSnapshotsGetForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this pcloud v2 cloudinstances snapshots get forbidden response a status code equal to that given
func (o *PcloudV2CloudinstancesSnapshotsGetForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the pcloud v2 cloudinstances snapshots get forbidden response
func (o *PcloudV2CloudinstancesSnapshotsGetForbidden) Code() int {
	return 403
}

func (o *PcloudV2CloudinstancesSnapshotsGetForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /pcloud/v2/cloud-instances/{cloud_instance_id}/snapshots/{snapshot_id}][%d] pcloudV2CloudinstancesSnapshotsGetForbidden %s", 403, payload)
}

func (o *PcloudV2CloudinstancesSnapshotsGetForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /pcloud/v2/cloud-instances/{cloud_instance_id}/snapshots/{snapshot_id}][%d] pcloudV2CloudinstancesSnapshotsGetForbidden %s", 403, payload)
}

func (o *PcloudV2CloudinstancesSnapshotsGetForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *PcloudV2CloudinstancesSnapshotsGetForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPcloudV2CloudinstancesSnapshotsGetNotFound creates a PcloudV2CloudinstancesSnapshotsGetNotFound with default headers values
func NewPcloudV2CloudinstancesSnapshotsGetNotFound() *PcloudV2CloudinstancesSnapshotsGetNotFound {
	return &PcloudV2CloudinstancesSnapshotsGetNotFound{}
}

/*
PcloudV2CloudinstancesSnapshotsGetNotFound describes a response with status code 404, with default header values.

Not Found
*/
type PcloudV2CloudinstancesSnapshotsGetNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this pcloud v2 cloudinstances snapshots get not found response has a 2xx status code
func (o *PcloudV2CloudinstancesSnapshotsGetNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this pcloud v2 cloudinstances snapshots get not found response has a 3xx status code
func (o *PcloudV2CloudinstancesSnapshotsGetNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud v2 cloudinstances snapshots get not found response has a 4xx status code
func (o *PcloudV2CloudinstancesSnapshotsGetNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this pcloud v2 cloudinstances snapshots get not found response has a 5xx status code
func (o *PcloudV2CloudinstancesSnapshotsGetNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this pcloud v2 cloudinstances snapshots get not found response a status code equal to that given
func (o *PcloudV2CloudinstancesSnapshotsGetNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the pcloud v2 cloudinstances snapshots get not found response
func (o *PcloudV2CloudinstancesSnapshotsGetNotFound) Code() int {
	return 404
}

func (o *PcloudV2CloudinstancesSnapshotsGetNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /pcloud/v2/cloud-instances/{cloud_instance_id}/snapshots/{snapshot_id}][%d] pcloudV2CloudinstancesSnapshotsGetNotFound %s", 404, payload)
}

func (o *PcloudV2CloudinstancesSnapshotsGetNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /pcloud/v2/cloud-instances/{cloud_instance_id}/snapshots/{snapshot_id}][%d] pcloudV2CloudinstancesSnapshotsGetNotFound %s", 404, payload)
}

func (o *PcloudV2CloudinstancesSnapshotsGetNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *PcloudV2CloudinstancesSnapshotsGetNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPcloudV2CloudinstancesSnapshotsGetInternalServerError creates a PcloudV2CloudinstancesSnapshotsGetInternalServerError with default headers values
func NewPcloudV2CloudinstancesSnapshotsGetInternalServerError() *PcloudV2CloudinstancesSnapshotsGetInternalServerError {
	return &PcloudV2CloudinstancesSnapshotsGetInternalServerError{}
}

/*
PcloudV2CloudinstancesSnapshotsGetInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PcloudV2CloudinstancesSnapshotsGetInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this pcloud v2 cloudinstances snapshots get internal server error response has a 2xx status code
func (o *PcloudV2CloudinstancesSnapshotsGetInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this pcloud v2 cloudinstances snapshots get internal server error response has a 3xx status code
func (o *PcloudV2CloudinstancesSnapshotsGetInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud v2 cloudinstances snapshots get internal server error response has a 4xx status code
func (o *PcloudV2CloudinstancesSnapshotsGetInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this pcloud v2 cloudinstances snapshots get internal server error response has a 5xx status code
func (o *PcloudV2CloudinstancesSnapshotsGetInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this pcloud v2 cloudinstances snapshots get internal server error response a status code equal to that given
func (o *PcloudV2CloudinstancesSnapshotsGetInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the pcloud v2 cloudinstances snapshots get internal server error response
func (o *PcloudV2CloudinstancesSnapshotsGetInternalServerError) Code() int {
	return 500
}

func (o *PcloudV2CloudinstancesSnapshotsGetInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /pcloud/v2/cloud-instances/{cloud_instance_id}/snapshots/{snapshot_id}][%d] pcloudV2CloudinstancesSnapshotsGetInternalServerError %s", 500, payload)
}

func (o *PcloudV2CloudinstancesSnapshotsGetInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /pcloud/v2/cloud-instances/{cloud_instance_id}/snapshots/{snapshot_id}][%d] pcloudV2CloudinstancesSnapshotsGetInternalServerError %s", 500, payload)
}

func (o *PcloudV2CloudinstancesSnapshotsGetInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *PcloudV2CloudinstancesSnapshotsGetInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
