// Code generated by go-swagger; DO NOT EDIT.

package p_cloud_snapshots

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/IBM-Cloud/power-go-client/power/models"
)

// PcloudCloudinstancesSnapshotsCloneReader is a Reader for the PcloudCloudinstancesSnapshotsClone structure.
type PcloudCloudinstancesSnapshotsCloneReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PcloudCloudinstancesSnapshotsCloneReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 202:
		result := NewPcloudCloudinstancesSnapshotsCloneAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPcloudCloudinstancesSnapshotsCloneBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPcloudCloudinstancesSnapshotsCloneUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPcloudCloudinstancesSnapshotsCloneForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPcloudCloudinstancesSnapshotsCloneNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewPcloudCloudinstancesSnapshotsCloneConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPcloudCloudinstancesSnapshotsCloneInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 504:
		result := NewPcloudCloudinstancesSnapshotsCloneGatewayTimeout()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/snapshots/{snapshot_id}/clone] pcloud.cloudinstances.snapshots.clone", response, response.Code())
	}
}

// NewPcloudCloudinstancesSnapshotsCloneAccepted creates a PcloudCloudinstancesSnapshotsCloneAccepted with default headers values
func NewPcloudCloudinstancesSnapshotsCloneAccepted() *PcloudCloudinstancesSnapshotsCloneAccepted {
	return &PcloudCloudinstancesSnapshotsCloneAccepted{}
}

/*
PcloudCloudinstancesSnapshotsCloneAccepted describes a response with status code 202, with default header values.

Accepted
*/
type PcloudCloudinstancesSnapshotsCloneAccepted struct {
	Payload *models.CloneSnapshotResponse
}

// IsSuccess returns true when this pcloud cloudinstances snapshots clone accepted response has a 2xx status code
func (o *PcloudCloudinstancesSnapshotsCloneAccepted) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this pcloud cloudinstances snapshots clone accepted response has a 3xx status code
func (o *PcloudCloudinstancesSnapshotsCloneAccepted) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud cloudinstances snapshots clone accepted response has a 4xx status code
func (o *PcloudCloudinstancesSnapshotsCloneAccepted) IsClientError() bool {
	return false
}

// IsServerError returns true when this pcloud cloudinstances snapshots clone accepted response has a 5xx status code
func (o *PcloudCloudinstancesSnapshotsCloneAccepted) IsServerError() bool {
	return false
}

// IsCode returns true when this pcloud cloudinstances snapshots clone accepted response a status code equal to that given
func (o *PcloudCloudinstancesSnapshotsCloneAccepted) IsCode(code int) bool {
	return code == 202
}

// Code gets the status code for the pcloud cloudinstances snapshots clone accepted response
func (o *PcloudCloudinstancesSnapshotsCloneAccepted) Code() int {
	return 202
}

func (o *PcloudCloudinstancesSnapshotsCloneAccepted) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/snapshots/{snapshot_id}/clone][%d] pcloudCloudinstancesSnapshotsCloneAccepted %s", 202, payload)
}

func (o *PcloudCloudinstancesSnapshotsCloneAccepted) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/snapshots/{snapshot_id}/clone][%d] pcloudCloudinstancesSnapshotsCloneAccepted %s", 202, payload)
}

func (o *PcloudCloudinstancesSnapshotsCloneAccepted) GetPayload() *models.CloneSnapshotResponse {
	return o.Payload
}

func (o *PcloudCloudinstancesSnapshotsCloneAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CloneSnapshotResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPcloudCloudinstancesSnapshotsCloneBadRequest creates a PcloudCloudinstancesSnapshotsCloneBadRequest with default headers values
func NewPcloudCloudinstancesSnapshotsCloneBadRequest() *PcloudCloudinstancesSnapshotsCloneBadRequest {
	return &PcloudCloudinstancesSnapshotsCloneBadRequest{}
}

/*
PcloudCloudinstancesSnapshotsCloneBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PcloudCloudinstancesSnapshotsCloneBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this pcloud cloudinstances snapshots clone bad request response has a 2xx status code
func (o *PcloudCloudinstancesSnapshotsCloneBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this pcloud cloudinstances snapshots clone bad request response has a 3xx status code
func (o *PcloudCloudinstancesSnapshotsCloneBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud cloudinstances snapshots clone bad request response has a 4xx status code
func (o *PcloudCloudinstancesSnapshotsCloneBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this pcloud cloudinstances snapshots clone bad request response has a 5xx status code
func (o *PcloudCloudinstancesSnapshotsCloneBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this pcloud cloudinstances snapshots clone bad request response a status code equal to that given
func (o *PcloudCloudinstancesSnapshotsCloneBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the pcloud cloudinstances snapshots clone bad request response
func (o *PcloudCloudinstancesSnapshotsCloneBadRequest) Code() int {
	return 400
}

func (o *PcloudCloudinstancesSnapshotsCloneBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/snapshots/{snapshot_id}/clone][%d] pcloudCloudinstancesSnapshotsCloneBadRequest %s", 400, payload)
}

func (o *PcloudCloudinstancesSnapshotsCloneBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/snapshots/{snapshot_id}/clone][%d] pcloudCloudinstancesSnapshotsCloneBadRequest %s", 400, payload)
}

func (o *PcloudCloudinstancesSnapshotsCloneBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *PcloudCloudinstancesSnapshotsCloneBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPcloudCloudinstancesSnapshotsCloneUnauthorized creates a PcloudCloudinstancesSnapshotsCloneUnauthorized with default headers values
func NewPcloudCloudinstancesSnapshotsCloneUnauthorized() *PcloudCloudinstancesSnapshotsCloneUnauthorized {
	return &PcloudCloudinstancesSnapshotsCloneUnauthorized{}
}

/*
PcloudCloudinstancesSnapshotsCloneUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PcloudCloudinstancesSnapshotsCloneUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this pcloud cloudinstances snapshots clone unauthorized response has a 2xx status code
func (o *PcloudCloudinstancesSnapshotsCloneUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this pcloud cloudinstances snapshots clone unauthorized response has a 3xx status code
func (o *PcloudCloudinstancesSnapshotsCloneUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud cloudinstances snapshots clone unauthorized response has a 4xx status code
func (o *PcloudCloudinstancesSnapshotsCloneUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this pcloud cloudinstances snapshots clone unauthorized response has a 5xx status code
func (o *PcloudCloudinstancesSnapshotsCloneUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this pcloud cloudinstances snapshots clone unauthorized response a status code equal to that given
func (o *PcloudCloudinstancesSnapshotsCloneUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the pcloud cloudinstances snapshots clone unauthorized response
func (o *PcloudCloudinstancesSnapshotsCloneUnauthorized) Code() int {
	return 401
}

func (o *PcloudCloudinstancesSnapshotsCloneUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/snapshots/{snapshot_id}/clone][%d] pcloudCloudinstancesSnapshotsCloneUnauthorized %s", 401, payload)
}

func (o *PcloudCloudinstancesSnapshotsCloneUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/snapshots/{snapshot_id}/clone][%d] pcloudCloudinstancesSnapshotsCloneUnauthorized %s", 401, payload)
}

func (o *PcloudCloudinstancesSnapshotsCloneUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *PcloudCloudinstancesSnapshotsCloneUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPcloudCloudinstancesSnapshotsCloneForbidden creates a PcloudCloudinstancesSnapshotsCloneForbidden with default headers values
func NewPcloudCloudinstancesSnapshotsCloneForbidden() *PcloudCloudinstancesSnapshotsCloneForbidden {
	return &PcloudCloudinstancesSnapshotsCloneForbidden{}
}

/*
PcloudCloudinstancesSnapshotsCloneForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type PcloudCloudinstancesSnapshotsCloneForbidden struct {
	Payload *models.Error
}

// IsSuccess returns true when this pcloud cloudinstances snapshots clone forbidden response has a 2xx status code
func (o *PcloudCloudinstancesSnapshotsCloneForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this pcloud cloudinstances snapshots clone forbidden response has a 3xx status code
func (o *PcloudCloudinstancesSnapshotsCloneForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud cloudinstances snapshots clone forbidden response has a 4xx status code
func (o *PcloudCloudinstancesSnapshotsCloneForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this pcloud cloudinstances snapshots clone forbidden response has a 5xx status code
func (o *PcloudCloudinstancesSnapshotsCloneForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this pcloud cloudinstances snapshots clone forbidden response a status code equal to that given
func (o *PcloudCloudinstancesSnapshotsCloneForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the pcloud cloudinstances snapshots clone forbidden response
func (o *PcloudCloudinstancesSnapshotsCloneForbidden) Code() int {
	return 403
}

func (o *PcloudCloudinstancesSnapshotsCloneForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/snapshots/{snapshot_id}/clone][%d] pcloudCloudinstancesSnapshotsCloneForbidden %s", 403, payload)
}

func (o *PcloudCloudinstancesSnapshotsCloneForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/snapshots/{snapshot_id}/clone][%d] pcloudCloudinstancesSnapshotsCloneForbidden %s", 403, payload)
}

func (o *PcloudCloudinstancesSnapshotsCloneForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *PcloudCloudinstancesSnapshotsCloneForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPcloudCloudinstancesSnapshotsCloneNotFound creates a PcloudCloudinstancesSnapshotsCloneNotFound with default headers values
func NewPcloudCloudinstancesSnapshotsCloneNotFound() *PcloudCloudinstancesSnapshotsCloneNotFound {
	return &PcloudCloudinstancesSnapshotsCloneNotFound{}
}

/*
PcloudCloudinstancesSnapshotsCloneNotFound describes a response with status code 404, with default header values.

Not Found
*/
type PcloudCloudinstancesSnapshotsCloneNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this pcloud cloudinstances snapshots clone not found response has a 2xx status code
func (o *PcloudCloudinstancesSnapshotsCloneNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this pcloud cloudinstances snapshots clone not found response has a 3xx status code
func (o *PcloudCloudinstancesSnapshotsCloneNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud cloudinstances snapshots clone not found response has a 4xx status code
func (o *PcloudCloudinstancesSnapshotsCloneNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this pcloud cloudinstances snapshots clone not found response has a 5xx status code
func (o *PcloudCloudinstancesSnapshotsCloneNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this pcloud cloudinstances snapshots clone not found response a status code equal to that given
func (o *PcloudCloudinstancesSnapshotsCloneNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the pcloud cloudinstances snapshots clone not found response
func (o *PcloudCloudinstancesSnapshotsCloneNotFound) Code() int {
	return 404
}

func (o *PcloudCloudinstancesSnapshotsCloneNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/snapshots/{snapshot_id}/clone][%d] pcloudCloudinstancesSnapshotsCloneNotFound %s", 404, payload)
}

func (o *PcloudCloudinstancesSnapshotsCloneNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/snapshots/{snapshot_id}/clone][%d] pcloudCloudinstancesSnapshotsCloneNotFound %s", 404, payload)
}

func (o *PcloudCloudinstancesSnapshotsCloneNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *PcloudCloudinstancesSnapshotsCloneNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPcloudCloudinstancesSnapshotsCloneConflict creates a PcloudCloudinstancesSnapshotsCloneConflict with default headers values
func NewPcloudCloudinstancesSnapshotsCloneConflict() *PcloudCloudinstancesSnapshotsCloneConflict {
	return &PcloudCloudinstancesSnapshotsCloneConflict{}
}

/*
PcloudCloudinstancesSnapshotsCloneConflict describes a response with status code 409, with default header values.

Conflict
*/
type PcloudCloudinstancesSnapshotsCloneConflict struct {
	Payload *models.Error
}

// IsSuccess returns true when this pcloud cloudinstances snapshots clone conflict response has a 2xx status code
func (o *PcloudCloudinstancesSnapshotsCloneConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this pcloud cloudinstances snapshots clone conflict response has a 3xx status code
func (o *PcloudCloudinstancesSnapshotsCloneConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud cloudinstances snapshots clone conflict response has a 4xx status code
func (o *PcloudCloudinstancesSnapshotsCloneConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this pcloud cloudinstances snapshots clone conflict response has a 5xx status code
func (o *PcloudCloudinstancesSnapshotsCloneConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this pcloud cloudinstances snapshots clone conflict response a status code equal to that given
func (o *PcloudCloudinstancesSnapshotsCloneConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the pcloud cloudinstances snapshots clone conflict response
func (o *PcloudCloudinstancesSnapshotsCloneConflict) Code() int {
	return 409
}

func (o *PcloudCloudinstancesSnapshotsCloneConflict) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/snapshots/{snapshot_id}/clone][%d] pcloudCloudinstancesSnapshotsCloneConflict %s", 409, payload)
}

func (o *PcloudCloudinstancesSnapshotsCloneConflict) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/snapshots/{snapshot_id}/clone][%d] pcloudCloudinstancesSnapshotsCloneConflict %s", 409, payload)
}

func (o *PcloudCloudinstancesSnapshotsCloneConflict) GetPayload() *models.Error {
	return o.Payload
}

func (o *PcloudCloudinstancesSnapshotsCloneConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPcloudCloudinstancesSnapshotsCloneInternalServerError creates a PcloudCloudinstancesSnapshotsCloneInternalServerError with default headers values
func NewPcloudCloudinstancesSnapshotsCloneInternalServerError() *PcloudCloudinstancesSnapshotsCloneInternalServerError {
	return &PcloudCloudinstancesSnapshotsCloneInternalServerError{}
}

/*
PcloudCloudinstancesSnapshotsCloneInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PcloudCloudinstancesSnapshotsCloneInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this pcloud cloudinstances snapshots clone internal server error response has a 2xx status code
func (o *PcloudCloudinstancesSnapshotsCloneInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this pcloud cloudinstances snapshots clone internal server error response has a 3xx status code
func (o *PcloudCloudinstancesSnapshotsCloneInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud cloudinstances snapshots clone internal server error response has a 4xx status code
func (o *PcloudCloudinstancesSnapshotsCloneInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this pcloud cloudinstances snapshots clone internal server error response has a 5xx status code
func (o *PcloudCloudinstancesSnapshotsCloneInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this pcloud cloudinstances snapshots clone internal server error response a status code equal to that given
func (o *PcloudCloudinstancesSnapshotsCloneInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the pcloud cloudinstances snapshots clone internal server error response
func (o *PcloudCloudinstancesSnapshotsCloneInternalServerError) Code() int {
	return 500
}

func (o *PcloudCloudinstancesSnapshotsCloneInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/snapshots/{snapshot_id}/clone][%d] pcloudCloudinstancesSnapshotsCloneInternalServerError %s", 500, payload)
}

func (o *PcloudCloudinstancesSnapshotsCloneInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/snapshots/{snapshot_id}/clone][%d] pcloudCloudinstancesSnapshotsCloneInternalServerError %s", 500, payload)
}

func (o *PcloudCloudinstancesSnapshotsCloneInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *PcloudCloudinstancesSnapshotsCloneInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPcloudCloudinstancesSnapshotsCloneGatewayTimeout creates a PcloudCloudinstancesSnapshotsCloneGatewayTimeout with default headers values
func NewPcloudCloudinstancesSnapshotsCloneGatewayTimeout() *PcloudCloudinstancesSnapshotsCloneGatewayTimeout {
	return &PcloudCloudinstancesSnapshotsCloneGatewayTimeout{}
}

/*
PcloudCloudinstancesSnapshotsCloneGatewayTimeout describes a response with status code 504, with default header values.

Gateway Timeout
*/
type PcloudCloudinstancesSnapshotsCloneGatewayTimeout struct {
	Payload *models.Error
}

// IsSuccess returns true when this pcloud cloudinstances snapshots clone gateway timeout response has a 2xx status code
func (o *PcloudCloudinstancesSnapshotsCloneGatewayTimeout) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this pcloud cloudinstances snapshots clone gateway timeout response has a 3xx status code
func (o *PcloudCloudinstancesSnapshotsCloneGatewayTimeout) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud cloudinstances snapshots clone gateway timeout response has a 4xx status code
func (o *PcloudCloudinstancesSnapshotsCloneGatewayTimeout) IsClientError() bool {
	return false
}

// IsServerError returns true when this pcloud cloudinstances snapshots clone gateway timeout response has a 5xx status code
func (o *PcloudCloudinstancesSnapshotsCloneGatewayTimeout) IsServerError() bool {
	return true
}

// IsCode returns true when this pcloud cloudinstances snapshots clone gateway timeout response a status code equal to that given
func (o *PcloudCloudinstancesSnapshotsCloneGatewayTimeout) IsCode(code int) bool {
	return code == 504
}

// Code gets the status code for the pcloud cloudinstances snapshots clone gateway timeout response
func (o *PcloudCloudinstancesSnapshotsCloneGatewayTimeout) Code() int {
	return 504
}

func (o *PcloudCloudinstancesSnapshotsCloneGatewayTimeout) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/snapshots/{snapshot_id}/clone][%d] pcloudCloudinstancesSnapshotsCloneGatewayTimeout %s", 504, payload)
}

func (o *PcloudCloudinstancesSnapshotsCloneGatewayTimeout) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/snapshots/{snapshot_id}/clone][%d] pcloudCloudinstancesSnapshotsCloneGatewayTimeout %s", 504, payload)
}

func (o *PcloudCloudinstancesSnapshotsCloneGatewayTimeout) GetPayload() *models.Error {
	return o.Payload
}

func (o *PcloudCloudinstancesSnapshotsCloneGatewayTimeout) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
