// Code generated by go-swagger; DO NOT EDIT.

package hostgroups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/IBM-Cloud/power-go-client/power/models"
)

// NewV1HostgroupsIDPutParams creates a new V1HostgroupsIDPutParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewV1HostgroupsIDPutParams() *V1HostgroupsIDPutParams {
	return &V1HostgroupsIDPutParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewV1HostgroupsIDPutParamsWithTimeout creates a new V1HostgroupsIDPutParams object
// with the ability to set a timeout on a request.
func NewV1HostgroupsIDPutParamsWithTimeout(timeout time.Duration) *V1HostgroupsIDPutParams {
	return &V1HostgroupsIDPutParams{
		timeout: timeout,
	}
}

// NewV1HostgroupsIDPutParamsWithContext creates a new V1HostgroupsIDPutParams object
// with the ability to set a context for a request.
func NewV1HostgroupsIDPutParamsWithContext(ctx context.Context) *V1HostgroupsIDPutParams {
	return &V1HostgroupsIDPutParams{
		Context: ctx,
	}
}

// NewV1HostgroupsIDPutParamsWithHTTPClient creates a new V1HostgroupsIDPutParams object
// with the ability to set a custom HTTPClient for a request.
func NewV1HostgroupsIDPutParamsWithHTTPClient(client *http.Client) *V1HostgroupsIDPutParams {
	return &V1HostgroupsIDPutParams{
		HTTPClient: client,
	}
}

/*
V1HostgroupsIDPutParams contains all the parameters to send to the API endpoint

	for the v1 hostgroups id put operation.

	Typically these are written to a http.Request.
*/
type V1HostgroupsIDPutParams struct {

	/* Body.

	   Parameters to set the sharing status of the hostgroup
	*/
	Body *models.HostgroupShareOp

	/* HostgroupID.

	   Hostgroup ID
	*/
	HostgroupID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the v1 hostgroups id put params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V1HostgroupsIDPutParams) WithDefaults() *V1HostgroupsIDPutParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the v1 hostgroups id put params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V1HostgroupsIDPutParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the v1 hostgroups id put params
func (o *V1HostgroupsIDPutParams) WithTimeout(timeout time.Duration) *V1HostgroupsIDPutParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v1 hostgroups id put params
func (o *V1HostgroupsIDPutParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v1 hostgroups id put params
func (o *V1HostgroupsIDPutParams) WithContext(ctx context.Context) *V1HostgroupsIDPutParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v1 hostgroups id put params
func (o *V1HostgroupsIDPutParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v1 hostgroups id put params
func (o *V1HostgroupsIDPutParams) WithHTTPClient(client *http.Client) *V1HostgroupsIDPutParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v1 hostgroups id put params
func (o *V1HostgroupsIDPutParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the v1 hostgroups id put params
func (o *V1HostgroupsIDPutParams) WithBody(body *models.HostgroupShareOp) *V1HostgroupsIDPutParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the v1 hostgroups id put params
func (o *V1HostgroupsIDPutParams) SetBody(body *models.HostgroupShareOp) {
	o.Body = body
}

// WithHostgroupID adds the hostgroupID to the v1 hostgroups id put params
func (o *V1HostgroupsIDPutParams) WithHostgroupID(hostgroupID string) *V1HostgroupsIDPutParams {
	o.SetHostgroupID(hostgroupID)
	return o
}

// SetHostgroupID adds the hostgroupId to the v1 hostgroups id put params
func (o *V1HostgroupsIDPutParams) SetHostgroupID(hostgroupID string) {
	o.HostgroupID = hostgroupID
}

// WriteToRequest writes these params to a swagger request
func (o *V1HostgroupsIDPutParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param hostgroup_id
	if err := r.SetPathParam("hostgroup_id", o.HostgroupID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
