// Code generated by go-swagger; DO NOT EDIT.

package hostgroups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/IBM-Cloud/power-go-client/power/models"
)

// NewV1HostgroupsPostParams creates a new V1HostgroupsPostParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewV1HostgroupsPostParams() *V1HostgroupsPostParams {
	return &V1HostgroupsPostParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewV1HostgroupsPostParamsWithTimeout creates a new V1HostgroupsPostParams object
// with the ability to set a timeout on a request.
func NewV1HostgroupsPostParamsWithTimeout(timeout time.Duration) *V1HostgroupsPostParams {
	return &V1HostgroupsPostParams{
		timeout: timeout,
	}
}

// NewV1HostgroupsPostParamsWithContext creates a new V1HostgroupsPostParams object
// with the ability to set a context for a request.
func NewV1HostgroupsPostParamsWithContext(ctx context.Context) *V1HostgroupsPostParams {
	return &V1HostgroupsPostParams{
		Context: ctx,
	}
}

// NewV1HostgroupsPostParamsWithHTTPClient creates a new V1HostgroupsPostParams object
// with the ability to set a custom HTTPClient for a request.
func NewV1HostgroupsPostParamsWithHTTPClient(client *http.Client) *V1HostgroupsPostParams {
	return &V1HostgroupsPostParams{
		HTTPClient: client,
	}
}

/*
V1HostgroupsPostParams contains all the parameters to send to the API endpoint

	for the v1 hostgroups post operation.

	Typically these are written to a http.Request.
*/
type V1HostgroupsPostParams struct {

	/* Body.

	   Parameters for the creation of a new hostgroup
	*/
	Body *models.HostgroupCreate

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the v1 hostgroups post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V1HostgroupsPostParams) WithDefaults() *V1HostgroupsPostParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the v1 hostgroups post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V1HostgroupsPostParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the v1 hostgroups post params
func (o *V1HostgroupsPostParams) WithTimeout(timeout time.Duration) *V1HostgroupsPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v1 hostgroups post params
func (o *V1HostgroupsPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v1 hostgroups post params
func (o *V1HostgroupsPostParams) WithContext(ctx context.Context) *V1HostgroupsPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v1 hostgroups post params
func (o *V1HostgroupsPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v1 hostgroups post params
func (o *V1HostgroupsPostParams) WithHTTPClient(client *http.Client) *V1HostgroupsPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v1 hostgroups post params
func (o *V1HostgroupsPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the v1 hostgroups post params
func (o *V1HostgroupsPostParams) WithBody(body *models.HostgroupCreate) *V1HostgroupsPostParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the v1 hostgroups post params
func (o *V1HostgroupsPostParams) SetBody(body *models.HostgroupCreate) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *V1HostgroupsPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
