// Code generated by go-swagger; DO NOT EDIT.

package p_cloud_snapshot_recovery

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPcloudLocationsSnapshotrecoveryGetParams creates a new PcloudLocationsSnapshotrecoveryGetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPcloudLocationsSnapshotrecoveryGetParams() *PcloudLocationsSnapshotrecoveryGetParams {
	return &PcloudLocationsSnapshotrecoveryGetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPcloudLocationsSnapshotrecoveryGetParamsWithTimeout creates a new PcloudLocationsSnapshotrecoveryGetParams object
// with the ability to set a timeout on a request.
func NewPcloudLocationsSnapshotrecoveryGetParamsWithTimeout(timeout time.Duration) *PcloudLocationsSnapshotrecoveryGetParams {
	return &PcloudLocationsSnapshotrecoveryGetParams{
		timeout: timeout,
	}
}

// NewPcloudLocationsSnapshotrecoveryGetParamsWithContext creates a new PcloudLocationsSnapshotrecoveryGetParams object
// with the ability to set a context for a request.
func NewPcloudLocationsSnapshotrecoveryGetParamsWithContext(ctx context.Context) *PcloudLocationsSnapshotrecoveryGetParams {
	return &PcloudLocationsSnapshotrecoveryGetParams{
		Context: ctx,
	}
}

// NewPcloudLocationsSnapshotrecoveryGetParamsWithHTTPClient creates a new PcloudLocationsSnapshotrecoveryGetParams object
// with the ability to set a custom HTTPClient for a request.
func NewPcloudLocationsSnapshotrecoveryGetParamsWithHTTPClient(client *http.Client) *PcloudLocationsSnapshotrecoveryGetParams {
	return &PcloudLocationsSnapshotrecoveryGetParams{
		HTTPClient: client,
	}
}

/*
PcloudLocationsSnapshotrecoveryGetParams contains all the parameters to send to the API endpoint

	for the pcloud locations snapshotrecovery get operation.

	Typically these are written to a http.Request.
*/
type PcloudLocationsSnapshotrecoveryGetParams struct {

	/* CloudInstanceID.

	   Cloud Instance ID of a PCloud Instance
	*/
	CloudInstanceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the pcloud locations snapshotrecovery get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PcloudLocationsSnapshotrecoveryGetParams) WithDefaults() *PcloudLocationsSnapshotrecoveryGetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the pcloud locations snapshotrecovery get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PcloudLocationsSnapshotrecoveryGetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the pcloud locations snapshotrecovery get params
func (o *PcloudLocationsSnapshotrecoveryGetParams) WithTimeout(timeout time.Duration) *PcloudLocationsSnapshotrecoveryGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the pcloud locations snapshotrecovery get params
func (o *PcloudLocationsSnapshotrecoveryGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the pcloud locations snapshotrecovery get params
func (o *PcloudLocationsSnapshotrecoveryGetParams) WithContext(ctx context.Context) *PcloudLocationsSnapshotrecoveryGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the pcloud locations snapshotrecovery get params
func (o *PcloudLocationsSnapshotrecoveryGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the pcloud locations snapshotrecovery get params
func (o *PcloudLocationsSnapshotrecoveryGetParams) WithHTTPClient(client *http.Client) *PcloudLocationsSnapshotrecoveryGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the pcloud locations snapshotrecovery get params
func (o *PcloudLocationsSnapshotrecoveryGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCloudInstanceID adds the cloudInstanceID to the pcloud locations snapshotrecovery get params
func (o *PcloudLocationsSnapshotrecoveryGetParams) WithCloudInstanceID(cloudInstanceID string) *PcloudLocationsSnapshotrecoveryGetParams {
	o.SetCloudInstanceID(cloudInstanceID)
	return o
}

// SetCloudInstanceID adds the cloudInstanceId to the pcloud locations snapshotrecovery get params
func (o *PcloudLocationsSnapshotrecoveryGetParams) SetCloudInstanceID(cloudInstanceID string) {
	o.CloudInstanceID = cloudInstanceID
}

// WriteToRequest writes these params to a swagger request
func (o *PcloudLocationsSnapshotrecoveryGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cloud_instance_id
	if err := r.SetPathParam("cloud_instance_id", o.CloudInstanceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
