// Code generated by go-swagger; DO NOT EDIT.

package p_cloud_snapshot_recovery

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/IBM-Cloud/power-go-client/power/models"
)

// PcloudLocationsSnapshotrecoveryGetallReader is a Reader for the PcloudLocationsSnapshotrecoveryGetall structure.
type PcloudLocationsSnapshotrecoveryGetallReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PcloudLocationsSnapshotrecoveryGetallReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPcloudLocationsSnapshotrecoveryGetallOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPcloudLocationsSnapshotrecoveryGetallBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPcloudLocationsSnapshotrecoveryGetallUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPcloudLocationsSnapshotrecoveryGetallForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPcloudLocationsSnapshotrecoveryGetallNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPcloudLocationsSnapshotrecoveryGetallInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /pcloud/v1/locations/snapshot-recovery] pcloud.locations.snapshotrecovery.getall", response, response.Code())
	}
}

// NewPcloudLocationsSnapshotrecoveryGetallOK creates a PcloudLocationsSnapshotrecoveryGetallOK with default headers values
func NewPcloudLocationsSnapshotrecoveryGetallOK() *PcloudLocationsSnapshotrecoveryGetallOK {
	return &PcloudLocationsSnapshotrecoveryGetallOK{}
}

/*
PcloudLocationsSnapshotrecoveryGetallOK describes a response with status code 200, with default header values.

OK
*/
type PcloudLocationsSnapshotrecoveryGetallOK struct {
	Payload *models.SnapshotRecoveryLocations
}

// IsSuccess returns true when this pcloud locations snapshotrecovery getall o k response has a 2xx status code
func (o *PcloudLocationsSnapshotrecoveryGetallOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this pcloud locations snapshotrecovery getall o k response has a 3xx status code
func (o *PcloudLocationsSnapshotrecoveryGetallOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud locations snapshotrecovery getall o k response has a 4xx status code
func (o *PcloudLocationsSnapshotrecoveryGetallOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this pcloud locations snapshotrecovery getall o k response has a 5xx status code
func (o *PcloudLocationsSnapshotrecoveryGetallOK) IsServerError() bool {
	return false
}

// IsCode returns true when this pcloud locations snapshotrecovery getall o k response a status code equal to that given
func (o *PcloudLocationsSnapshotrecoveryGetallOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the pcloud locations snapshotrecovery getall o k response
func (o *PcloudLocationsSnapshotrecoveryGetallOK) Code() int {
	return 200
}

func (o *PcloudLocationsSnapshotrecoveryGetallOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /pcloud/v1/locations/snapshot-recovery][%d] pcloudLocationsSnapshotrecoveryGetallOK %s", 200, payload)
}

func (o *PcloudLocationsSnapshotrecoveryGetallOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /pcloud/v1/locations/snapshot-recovery][%d] pcloudLocationsSnapshotrecoveryGetallOK %s", 200, payload)
}

func (o *PcloudLocationsSnapshotrecoveryGetallOK) GetPayload() *models.SnapshotRecoveryLocations {
	return o.Payload
}

func (o *PcloudLocationsSnapshotrecoveryGetallOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SnapshotRecoveryLocations)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPcloudLocationsSnapshotrecoveryGetallBadRequest creates a PcloudLocationsSnapshotrecoveryGetallBadRequest with default headers values
func NewPcloudLocationsSnapshotrecoveryGetallBadRequest() *PcloudLocationsSnapshotrecoveryGetallBadRequest {
	return &PcloudLocationsSnapshotrecoveryGetallBadRequest{}
}

/*
PcloudLocationsSnapshotrecoveryGetallBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PcloudLocationsSnapshotrecoveryGetallBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this pcloud locations snapshotrecovery getall bad request response has a 2xx status code
func (o *PcloudLocationsSnapshotrecoveryGetallBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this pcloud locations snapshotrecovery getall bad request response has a 3xx status code
func (o *PcloudLocationsSnapshotrecoveryGetallBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud locations snapshotrecovery getall bad request response has a 4xx status code
func (o *PcloudLocationsSnapshotrecoveryGetallBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this pcloud locations snapshotrecovery getall bad request response has a 5xx status code
func (o *PcloudLocationsSnapshotrecoveryGetallBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this pcloud locations snapshotrecovery getall bad request response a status code equal to that given
func (o *PcloudLocationsSnapshotrecoveryGetallBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the pcloud locations snapshotrecovery getall bad request response
func (o *PcloudLocationsSnapshotrecoveryGetallBadRequest) Code() int {
	return 400
}

func (o *PcloudLocationsSnapshotrecoveryGetallBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /pcloud/v1/locations/snapshot-recovery][%d] pcloudLocationsSnapshotrecoveryGetallBadRequest %s", 400, payload)
}

func (o *PcloudLocationsSnapshotrecoveryGetallBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /pcloud/v1/locations/snapshot-recovery][%d] pcloudLocationsSnapshotrecoveryGetallBadRequest %s", 400, payload)
}

func (o *PcloudLocationsSnapshotrecoveryGetallBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *PcloudLocationsSnapshotrecoveryGetallBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPcloudLocationsSnapshotrecoveryGetallUnauthorized creates a PcloudLocationsSnapshotrecoveryGetallUnauthorized with default headers values
func NewPcloudLocationsSnapshotrecoveryGetallUnauthorized() *PcloudLocationsSnapshotrecoveryGetallUnauthorized {
	return &PcloudLocationsSnapshotrecoveryGetallUnauthorized{}
}

/*
PcloudLocationsSnapshotrecoveryGetallUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PcloudLocationsSnapshotrecoveryGetallUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this pcloud locations snapshotrecovery getall unauthorized response has a 2xx status code
func (o *PcloudLocationsSnapshotrecoveryGetallUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this pcloud locations snapshotrecovery getall unauthorized response has a 3xx status code
func (o *PcloudLocationsSnapshotrecoveryGetallUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud locations snapshotrecovery getall unauthorized response has a 4xx status code
func (o *PcloudLocationsSnapshotrecoveryGetallUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this pcloud locations snapshotrecovery getall unauthorized response has a 5xx status code
func (o *PcloudLocationsSnapshotrecoveryGetallUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this pcloud locations snapshotrecovery getall unauthorized response a status code equal to that given
func (o *PcloudLocationsSnapshotrecoveryGetallUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the pcloud locations snapshotrecovery getall unauthorized response
func (o *PcloudLocationsSnapshotrecoveryGetallUnauthorized) Code() int {
	return 401
}

func (o *PcloudLocationsSnapshotrecoveryGetallUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /pcloud/v1/locations/snapshot-recovery][%d] pcloudLocationsSnapshotrecoveryGetallUnauthorized %s", 401, payload)
}

func (o *PcloudLocationsSnapshotrecoveryGetallUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /pcloud/v1/locations/snapshot-recovery][%d] pcloudLocationsSnapshotrecoveryGetallUnauthorized %s", 401, payload)
}

func (o *PcloudLocationsSnapshotrecoveryGetallUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *PcloudLocationsSnapshotrecoveryGetallUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPcloudLocationsSnapshotrecoveryGetallForbidden creates a PcloudLocationsSnapshotrecoveryGetallForbidden with default headers values
func NewPcloudLocationsSnapshotrecoveryGetallForbidden() *PcloudLocationsSnapshotrecoveryGetallForbidden {
	return &PcloudLocationsSnapshotrecoveryGetallForbidden{}
}

/*
PcloudLocationsSnapshotrecoveryGetallForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type PcloudLocationsSnapshotrecoveryGetallForbidden struct {
	Payload *models.Error
}

// IsSuccess returns true when this pcloud locations snapshotrecovery getall forbidden response has a 2xx status code
func (o *PcloudLocationsSnapshotrecoveryGetallForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this pcloud locations snapshotrecovery getall forbidden response has a 3xx status code
func (o *PcloudLocationsSnapshotrecoveryGetallForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud locations snapshotrecovery getall forbidden response has a 4xx status code
func (o *PcloudLocationsSnapshotrecoveryGetallForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this pcloud locations snapshotrecovery getall forbidden response has a 5xx status code
func (o *PcloudLocationsSnapshotrecoveryGetallForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this pcloud locations snapshotrecovery getall forbidden response a status code equal to that given
func (o *PcloudLocationsSnapshotrecoveryGetallForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the pcloud locations snapshotrecovery getall forbidden response
func (o *PcloudLocationsSnapshotrecoveryGetallForbidden) Code() int {
	return 403
}

func (o *PcloudLocationsSnapshotrecoveryGetallForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /pcloud/v1/locations/snapshot-recovery][%d] pcloudLocationsSnapshotrecoveryGetallForbidden %s", 403, payload)
}

func (o *PcloudLocationsSnapshotrecoveryGetallForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /pcloud/v1/locations/snapshot-recovery][%d] pcloudLocationsSnapshotrecoveryGetallForbidden %s", 403, payload)
}

func (o *PcloudLocationsSnapshotrecoveryGetallForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *PcloudLocationsSnapshotrecoveryGetallForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPcloudLocationsSnapshotrecoveryGetallNotFound creates a PcloudLocationsSnapshotrecoveryGetallNotFound with default headers values
func NewPcloudLocationsSnapshotrecoveryGetallNotFound() *PcloudLocationsSnapshotrecoveryGetallNotFound {
	return &PcloudLocationsSnapshotrecoveryGetallNotFound{}
}

/*
PcloudLocationsSnapshotrecoveryGetallNotFound describes a response with status code 404, with default header values.

Not Found
*/
type PcloudLocationsSnapshotrecoveryGetallNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this pcloud locations snapshotrecovery getall not found response has a 2xx status code
func (o *PcloudLocationsSnapshotrecoveryGetallNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this pcloud locations snapshotrecovery getall not found response has a 3xx status code
func (o *PcloudLocationsSnapshotrecoveryGetallNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud locations snapshotrecovery getall not found response has a 4xx status code
func (o *PcloudLocationsSnapshotrecoveryGetallNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this pcloud locations snapshotrecovery getall not found response has a 5xx status code
func (o *PcloudLocationsSnapshotrecoveryGetallNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this pcloud locations snapshotrecovery getall not found response a status code equal to that given
func (o *PcloudLocationsSnapshotrecoveryGetallNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the pcloud locations snapshotrecovery getall not found response
func (o *PcloudLocationsSnapshotrecoveryGetallNotFound) Code() int {
	return 404
}

func (o *PcloudLocationsSnapshotrecoveryGetallNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /pcloud/v1/locations/snapshot-recovery][%d] pcloudLocationsSnapshotrecoveryGetallNotFound %s", 404, payload)
}

func (o *PcloudLocationsSnapshotrecoveryGetallNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /pcloud/v1/locations/snapshot-recovery][%d] pcloudLocationsSnapshotrecoveryGetallNotFound %s", 404, payload)
}

func (o *PcloudLocationsSnapshotrecoveryGetallNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *PcloudLocationsSnapshotrecoveryGetallNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPcloudLocationsSnapshotrecoveryGetallInternalServerError creates a PcloudLocationsSnapshotrecoveryGetallInternalServerError with default headers values
func NewPcloudLocationsSnapshotrecoveryGetallInternalServerError() *PcloudLocationsSnapshotrecoveryGetallInternalServerError {
	return &PcloudLocationsSnapshotrecoveryGetallInternalServerError{}
}

/*
PcloudLocationsSnapshotrecoveryGetallInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PcloudLocationsSnapshotrecoveryGetallInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this pcloud locations snapshotrecovery getall internal server error response has a 2xx status code
func (o *PcloudLocationsSnapshotrecoveryGetallInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this pcloud locations snapshotrecovery getall internal server error response has a 3xx status code
func (o *PcloudLocationsSnapshotrecoveryGetallInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud locations snapshotrecovery getall internal server error response has a 4xx status code
func (o *PcloudLocationsSnapshotrecoveryGetallInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this pcloud locations snapshotrecovery getall internal server error response has a 5xx status code
func (o *PcloudLocationsSnapshotrecoveryGetallInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this pcloud locations snapshotrecovery getall internal server error response a status code equal to that given
func (o *PcloudLocationsSnapshotrecoveryGetallInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the pcloud locations snapshotrecovery getall internal server error response
func (o *PcloudLocationsSnapshotrecoveryGetallInternalServerError) Code() int {
	return 500
}

func (o *PcloudLocationsSnapshotrecoveryGetallInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /pcloud/v1/locations/snapshot-recovery][%d] pcloudLocationsSnapshotrecoveryGetallInternalServerError %s", 500, payload)
}

func (o *PcloudLocationsSnapshotrecoveryGetallInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /pcloud/v1/locations/snapshot-recovery][%d] pcloudLocationsSnapshotrecoveryGetallInternalServerError %s", 500, payload)
}

func (o *PcloudLocationsSnapshotrecoveryGetallInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *PcloudLocationsSnapshotrecoveryGetallInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
