// Code generated by go-swagger; DO NOT EDIT.

package v_p_mem_volumes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/IBM-Cloud/power-go-client/power/models"
)

// V1VpmemVolumesGetallReader is a Reader for the V1VpmemVolumesGetall structure.
type V1VpmemVolumesGetallReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V1VpmemVolumesGetallReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewV1VpmemVolumesGetallOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewV1VpmemVolumesGetallUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewV1VpmemVolumesGetallForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewV1VpmemVolumesGetallNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewV1VpmemVolumesGetallInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /v1/vpmem-volumes] v1.vpmem-volumes.getall", response, response.Code())
	}
}

// NewV1VpmemVolumesGetallOK creates a V1VpmemVolumesGetallOK with default headers values
func NewV1VpmemVolumesGetallOK() *V1VpmemVolumesGetallOK {
	return &V1VpmemVolumesGetallOK{}
}

/*
V1VpmemVolumesGetallOK describes a response with status code 200, with default header values.

OK
*/
type V1VpmemVolumesGetallOK struct {
	Payload *models.VPMemVolumes
}

// IsSuccess returns true when this v1 vpmem volumes getall o k response has a 2xx status code
func (o *V1VpmemVolumesGetallOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this v1 vpmem volumes getall o k response has a 3xx status code
func (o *V1VpmemVolumesGetallOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1 vpmem volumes getall o k response has a 4xx status code
func (o *V1VpmemVolumesGetallOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this v1 vpmem volumes getall o k response has a 5xx status code
func (o *V1VpmemVolumesGetallOK) IsServerError() bool {
	return false
}

// IsCode returns true when this v1 vpmem volumes getall o k response a status code equal to that given
func (o *V1VpmemVolumesGetallOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the v1 vpmem volumes getall o k response
func (o *V1VpmemVolumesGetallOK) Code() int {
	return 200
}

func (o *V1VpmemVolumesGetallOK) Error() string {
	return fmt.Sprintf("[GET /v1/vpmem-volumes][%d] v1VpmemVolumesGetallOK  %+v", 200, o.Payload)
}

func (o *V1VpmemVolumesGetallOK) String() string {
	return fmt.Sprintf("[GET /v1/vpmem-volumes][%d] v1VpmemVolumesGetallOK  %+v", 200, o.Payload)
}

func (o *V1VpmemVolumesGetallOK) GetPayload() *models.VPMemVolumes {
	return o.Payload
}

func (o *V1VpmemVolumesGetallOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VPMemVolumes)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1VpmemVolumesGetallUnauthorized creates a V1VpmemVolumesGetallUnauthorized with default headers values
func NewV1VpmemVolumesGetallUnauthorized() *V1VpmemVolumesGetallUnauthorized {
	return &V1VpmemVolumesGetallUnauthorized{}
}

/*
V1VpmemVolumesGetallUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type V1VpmemVolumesGetallUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this v1 vpmem volumes getall unauthorized response has a 2xx status code
func (o *V1VpmemVolumesGetallUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v1 vpmem volumes getall unauthorized response has a 3xx status code
func (o *V1VpmemVolumesGetallUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1 vpmem volumes getall unauthorized response has a 4xx status code
func (o *V1VpmemVolumesGetallUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this v1 vpmem volumes getall unauthorized response has a 5xx status code
func (o *V1VpmemVolumesGetallUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this v1 vpmem volumes getall unauthorized response a status code equal to that given
func (o *V1VpmemVolumesGetallUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the v1 vpmem volumes getall unauthorized response
func (o *V1VpmemVolumesGetallUnauthorized) Code() int {
	return 401
}

func (o *V1VpmemVolumesGetallUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v1/vpmem-volumes][%d] v1VpmemVolumesGetallUnauthorized  %+v", 401, o.Payload)
}

func (o *V1VpmemVolumesGetallUnauthorized) String() string {
	return fmt.Sprintf("[GET /v1/vpmem-volumes][%d] v1VpmemVolumesGetallUnauthorized  %+v", 401, o.Payload)
}

func (o *V1VpmemVolumesGetallUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1VpmemVolumesGetallUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1VpmemVolumesGetallForbidden creates a V1VpmemVolumesGetallForbidden with default headers values
func NewV1VpmemVolumesGetallForbidden() *V1VpmemVolumesGetallForbidden {
	return &V1VpmemVolumesGetallForbidden{}
}

/*
V1VpmemVolumesGetallForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type V1VpmemVolumesGetallForbidden struct {
	Payload *models.Error
}

// IsSuccess returns true when this v1 vpmem volumes getall forbidden response has a 2xx status code
func (o *V1VpmemVolumesGetallForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v1 vpmem volumes getall forbidden response has a 3xx status code
func (o *V1VpmemVolumesGetallForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1 vpmem volumes getall forbidden response has a 4xx status code
func (o *V1VpmemVolumesGetallForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this v1 vpmem volumes getall forbidden response has a 5xx status code
func (o *V1VpmemVolumesGetallForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this v1 vpmem volumes getall forbidden response a status code equal to that given
func (o *V1VpmemVolumesGetallForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the v1 vpmem volumes getall forbidden response
func (o *V1VpmemVolumesGetallForbidden) Code() int {
	return 403
}

func (o *V1VpmemVolumesGetallForbidden) Error() string {
	return fmt.Sprintf("[GET /v1/vpmem-volumes][%d] v1VpmemVolumesGetallForbidden  %+v", 403, o.Payload)
}

func (o *V1VpmemVolumesGetallForbidden) String() string {
	return fmt.Sprintf("[GET /v1/vpmem-volumes][%d] v1VpmemVolumesGetallForbidden  %+v", 403, o.Payload)
}

func (o *V1VpmemVolumesGetallForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1VpmemVolumesGetallForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1VpmemVolumesGetallNotFound creates a V1VpmemVolumesGetallNotFound with default headers values
func NewV1VpmemVolumesGetallNotFound() *V1VpmemVolumesGetallNotFound {
	return &V1VpmemVolumesGetallNotFound{}
}

/*
V1VpmemVolumesGetallNotFound describes a response with status code 404, with default header values.

Not Found
*/
type V1VpmemVolumesGetallNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this v1 vpmem volumes getall not found response has a 2xx status code
func (o *V1VpmemVolumesGetallNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v1 vpmem volumes getall not found response has a 3xx status code
func (o *V1VpmemVolumesGetallNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1 vpmem volumes getall not found response has a 4xx status code
func (o *V1VpmemVolumesGetallNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this v1 vpmem volumes getall not found response has a 5xx status code
func (o *V1VpmemVolumesGetallNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this v1 vpmem volumes getall not found response a status code equal to that given
func (o *V1VpmemVolumesGetallNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the v1 vpmem volumes getall not found response
func (o *V1VpmemVolumesGetallNotFound) Code() int {
	return 404
}

func (o *V1VpmemVolumesGetallNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/vpmem-volumes][%d] v1VpmemVolumesGetallNotFound  %+v", 404, o.Payload)
}

func (o *V1VpmemVolumesGetallNotFound) String() string {
	return fmt.Sprintf("[GET /v1/vpmem-volumes][%d] v1VpmemVolumesGetallNotFound  %+v", 404, o.Payload)
}

func (o *V1VpmemVolumesGetallNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1VpmemVolumesGetallNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1VpmemVolumesGetallInternalServerError creates a V1VpmemVolumesGetallInternalServerError with default headers values
func NewV1VpmemVolumesGetallInternalServerError() *V1VpmemVolumesGetallInternalServerError {
	return &V1VpmemVolumesGetallInternalServerError{}
}

/*
V1VpmemVolumesGetallInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type V1VpmemVolumesGetallInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this v1 vpmem volumes getall internal server error response has a 2xx status code
func (o *V1VpmemVolumesGetallInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v1 vpmem volumes getall internal server error response has a 3xx status code
func (o *V1VpmemVolumesGetallInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1 vpmem volumes getall internal server error response has a 4xx status code
func (o *V1VpmemVolumesGetallInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this v1 vpmem volumes getall internal server error response has a 5xx status code
func (o *V1VpmemVolumesGetallInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this v1 vpmem volumes getall internal server error response a status code equal to that given
func (o *V1VpmemVolumesGetallInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the v1 vpmem volumes getall internal server error response
func (o *V1VpmemVolumesGetallInternalServerError) Code() int {
	return 500
}

func (o *V1VpmemVolumesGetallInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/vpmem-volumes][%d] v1VpmemVolumesGetallInternalServerError  %+v", 500, o.Payload)
}

func (o *V1VpmemVolumesGetallInternalServerError) String() string {
	return fmt.Sprintf("[GET /v1/vpmem-volumes][%d] v1VpmemVolumesGetallInternalServerError  %+v", 500, o.Payload)
}

func (o *V1VpmemVolumesGetallInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1VpmemVolumesGetallInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
