// Code generated by go-swagger; DO NOT EDIT.

package p_cloud_p_vm_instances

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/IBM-Cloud/power-go-client/power/models"
)

// PcloudV2PvminstancesSnapshotsPostReader is a Reader for the PcloudV2PvminstancesSnapshotsPost structure.
type PcloudV2PvminstancesSnapshotsPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PcloudV2PvminstancesSnapshotsPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 202:
		result := NewPcloudV2PvminstancesSnapshotsPostAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPcloudV2PvminstancesSnapshotsPostBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPcloudV2PvminstancesSnapshotsPostUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPcloudV2PvminstancesSnapshotsPostForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPcloudV2PvminstancesSnapshotsPostNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewPcloudV2PvminstancesSnapshotsPostConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPcloudV2PvminstancesSnapshotsPostInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 504:
		result := NewPcloudV2PvminstancesSnapshotsPostGatewayTimeout()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /pcloud/v2/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/snapshots] pcloud.v2.pvminstances.snapshots.post", response, response.Code())
	}
}

// NewPcloudV2PvminstancesSnapshotsPostAccepted creates a PcloudV2PvminstancesSnapshotsPostAccepted with default headers values
func NewPcloudV2PvminstancesSnapshotsPostAccepted() *PcloudV2PvminstancesSnapshotsPostAccepted {
	return &PcloudV2PvminstancesSnapshotsPostAccepted{}
}

/*
PcloudV2PvminstancesSnapshotsPostAccepted describes a response with status code 202, with default header values.

Accepted
*/
type PcloudV2PvminstancesSnapshotsPostAccepted struct {
	Payload *models.SnapshotCreateResponse
}

// IsSuccess returns true when this pcloud v2 pvminstances snapshots post accepted response has a 2xx status code
func (o *PcloudV2PvminstancesSnapshotsPostAccepted) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this pcloud v2 pvminstances snapshots post accepted response has a 3xx status code
func (o *PcloudV2PvminstancesSnapshotsPostAccepted) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud v2 pvminstances snapshots post accepted response has a 4xx status code
func (o *PcloudV2PvminstancesSnapshotsPostAccepted) IsClientError() bool {
	return false
}

// IsServerError returns true when this pcloud v2 pvminstances snapshots post accepted response has a 5xx status code
func (o *PcloudV2PvminstancesSnapshotsPostAccepted) IsServerError() bool {
	return false
}

// IsCode returns true when this pcloud v2 pvminstances snapshots post accepted response a status code equal to that given
func (o *PcloudV2PvminstancesSnapshotsPostAccepted) IsCode(code int) bool {
	return code == 202
}

// Code gets the status code for the pcloud v2 pvminstances snapshots post accepted response
func (o *PcloudV2PvminstancesSnapshotsPostAccepted) Code() int {
	return 202
}

func (o *PcloudV2PvminstancesSnapshotsPostAccepted) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v2/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/snapshots][%d] pcloudV2PvminstancesSnapshotsPostAccepted %s", 202, payload)
}

func (o *PcloudV2PvminstancesSnapshotsPostAccepted) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v2/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/snapshots][%d] pcloudV2PvminstancesSnapshotsPostAccepted %s", 202, payload)
}

func (o *PcloudV2PvminstancesSnapshotsPostAccepted) GetPayload() *models.SnapshotCreateResponse {
	return o.Payload
}

func (o *PcloudV2PvminstancesSnapshotsPostAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SnapshotCreateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPcloudV2PvminstancesSnapshotsPostBadRequest creates a PcloudV2PvminstancesSnapshotsPostBadRequest with default headers values
func NewPcloudV2PvminstancesSnapshotsPostBadRequest() *PcloudV2PvminstancesSnapshotsPostBadRequest {
	return &PcloudV2PvminstancesSnapshotsPostBadRequest{}
}

/*
PcloudV2PvminstancesSnapshotsPostBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PcloudV2PvminstancesSnapshotsPostBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this pcloud v2 pvminstances snapshots post bad request response has a 2xx status code
func (o *PcloudV2PvminstancesSnapshotsPostBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this pcloud v2 pvminstances snapshots post bad request response has a 3xx status code
func (o *PcloudV2PvminstancesSnapshotsPostBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud v2 pvminstances snapshots post bad request response has a 4xx status code
func (o *PcloudV2PvminstancesSnapshotsPostBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this pcloud v2 pvminstances snapshots post bad request response has a 5xx status code
func (o *PcloudV2PvminstancesSnapshotsPostBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this pcloud v2 pvminstances snapshots post bad request response a status code equal to that given
func (o *PcloudV2PvminstancesSnapshotsPostBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the pcloud v2 pvminstances snapshots post bad request response
func (o *PcloudV2PvminstancesSnapshotsPostBadRequest) Code() int {
	return 400
}

func (o *PcloudV2PvminstancesSnapshotsPostBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v2/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/snapshots][%d] pcloudV2PvminstancesSnapshotsPostBadRequest %s", 400, payload)
}

func (o *PcloudV2PvminstancesSnapshotsPostBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v2/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/snapshots][%d] pcloudV2PvminstancesSnapshotsPostBadRequest %s", 400, payload)
}

func (o *PcloudV2PvminstancesSnapshotsPostBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *PcloudV2PvminstancesSnapshotsPostBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPcloudV2PvminstancesSnapshotsPostUnauthorized creates a PcloudV2PvminstancesSnapshotsPostUnauthorized with default headers values
func NewPcloudV2PvminstancesSnapshotsPostUnauthorized() *PcloudV2PvminstancesSnapshotsPostUnauthorized {
	return &PcloudV2PvminstancesSnapshotsPostUnauthorized{}
}

/*
PcloudV2PvminstancesSnapshotsPostUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PcloudV2PvminstancesSnapshotsPostUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this pcloud v2 pvminstances snapshots post unauthorized response has a 2xx status code
func (o *PcloudV2PvminstancesSnapshotsPostUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this pcloud v2 pvminstances snapshots post unauthorized response has a 3xx status code
func (o *PcloudV2PvminstancesSnapshotsPostUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud v2 pvminstances snapshots post unauthorized response has a 4xx status code
func (o *PcloudV2PvminstancesSnapshotsPostUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this pcloud v2 pvminstances snapshots post unauthorized response has a 5xx status code
func (o *PcloudV2PvminstancesSnapshotsPostUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this pcloud v2 pvminstances snapshots post unauthorized response a status code equal to that given
func (o *PcloudV2PvminstancesSnapshotsPostUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the pcloud v2 pvminstances snapshots post unauthorized response
func (o *PcloudV2PvminstancesSnapshotsPostUnauthorized) Code() int {
	return 401
}

func (o *PcloudV2PvminstancesSnapshotsPostUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v2/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/snapshots][%d] pcloudV2PvminstancesSnapshotsPostUnauthorized %s", 401, payload)
}

func (o *PcloudV2PvminstancesSnapshotsPostUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v2/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/snapshots][%d] pcloudV2PvminstancesSnapshotsPostUnauthorized %s", 401, payload)
}

func (o *PcloudV2PvminstancesSnapshotsPostUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *PcloudV2PvminstancesSnapshotsPostUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPcloudV2PvminstancesSnapshotsPostForbidden creates a PcloudV2PvminstancesSnapshotsPostForbidden with default headers values
func NewPcloudV2PvminstancesSnapshotsPostForbidden() *PcloudV2PvminstancesSnapshotsPostForbidden {
	return &PcloudV2PvminstancesSnapshotsPostForbidden{}
}

/*
PcloudV2PvminstancesSnapshotsPostForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type PcloudV2PvminstancesSnapshotsPostForbidden struct {
	Payload *models.Error
}

// IsSuccess returns true when this pcloud v2 pvminstances snapshots post forbidden response has a 2xx status code
func (o *PcloudV2PvminstancesSnapshotsPostForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this pcloud v2 pvminstances snapshots post forbidden response has a 3xx status code
func (o *PcloudV2PvminstancesSnapshotsPostForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud v2 pvminstances snapshots post forbidden response has a 4xx status code
func (o *PcloudV2PvminstancesSnapshotsPostForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this pcloud v2 pvminstances snapshots post forbidden response has a 5xx status code
func (o *PcloudV2PvminstancesSnapshotsPostForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this pcloud v2 pvminstances snapshots post forbidden response a status code equal to that given
func (o *PcloudV2PvminstancesSnapshotsPostForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the pcloud v2 pvminstances snapshots post forbidden response
func (o *PcloudV2PvminstancesSnapshotsPostForbidden) Code() int {
	return 403
}

func (o *PcloudV2PvminstancesSnapshotsPostForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v2/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/snapshots][%d] pcloudV2PvminstancesSnapshotsPostForbidden %s", 403, payload)
}

func (o *PcloudV2PvminstancesSnapshotsPostForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v2/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/snapshots][%d] pcloudV2PvminstancesSnapshotsPostForbidden %s", 403, payload)
}

func (o *PcloudV2PvminstancesSnapshotsPostForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *PcloudV2PvminstancesSnapshotsPostForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPcloudV2PvminstancesSnapshotsPostNotFound creates a PcloudV2PvminstancesSnapshotsPostNotFound with default headers values
func NewPcloudV2PvminstancesSnapshotsPostNotFound() *PcloudV2PvminstancesSnapshotsPostNotFound {
	return &PcloudV2PvminstancesSnapshotsPostNotFound{}
}

/*
PcloudV2PvminstancesSnapshotsPostNotFound describes a response with status code 404, with default header values.

Not Found
*/
type PcloudV2PvminstancesSnapshotsPostNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this pcloud v2 pvminstances snapshots post not found response has a 2xx status code
func (o *PcloudV2PvminstancesSnapshotsPostNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this pcloud v2 pvminstances snapshots post not found response has a 3xx status code
func (o *PcloudV2PvminstancesSnapshotsPostNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud v2 pvminstances snapshots post not found response has a 4xx status code
func (o *PcloudV2PvminstancesSnapshotsPostNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this pcloud v2 pvminstances snapshots post not found response has a 5xx status code
func (o *PcloudV2PvminstancesSnapshotsPostNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this pcloud v2 pvminstances snapshots post not found response a status code equal to that given
func (o *PcloudV2PvminstancesSnapshotsPostNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the pcloud v2 pvminstances snapshots post not found response
func (o *PcloudV2PvminstancesSnapshotsPostNotFound) Code() int {
	return 404
}

func (o *PcloudV2PvminstancesSnapshotsPostNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v2/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/snapshots][%d] pcloudV2PvminstancesSnapshotsPostNotFound %s", 404, payload)
}

func (o *PcloudV2PvminstancesSnapshotsPostNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v2/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/snapshots][%d] pcloudV2PvminstancesSnapshotsPostNotFound %s", 404, payload)
}

func (o *PcloudV2PvminstancesSnapshotsPostNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *PcloudV2PvminstancesSnapshotsPostNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPcloudV2PvminstancesSnapshotsPostConflict creates a PcloudV2PvminstancesSnapshotsPostConflict with default headers values
func NewPcloudV2PvminstancesSnapshotsPostConflict() *PcloudV2PvminstancesSnapshotsPostConflict {
	return &PcloudV2PvminstancesSnapshotsPostConflict{}
}

/*
PcloudV2PvminstancesSnapshotsPostConflict describes a response with status code 409, with default header values.

Conflict
*/
type PcloudV2PvminstancesSnapshotsPostConflict struct {
	Payload *models.Error
}

// IsSuccess returns true when this pcloud v2 pvminstances snapshots post conflict response has a 2xx status code
func (o *PcloudV2PvminstancesSnapshotsPostConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this pcloud v2 pvminstances snapshots post conflict response has a 3xx status code
func (o *PcloudV2PvminstancesSnapshotsPostConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud v2 pvminstances snapshots post conflict response has a 4xx status code
func (o *PcloudV2PvminstancesSnapshotsPostConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this pcloud v2 pvminstances snapshots post conflict response has a 5xx status code
func (o *PcloudV2PvminstancesSnapshotsPostConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this pcloud v2 pvminstances snapshots post conflict response a status code equal to that given
func (o *PcloudV2PvminstancesSnapshotsPostConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the pcloud v2 pvminstances snapshots post conflict response
func (o *PcloudV2PvminstancesSnapshotsPostConflict) Code() int {
	return 409
}

func (o *PcloudV2PvminstancesSnapshotsPostConflict) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v2/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/snapshots][%d] pcloudV2PvminstancesSnapshotsPostConflict %s", 409, payload)
}

func (o *PcloudV2PvminstancesSnapshotsPostConflict) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v2/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/snapshots][%d] pcloudV2PvminstancesSnapshotsPostConflict %s", 409, payload)
}

func (o *PcloudV2PvminstancesSnapshotsPostConflict) GetPayload() *models.Error {
	return o.Payload
}

func (o *PcloudV2PvminstancesSnapshotsPostConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPcloudV2PvminstancesSnapshotsPostInternalServerError creates a PcloudV2PvminstancesSnapshotsPostInternalServerError with default headers values
func NewPcloudV2PvminstancesSnapshotsPostInternalServerError() *PcloudV2PvminstancesSnapshotsPostInternalServerError {
	return &PcloudV2PvminstancesSnapshotsPostInternalServerError{}
}

/*
PcloudV2PvminstancesSnapshotsPostInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PcloudV2PvminstancesSnapshotsPostInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this pcloud v2 pvminstances snapshots post internal server error response has a 2xx status code
func (o *PcloudV2PvminstancesSnapshotsPostInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this pcloud v2 pvminstances snapshots post internal server error response has a 3xx status code
func (o *PcloudV2PvminstancesSnapshotsPostInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud v2 pvminstances snapshots post internal server error response has a 4xx status code
func (o *PcloudV2PvminstancesSnapshotsPostInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this pcloud v2 pvminstances snapshots post internal server error response has a 5xx status code
func (o *PcloudV2PvminstancesSnapshotsPostInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this pcloud v2 pvminstances snapshots post internal server error response a status code equal to that given
func (o *PcloudV2PvminstancesSnapshotsPostInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the pcloud v2 pvminstances snapshots post internal server error response
func (o *PcloudV2PvminstancesSnapshotsPostInternalServerError) Code() int {
	return 500
}

func (o *PcloudV2PvminstancesSnapshotsPostInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v2/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/snapshots][%d] pcloudV2PvminstancesSnapshotsPostInternalServerError %s", 500, payload)
}

func (o *PcloudV2PvminstancesSnapshotsPostInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v2/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/snapshots][%d] pcloudV2PvminstancesSnapshotsPostInternalServerError %s", 500, payload)
}

func (o *PcloudV2PvminstancesSnapshotsPostInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *PcloudV2PvminstancesSnapshotsPostInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPcloudV2PvminstancesSnapshotsPostGatewayTimeout creates a PcloudV2PvminstancesSnapshotsPostGatewayTimeout with default headers values
func NewPcloudV2PvminstancesSnapshotsPostGatewayTimeout() *PcloudV2PvminstancesSnapshotsPostGatewayTimeout {
	return &PcloudV2PvminstancesSnapshotsPostGatewayTimeout{}
}

/*
PcloudV2PvminstancesSnapshotsPostGatewayTimeout describes a response with status code 504, with default header values.

Gateway Timeout
*/
type PcloudV2PvminstancesSnapshotsPostGatewayTimeout struct {
	Payload *models.Error
}

// IsSuccess returns true when this pcloud v2 pvminstances snapshots post gateway timeout response has a 2xx status code
func (o *PcloudV2PvminstancesSnapshotsPostGatewayTimeout) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this pcloud v2 pvminstances snapshots post gateway timeout response has a 3xx status code
func (o *PcloudV2PvminstancesSnapshotsPostGatewayTimeout) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud v2 pvminstances snapshots post gateway timeout response has a 4xx status code
func (o *PcloudV2PvminstancesSnapshotsPostGatewayTimeout) IsClientError() bool {
	return false
}

// IsServerError returns true when this pcloud v2 pvminstances snapshots post gateway timeout response has a 5xx status code
func (o *PcloudV2PvminstancesSnapshotsPostGatewayTimeout) IsServerError() bool {
	return true
}

// IsCode returns true when this pcloud v2 pvminstances snapshots post gateway timeout response a status code equal to that given
func (o *PcloudV2PvminstancesSnapshotsPostGatewayTimeout) IsCode(code int) bool {
	return code == 504
}

// Code gets the status code for the pcloud v2 pvminstances snapshots post gateway timeout response
func (o *PcloudV2PvminstancesSnapshotsPostGatewayTimeout) Code() int {
	return 504
}

func (o *PcloudV2PvminstancesSnapshotsPostGatewayTimeout) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v2/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/snapshots][%d] pcloudV2PvminstancesSnapshotsPostGatewayTimeout %s", 504, payload)
}

func (o *PcloudV2PvminstancesSnapshotsPostGatewayTimeout) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v2/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/snapshots][%d] pcloudV2PvminstancesSnapshotsPostGatewayTimeout %s", 504, payload)
}

func (o *PcloudV2PvminstancesSnapshotsPostGatewayTimeout) GetPayload() *models.Error {
	return o.Payload
}

func (o *PcloudV2PvminstancesSnapshotsPostGatewayTimeout) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
