// Code generated by go-swagger; DO NOT EDIT.

package p_cloud_p_vm_instances

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPcloudPvminstancesShelvePostParams creates a new PcloudPvminstancesShelvePostParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPcloudPvminstancesShelvePostParams() *PcloudPvminstancesShelvePostParams {
	return &PcloudPvminstancesShelvePostParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPcloudPvminstancesShelvePostParamsWithTimeout creates a new PcloudPvminstancesShelvePostParams object
// with the ability to set a timeout on a request.
func NewPcloudPvminstancesShelvePostParamsWithTimeout(timeout time.Duration) *PcloudPvminstancesShelvePostParams {
	return &PcloudPvminstancesShelvePostParams{
		timeout: timeout,
	}
}

// NewPcloudPvminstancesShelvePostParamsWithContext creates a new PcloudPvminstancesShelvePostParams object
// with the ability to set a context for a request.
func NewPcloudPvminstancesShelvePostParamsWithContext(ctx context.Context) *PcloudPvminstancesShelvePostParams {
	return &PcloudPvminstancesShelvePostParams{
		Context: ctx,
	}
}

// NewPcloudPvminstancesShelvePostParamsWithHTTPClient creates a new PcloudPvminstancesShelvePostParams object
// with the ability to set a custom HTTPClient for a request.
func NewPcloudPvminstancesShelvePostParamsWithHTTPClient(client *http.Client) *PcloudPvminstancesShelvePostParams {
	return &PcloudPvminstancesShelvePostParams{
		HTTPClient: client,
	}
}

/*
PcloudPvminstancesShelvePostParams contains all the parameters to send to the API endpoint

	for the pcloud pvminstances shelve post operation.

	Typically these are written to a http.Request.
*/
type PcloudPvminstancesShelvePostParams struct {

	/* CloudInstanceID.

	   Cloud Instance ID of a PCloud Instance
	*/
	CloudInstanceID string

	/* PvmInstanceID.

	   PCloud PVM Instance ID
	*/
	PvmInstanceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the pcloud pvminstances shelve post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PcloudPvminstancesShelvePostParams) WithDefaults() *PcloudPvminstancesShelvePostParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the pcloud pvminstances shelve post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PcloudPvminstancesShelvePostParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the pcloud pvminstances shelve post params
func (o *PcloudPvminstancesShelvePostParams) WithTimeout(timeout time.Duration) *PcloudPvminstancesShelvePostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the pcloud pvminstances shelve post params
func (o *PcloudPvminstancesShelvePostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the pcloud pvminstances shelve post params
func (o *PcloudPvminstancesShelvePostParams) WithContext(ctx context.Context) *PcloudPvminstancesShelvePostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the pcloud pvminstances shelve post params
func (o *PcloudPvminstancesShelvePostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the pcloud pvminstances shelve post params
func (o *PcloudPvminstancesShelvePostParams) WithHTTPClient(client *http.Client) *PcloudPvminstancesShelvePostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the pcloud pvminstances shelve post params
func (o *PcloudPvminstancesShelvePostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCloudInstanceID adds the cloudInstanceID to the pcloud pvminstances shelve post params
func (o *PcloudPvminstancesShelvePostParams) WithCloudInstanceID(cloudInstanceID string) *PcloudPvminstancesShelvePostParams {
	o.SetCloudInstanceID(cloudInstanceID)
	return o
}

// SetCloudInstanceID adds the cloudInstanceId to the pcloud pvminstances shelve post params
func (o *PcloudPvminstancesShelvePostParams) SetCloudInstanceID(cloudInstanceID string) {
	o.CloudInstanceID = cloudInstanceID
}

// WithPvmInstanceID adds the pvmInstanceID to the pcloud pvminstances shelve post params
func (o *PcloudPvminstancesShelvePostParams) WithPvmInstanceID(pvmInstanceID string) *PcloudPvminstancesShelvePostParams {
	o.SetPvmInstanceID(pvmInstanceID)
	return o
}

// SetPvmInstanceID adds the pvmInstanceId to the pcloud pvminstances shelve post params
func (o *PcloudPvminstancesShelvePostParams) SetPvmInstanceID(pvmInstanceID string) {
	o.PvmInstanceID = pvmInstanceID
}

// WriteToRequest writes these params to a swagger request
func (o *PcloudPvminstancesShelvePostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cloud_instance_id
	if err := r.SetPathParam("cloud_instance_id", o.CloudInstanceID); err != nil {
		return err
	}

	// path param pvm_instance_id
	if err := r.SetPathParam("pvm_instance_id", o.PvmInstanceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
