// Code generated by go-swagger; DO NOT EDIT.

package p_cloud_p_vm_instances

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/IBM-Cloud/power-go-client/power/models"
)

// NewPcloudPvminstancesUnshelvePostParams creates a new PcloudPvminstancesUnshelvePostParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPcloudPvminstancesUnshelvePostParams() *PcloudPvminstancesUnshelvePostParams {
	return &PcloudPvminstancesUnshelvePostParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPcloudPvminstancesUnshelvePostParamsWithTimeout creates a new PcloudPvminstancesUnshelvePostParams object
// with the ability to set a timeout on a request.
func NewPcloudPvminstancesUnshelvePostParamsWithTimeout(timeout time.Duration) *PcloudPvminstancesUnshelvePostParams {
	return &PcloudPvminstancesUnshelvePostParams{
		timeout: timeout,
	}
}

// NewPcloudPvminstancesUnshelvePostParamsWithContext creates a new PcloudPvminstancesUnshelvePostParams object
// with the ability to set a context for a request.
func NewPcloudPvminstancesUnshelvePostParamsWithContext(ctx context.Context) *PcloudPvminstancesUnshelvePostParams {
	return &PcloudPvminstancesUnshelvePostParams{
		Context: ctx,
	}
}

// NewPcloudPvminstancesUnshelvePostParamsWithHTTPClient creates a new PcloudPvminstancesUnshelvePostParams object
// with the ability to set a custom HTTPClient for a request.
func NewPcloudPvminstancesUnshelvePostParamsWithHTTPClient(client *http.Client) *PcloudPvminstancesUnshelvePostParams {
	return &PcloudPvminstancesUnshelvePostParams{
		HTTPClient: client,
	}
}

/*
PcloudPvminstancesUnshelvePostParams contains all the parameters to send to the API endpoint

	for the pcloud pvminstances unshelve post operation.

	Typically these are written to a http.Request.
*/
type PcloudPvminstancesUnshelvePostParams struct {

	/* Body.

	   Parameters for unshelving the VSI.
	*/
	Body *models.PVMInstanceUnshelve

	/* CloudInstanceID.

	   Cloud Instance ID of a PCloud Instance
	*/
	CloudInstanceID string

	/* PvmInstanceID.

	   PCloud PVM Instance ID
	*/
	PvmInstanceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the pcloud pvminstances unshelve post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PcloudPvminstancesUnshelvePostParams) WithDefaults() *PcloudPvminstancesUnshelvePostParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the pcloud pvminstances unshelve post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PcloudPvminstancesUnshelvePostParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the pcloud pvminstances unshelve post params
func (o *PcloudPvminstancesUnshelvePostParams) WithTimeout(timeout time.Duration) *PcloudPvminstancesUnshelvePostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the pcloud pvminstances unshelve post params
func (o *PcloudPvminstancesUnshelvePostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the pcloud pvminstances unshelve post params
func (o *PcloudPvminstancesUnshelvePostParams) WithContext(ctx context.Context) *PcloudPvminstancesUnshelvePostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the pcloud pvminstances unshelve post params
func (o *PcloudPvminstancesUnshelvePostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the pcloud pvminstances unshelve post params
func (o *PcloudPvminstancesUnshelvePostParams) WithHTTPClient(client *http.Client) *PcloudPvminstancesUnshelvePostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the pcloud pvminstances unshelve post params
func (o *PcloudPvminstancesUnshelvePostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the pcloud pvminstances unshelve post params
func (o *PcloudPvminstancesUnshelvePostParams) WithBody(body *models.PVMInstanceUnshelve) *PcloudPvminstancesUnshelvePostParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the pcloud pvminstances unshelve post params
func (o *PcloudPvminstancesUnshelvePostParams) SetBody(body *models.PVMInstanceUnshelve) {
	o.Body = body
}

// WithCloudInstanceID adds the cloudInstanceID to the pcloud pvminstances unshelve post params
func (o *PcloudPvminstancesUnshelvePostParams) WithCloudInstanceID(cloudInstanceID string) *PcloudPvminstancesUnshelvePostParams {
	o.SetCloudInstanceID(cloudInstanceID)
	return o
}

// SetCloudInstanceID adds the cloudInstanceId to the pcloud pvminstances unshelve post params
func (o *PcloudPvminstancesUnshelvePostParams) SetCloudInstanceID(cloudInstanceID string) {
	o.CloudInstanceID = cloudInstanceID
}

// WithPvmInstanceID adds the pvmInstanceID to the pcloud pvminstances unshelve post params
func (o *PcloudPvminstancesUnshelvePostParams) WithPvmInstanceID(pvmInstanceID string) *PcloudPvminstancesUnshelvePostParams {
	o.SetPvmInstanceID(pvmInstanceID)
	return o
}

// SetPvmInstanceID adds the pvmInstanceId to the pcloud pvminstances unshelve post params
func (o *PcloudPvminstancesUnshelvePostParams) SetPvmInstanceID(pvmInstanceID string) {
	o.PvmInstanceID = pvmInstanceID
}

// WriteToRequest writes these params to a swagger request
func (o *PcloudPvminstancesUnshelvePostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param cloud_instance_id
	if err := r.SetPathParam("cloud_instance_id", o.CloudInstanceID); err != nil {
		return err
	}

	// path param pvm_instance_id
	if err := r.SetPathParam("pvm_instance_id", o.PvmInstanceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
