// Code generated by go-swagger; DO NOT EDIT.

package p_cloud_p_vm_instances

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/IBM-Cloud/power-go-client/power/models"
)

// NewPcloudV2PvminstancesSnapshotsPostParams creates a new PcloudV2PvminstancesSnapshotsPostParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPcloudV2PvminstancesSnapshotsPostParams() *PcloudV2PvminstancesSnapshotsPostParams {
	return &PcloudV2PvminstancesSnapshotsPostParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPcloudV2PvminstancesSnapshotsPostParamsWithTimeout creates a new PcloudV2PvminstancesSnapshotsPostParams object
// with the ability to set a timeout on a request.
func NewPcloudV2PvminstancesSnapshotsPostParamsWithTimeout(timeout time.Duration) *PcloudV2PvminstancesSnapshotsPostParams {
	return &PcloudV2PvminstancesSnapshotsPostParams{
		timeout: timeout,
	}
}

// NewPcloudV2PvminstancesSnapshotsPostParamsWithContext creates a new PcloudV2PvminstancesSnapshotsPostParams object
// with the ability to set a context for a request.
func NewPcloudV2PvminstancesSnapshotsPostParamsWithContext(ctx context.Context) *PcloudV2PvminstancesSnapshotsPostParams {
	return &PcloudV2PvminstancesSnapshotsPostParams{
		Context: ctx,
	}
}

// NewPcloudV2PvminstancesSnapshotsPostParamsWithHTTPClient creates a new PcloudV2PvminstancesSnapshotsPostParams object
// with the ability to set a custom HTTPClient for a request.
func NewPcloudV2PvminstancesSnapshotsPostParamsWithHTTPClient(client *http.Client) *PcloudV2PvminstancesSnapshotsPostParams {
	return &PcloudV2PvminstancesSnapshotsPostParams{
		HTTPClient: client,
	}
}

/*
PcloudV2PvminstancesSnapshotsPostParams contains all the parameters to send to the API endpoint

	for the pcloud v2 pvminstances snapshots post operation.

	Typically these are written to a http.Request.
*/
type PcloudV2PvminstancesSnapshotsPostParams struct {

	/* Body.

	   PVM V2 Instance snapshot create parameters
	*/
	Body *models.SnapshotCreateV2

	/* CloudInstanceID.

	   Cloud Instance ID of a PCloud Instance
	*/
	CloudInstanceID string

	/* PvmInstanceID.

	   PCloud PVM Instance ID
	*/
	PvmInstanceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the pcloud v2 pvminstances snapshots post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PcloudV2PvminstancesSnapshotsPostParams) WithDefaults() *PcloudV2PvminstancesSnapshotsPostParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the pcloud v2 pvminstances snapshots post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PcloudV2PvminstancesSnapshotsPostParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the pcloud v2 pvminstances snapshots post params
func (o *PcloudV2PvminstancesSnapshotsPostParams) WithTimeout(timeout time.Duration) *PcloudV2PvminstancesSnapshotsPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the pcloud v2 pvminstances snapshots post params
func (o *PcloudV2PvminstancesSnapshotsPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the pcloud v2 pvminstances snapshots post params
func (o *PcloudV2PvminstancesSnapshotsPostParams) WithContext(ctx context.Context) *PcloudV2PvminstancesSnapshotsPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the pcloud v2 pvminstances snapshots post params
func (o *PcloudV2PvminstancesSnapshotsPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the pcloud v2 pvminstances snapshots post params
func (o *PcloudV2PvminstancesSnapshotsPostParams) WithHTTPClient(client *http.Client) *PcloudV2PvminstancesSnapshotsPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the pcloud v2 pvminstances snapshots post params
func (o *PcloudV2PvminstancesSnapshotsPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the pcloud v2 pvminstances snapshots post params
func (o *PcloudV2PvminstancesSnapshotsPostParams) WithBody(body *models.SnapshotCreateV2) *PcloudV2PvminstancesSnapshotsPostParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the pcloud v2 pvminstances snapshots post params
func (o *PcloudV2PvminstancesSnapshotsPostParams) SetBody(body *models.SnapshotCreateV2) {
	o.Body = body
}

// WithCloudInstanceID adds the cloudInstanceID to the pcloud v2 pvminstances snapshots post params
func (o *PcloudV2PvminstancesSnapshotsPostParams) WithCloudInstanceID(cloudInstanceID string) *PcloudV2PvminstancesSnapshotsPostParams {
	o.SetCloudInstanceID(cloudInstanceID)
	return o
}

// SetCloudInstanceID adds the cloudInstanceId to the pcloud v2 pvminstances snapshots post params
func (o *PcloudV2PvminstancesSnapshotsPostParams) SetCloudInstanceID(cloudInstanceID string) {
	o.CloudInstanceID = cloudInstanceID
}

// WithPvmInstanceID adds the pvmInstanceID to the pcloud v2 pvminstances snapshots post params
func (o *PcloudV2PvminstancesSnapshotsPostParams) WithPvmInstanceID(pvmInstanceID string) *PcloudV2PvminstancesSnapshotsPostParams {
	o.SetPvmInstanceID(pvmInstanceID)
	return o
}

// SetPvmInstanceID adds the pvmInstanceId to the pcloud v2 pvminstances snapshots post params
func (o *PcloudV2PvminstancesSnapshotsPostParams) SetPvmInstanceID(pvmInstanceID string) {
	o.PvmInstanceID = pvmInstanceID
}

// WriteToRequest writes these params to a swagger request
func (o *PcloudV2PvminstancesSnapshotsPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param cloud_instance_id
	if err := r.SetPathParam("cloud_instance_id", o.CloudInstanceID); err != nil {
		return err
	}

	// path param pvm_instance_id
	if err := r.SetPathParam("pvm_instance_id", o.PvmInstanceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
