// Code generated by go-swagger; DO NOT EDIT.

package p_cloud_p_vm_instances

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/IBM-Cloud/power-go-client/power/models"
)

// PcloudPvminstancesShelvePostReader is a Reader for the PcloudPvminstancesShelvePost structure.
type PcloudPvminstancesShelvePostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PcloudPvminstancesShelvePostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 202:
		result := NewPcloudPvminstancesShelvePostAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPcloudPvminstancesShelvePostBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPcloudPvminstancesShelvePostUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPcloudPvminstancesShelvePostForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPcloudPvminstancesShelvePostNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewPcloudPvminstancesShelvePostConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPcloudPvminstancesShelvePostInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/shelve] pcloud.pvminstances.shelve.post", response, response.Code())
	}
}

// NewPcloudPvminstancesShelvePostAccepted creates a PcloudPvminstancesShelvePostAccepted with default headers values
func NewPcloudPvminstancesShelvePostAccepted() *PcloudPvminstancesShelvePostAccepted {
	return &PcloudPvminstancesShelvePostAccepted{}
}

/*
PcloudPvminstancesShelvePostAccepted describes a response with status code 202, with default header values.

Accepted
*/
type PcloudPvminstancesShelvePostAccepted struct {
	Payload models.Object
}

// IsSuccess returns true when this pcloud pvminstances shelve post accepted response has a 2xx status code
func (o *PcloudPvminstancesShelvePostAccepted) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this pcloud pvminstances shelve post accepted response has a 3xx status code
func (o *PcloudPvminstancesShelvePostAccepted) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud pvminstances shelve post accepted response has a 4xx status code
func (o *PcloudPvminstancesShelvePostAccepted) IsClientError() bool {
	return false
}

// IsServerError returns true when this pcloud pvminstances shelve post accepted response has a 5xx status code
func (o *PcloudPvminstancesShelvePostAccepted) IsServerError() bool {
	return false
}

// IsCode returns true when this pcloud pvminstances shelve post accepted response a status code equal to that given
func (o *PcloudPvminstancesShelvePostAccepted) IsCode(code int) bool {
	return code == 202
}

// Code gets the status code for the pcloud pvminstances shelve post accepted response
func (o *PcloudPvminstancesShelvePostAccepted) Code() int {
	return 202
}

func (o *PcloudPvminstancesShelvePostAccepted) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/shelve][%d] pcloudPvminstancesShelvePostAccepted %s", 202, payload)
}

func (o *PcloudPvminstancesShelvePostAccepted) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/shelve][%d] pcloudPvminstancesShelvePostAccepted %s", 202, payload)
}

func (o *PcloudPvminstancesShelvePostAccepted) GetPayload() models.Object {
	return o.Payload
}

func (o *PcloudPvminstancesShelvePostAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPcloudPvminstancesShelvePostBadRequest creates a PcloudPvminstancesShelvePostBadRequest with default headers values
func NewPcloudPvminstancesShelvePostBadRequest() *PcloudPvminstancesShelvePostBadRequest {
	return &PcloudPvminstancesShelvePostBadRequest{}
}

/*
PcloudPvminstancesShelvePostBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PcloudPvminstancesShelvePostBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this pcloud pvminstances shelve post bad request response has a 2xx status code
func (o *PcloudPvminstancesShelvePostBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this pcloud pvminstances shelve post bad request response has a 3xx status code
func (o *PcloudPvminstancesShelvePostBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud pvminstances shelve post bad request response has a 4xx status code
func (o *PcloudPvminstancesShelvePostBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this pcloud pvminstances shelve post bad request response has a 5xx status code
func (o *PcloudPvminstancesShelvePostBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this pcloud pvminstances shelve post bad request response a status code equal to that given
func (o *PcloudPvminstancesShelvePostBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the pcloud pvminstances shelve post bad request response
func (o *PcloudPvminstancesShelvePostBadRequest) Code() int {
	return 400
}

func (o *PcloudPvminstancesShelvePostBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/shelve][%d] pcloudPvminstancesShelvePostBadRequest %s", 400, payload)
}

func (o *PcloudPvminstancesShelvePostBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/shelve][%d] pcloudPvminstancesShelvePostBadRequest %s", 400, payload)
}

func (o *PcloudPvminstancesShelvePostBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *PcloudPvminstancesShelvePostBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPcloudPvminstancesShelvePostUnauthorized creates a PcloudPvminstancesShelvePostUnauthorized with default headers values
func NewPcloudPvminstancesShelvePostUnauthorized() *PcloudPvminstancesShelvePostUnauthorized {
	return &PcloudPvminstancesShelvePostUnauthorized{}
}

/*
PcloudPvminstancesShelvePostUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PcloudPvminstancesShelvePostUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this pcloud pvminstances shelve post unauthorized response has a 2xx status code
func (o *PcloudPvminstancesShelvePostUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this pcloud pvminstances shelve post unauthorized response has a 3xx status code
func (o *PcloudPvminstancesShelvePostUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud pvminstances shelve post unauthorized response has a 4xx status code
func (o *PcloudPvminstancesShelvePostUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this pcloud pvminstances shelve post unauthorized response has a 5xx status code
func (o *PcloudPvminstancesShelvePostUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this pcloud pvminstances shelve post unauthorized response a status code equal to that given
func (o *PcloudPvminstancesShelvePostUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the pcloud pvminstances shelve post unauthorized response
func (o *PcloudPvminstancesShelvePostUnauthorized) Code() int {
	return 401
}

func (o *PcloudPvminstancesShelvePostUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/shelve][%d] pcloudPvminstancesShelvePostUnauthorized %s", 401, payload)
}

func (o *PcloudPvminstancesShelvePostUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/shelve][%d] pcloudPvminstancesShelvePostUnauthorized %s", 401, payload)
}

func (o *PcloudPvminstancesShelvePostUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *PcloudPvminstancesShelvePostUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPcloudPvminstancesShelvePostForbidden creates a PcloudPvminstancesShelvePostForbidden with default headers values
func NewPcloudPvminstancesShelvePostForbidden() *PcloudPvminstancesShelvePostForbidden {
	return &PcloudPvminstancesShelvePostForbidden{}
}

/*
PcloudPvminstancesShelvePostForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type PcloudPvminstancesShelvePostForbidden struct {
	Payload *models.Error
}

// IsSuccess returns true when this pcloud pvminstances shelve post forbidden response has a 2xx status code
func (o *PcloudPvminstancesShelvePostForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this pcloud pvminstances shelve post forbidden response has a 3xx status code
func (o *PcloudPvminstancesShelvePostForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud pvminstances shelve post forbidden response has a 4xx status code
func (o *PcloudPvminstancesShelvePostForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this pcloud pvminstances shelve post forbidden response has a 5xx status code
func (o *PcloudPvminstancesShelvePostForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this pcloud pvminstances shelve post forbidden response a status code equal to that given
func (o *PcloudPvminstancesShelvePostForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the pcloud pvminstances shelve post forbidden response
func (o *PcloudPvminstancesShelvePostForbidden) Code() int {
	return 403
}

func (o *PcloudPvminstancesShelvePostForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/shelve][%d] pcloudPvminstancesShelvePostForbidden %s", 403, payload)
}

func (o *PcloudPvminstancesShelvePostForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/shelve][%d] pcloudPvminstancesShelvePostForbidden %s", 403, payload)
}

func (o *PcloudPvminstancesShelvePostForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *PcloudPvminstancesShelvePostForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPcloudPvminstancesShelvePostNotFound creates a PcloudPvminstancesShelvePostNotFound with default headers values
func NewPcloudPvminstancesShelvePostNotFound() *PcloudPvminstancesShelvePostNotFound {
	return &PcloudPvminstancesShelvePostNotFound{}
}

/*
PcloudPvminstancesShelvePostNotFound describes a response with status code 404, with default header values.

Not Found
*/
type PcloudPvminstancesShelvePostNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this pcloud pvminstances shelve post not found response has a 2xx status code
func (o *PcloudPvminstancesShelvePostNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this pcloud pvminstances shelve post not found response has a 3xx status code
func (o *PcloudPvminstancesShelvePostNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud pvminstances shelve post not found response has a 4xx status code
func (o *PcloudPvminstancesShelvePostNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this pcloud pvminstances shelve post not found response has a 5xx status code
func (o *PcloudPvminstancesShelvePostNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this pcloud pvminstances shelve post not found response a status code equal to that given
func (o *PcloudPvminstancesShelvePostNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the pcloud pvminstances shelve post not found response
func (o *PcloudPvminstancesShelvePostNotFound) Code() int {
	return 404
}

func (o *PcloudPvminstancesShelvePostNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/shelve][%d] pcloudPvminstancesShelvePostNotFound %s", 404, payload)
}

func (o *PcloudPvminstancesShelvePostNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/shelve][%d] pcloudPvminstancesShelvePostNotFound %s", 404, payload)
}

func (o *PcloudPvminstancesShelvePostNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *PcloudPvminstancesShelvePostNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPcloudPvminstancesShelvePostConflict creates a PcloudPvminstancesShelvePostConflict with default headers values
func NewPcloudPvminstancesShelvePostConflict() *PcloudPvminstancesShelvePostConflict {
	return &PcloudPvminstancesShelvePostConflict{}
}

/*
PcloudPvminstancesShelvePostConflict describes a response with status code 409, with default header values.

Conflict
*/
type PcloudPvminstancesShelvePostConflict struct {
	Payload *models.Error
}

// IsSuccess returns true when this pcloud pvminstances shelve post conflict response has a 2xx status code
func (o *PcloudPvminstancesShelvePostConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this pcloud pvminstances shelve post conflict response has a 3xx status code
func (o *PcloudPvminstancesShelvePostConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud pvminstances shelve post conflict response has a 4xx status code
func (o *PcloudPvminstancesShelvePostConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this pcloud pvminstances shelve post conflict response has a 5xx status code
func (o *PcloudPvminstancesShelvePostConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this pcloud pvminstances shelve post conflict response a status code equal to that given
func (o *PcloudPvminstancesShelvePostConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the pcloud pvminstances shelve post conflict response
func (o *PcloudPvminstancesShelvePostConflict) Code() int {
	return 409
}

func (o *PcloudPvminstancesShelvePostConflict) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/shelve][%d] pcloudPvminstancesShelvePostConflict %s", 409, payload)
}

func (o *PcloudPvminstancesShelvePostConflict) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/shelve][%d] pcloudPvminstancesShelvePostConflict %s", 409, payload)
}

func (o *PcloudPvminstancesShelvePostConflict) GetPayload() *models.Error {
	return o.Payload
}

func (o *PcloudPvminstancesShelvePostConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPcloudPvminstancesShelvePostInternalServerError creates a PcloudPvminstancesShelvePostInternalServerError with default headers values
func NewPcloudPvminstancesShelvePostInternalServerError() *PcloudPvminstancesShelvePostInternalServerError {
	return &PcloudPvminstancesShelvePostInternalServerError{}
}

/*
PcloudPvminstancesShelvePostInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PcloudPvminstancesShelvePostInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this pcloud pvminstances shelve post internal server error response has a 2xx status code
func (o *PcloudPvminstancesShelvePostInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this pcloud pvminstances shelve post internal server error response has a 3xx status code
func (o *PcloudPvminstancesShelvePostInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud pvminstances shelve post internal server error response has a 4xx status code
func (o *PcloudPvminstancesShelvePostInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this pcloud pvminstances shelve post internal server error response has a 5xx status code
func (o *PcloudPvminstancesShelvePostInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this pcloud pvminstances shelve post internal server error response a status code equal to that given
func (o *PcloudPvminstancesShelvePostInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the pcloud pvminstances shelve post internal server error response
func (o *PcloudPvminstancesShelvePostInternalServerError) Code() int {
	return 500
}

func (o *PcloudPvminstancesShelvePostInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/shelve][%d] pcloudPvminstancesShelvePostInternalServerError %s", 500, payload)
}

func (o *PcloudPvminstancesShelvePostInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/shelve][%d] pcloudPvminstancesShelvePostInternalServerError %s", 500, payload)
}

func (o *PcloudPvminstancesShelvePostInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *PcloudPvminstancesShelvePostInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
