// Code generated by go-swagger; DO NOT EDIT.

package p_cloud_clone_volumes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/IBM-Cloud/power-go-client/power/models"
)

// PcloudClonevolumesPostReader is a Reader for the PcloudClonevolumesPost structure.
type PcloudClonevolumesPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PcloudClonevolumesPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPcloudClonevolumesPostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPcloudClonevolumesPostBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 409:
		result := NewPcloudClonevolumesPostConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewPcloudClonevolumesPostInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPcloudClonevolumesPostOK creates a PcloudClonevolumesPostOK with default headers values
func NewPcloudClonevolumesPostOK() *PcloudClonevolumesPostOK {
	return &PcloudClonevolumesPostOK{}
}

/*PcloudClonevolumesPostOK handles this case with default header values.

OK
*/
type PcloudClonevolumesPostOK struct {
	Payload *models.CloneVolumesResponse
}

func (o *PcloudClonevolumesPostOK) Error() string {
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/clone-volumes][%d] pcloudClonevolumesPostOK  %+v", 200, o.Payload)
}

func (o *PcloudClonevolumesPostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CloneVolumesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPcloudClonevolumesPostBadRequest creates a PcloudClonevolumesPostBadRequest with default headers values
func NewPcloudClonevolumesPostBadRequest() *PcloudClonevolumesPostBadRequest {
	return &PcloudClonevolumesPostBadRequest{}
}

/*PcloudClonevolumesPostBadRequest handles this case with default header values.

Bad Request
*/
type PcloudClonevolumesPostBadRequest struct {
	Payload *models.Error
}

func (o *PcloudClonevolumesPostBadRequest) Error() string {
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/clone-volumes][%d] pcloudClonevolumesPostBadRequest  %+v", 400, o.Payload)
}

func (o *PcloudClonevolumesPostBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPcloudClonevolumesPostConflict creates a PcloudClonevolumesPostConflict with default headers values
func NewPcloudClonevolumesPostConflict() *PcloudClonevolumesPostConflict {
	return &PcloudClonevolumesPostConflict{}
}

/*PcloudClonevolumesPostConflict handles this case with default header values.

Conflict
*/
type PcloudClonevolumesPostConflict struct {
	Payload *models.Error
}

func (o *PcloudClonevolumesPostConflict) Error() string {
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/clone-volumes][%d] pcloudClonevolumesPostConflict  %+v", 409, o.Payload)
}

func (o *PcloudClonevolumesPostConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPcloudClonevolumesPostInternalServerError creates a PcloudClonevolumesPostInternalServerError with default headers values
func NewPcloudClonevolumesPostInternalServerError() *PcloudClonevolumesPostInternalServerError {
	return &PcloudClonevolumesPostInternalServerError{}
}

/*PcloudClonevolumesPostInternalServerError handles this case with default header values.

Internal Server Error
*/
type PcloudClonevolumesPostInternalServerError struct {
	Payload *models.Error
}

func (o *PcloudClonevolumesPostInternalServerError) Error() string {
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/clone-volumes][%d] pcloudClonevolumesPostInternalServerError  %+v", 500, o.Payload)
}

func (o *PcloudClonevolumesPostInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
