// Code generated by go-swagger; DO NOT EDIT.

package p_cloud_v_p_mem_volumes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/IBM-Cloud/power-go-client/power/models"
)

// PcloudPvminstancesVpmemVolumesPostReader is a Reader for the PcloudPvminstancesVpmemVolumesPost structure.
type PcloudPvminstancesVpmemVolumesPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PcloudPvminstancesVpmemVolumesPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewPcloudPvminstancesVpmemVolumesPostAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPcloudPvminstancesVpmemVolumesPostBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPcloudPvminstancesVpmemVolumesPostUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPcloudPvminstancesVpmemVolumesPostForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPcloudPvminstancesVpmemVolumesPostNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewPcloudPvminstancesVpmemVolumesPostConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPcloudPvminstancesVpmemVolumesPostInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/vpmem-volumes] pcloud.pvminstances.vpmem-volumes.post", response, response.Code())
	}
}

// NewPcloudPvminstancesVpmemVolumesPostAccepted creates a PcloudPvminstancesVpmemVolumesPostAccepted with default headers values
func NewPcloudPvminstancesVpmemVolumesPostAccepted() *PcloudPvminstancesVpmemVolumesPostAccepted {
	return &PcloudPvminstancesVpmemVolumesPostAccepted{}
}

/*
PcloudPvminstancesVpmemVolumesPostAccepted describes a response with status code 202, with default header values.

Accepted
*/
type PcloudPvminstancesVpmemVolumesPostAccepted struct {
	Payload *models.VPMemVolumes
}

// IsSuccess returns true when this pcloud pvminstances vpmem volumes post accepted response has a 2xx status code
func (o *PcloudPvminstancesVpmemVolumesPostAccepted) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this pcloud pvminstances vpmem volumes post accepted response has a 3xx status code
func (o *PcloudPvminstancesVpmemVolumesPostAccepted) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud pvminstances vpmem volumes post accepted response has a 4xx status code
func (o *PcloudPvminstancesVpmemVolumesPostAccepted) IsClientError() bool {
	return false
}

// IsServerError returns true when this pcloud pvminstances vpmem volumes post accepted response has a 5xx status code
func (o *PcloudPvminstancesVpmemVolumesPostAccepted) IsServerError() bool {
	return false
}

// IsCode returns true when this pcloud pvminstances vpmem volumes post accepted response a status code equal to that given
func (o *PcloudPvminstancesVpmemVolumesPostAccepted) IsCode(code int) bool {
	return code == 202
}

// Code gets the status code for the pcloud pvminstances vpmem volumes post accepted response
func (o *PcloudPvminstancesVpmemVolumesPostAccepted) Code() int {
	return 202
}

func (o *PcloudPvminstancesVpmemVolumesPostAccepted) Error() string {
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/vpmem-volumes][%d] pcloudPvminstancesVpmemVolumesPostAccepted  %+v", 202, o.Payload)
}

func (o *PcloudPvminstancesVpmemVolumesPostAccepted) String() string {
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/vpmem-volumes][%d] pcloudPvminstancesVpmemVolumesPostAccepted  %+v", 202, o.Payload)
}

func (o *PcloudPvminstancesVpmemVolumesPostAccepted) GetPayload() *models.VPMemVolumes {
	return o.Payload
}

func (o *PcloudPvminstancesVpmemVolumesPostAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VPMemVolumes)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPcloudPvminstancesVpmemVolumesPostBadRequest creates a PcloudPvminstancesVpmemVolumesPostBadRequest with default headers values
func NewPcloudPvminstancesVpmemVolumesPostBadRequest() *PcloudPvminstancesVpmemVolumesPostBadRequest {
	return &PcloudPvminstancesVpmemVolumesPostBadRequest{}
}

/*
PcloudPvminstancesVpmemVolumesPostBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PcloudPvminstancesVpmemVolumesPostBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this pcloud pvminstances vpmem volumes post bad request response has a 2xx status code
func (o *PcloudPvminstancesVpmemVolumesPostBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this pcloud pvminstances vpmem volumes post bad request response has a 3xx status code
func (o *PcloudPvminstancesVpmemVolumesPostBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud pvminstances vpmem volumes post bad request response has a 4xx status code
func (o *PcloudPvminstancesVpmemVolumesPostBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this pcloud pvminstances vpmem volumes post bad request response has a 5xx status code
func (o *PcloudPvminstancesVpmemVolumesPostBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this pcloud pvminstances vpmem volumes post bad request response a status code equal to that given
func (o *PcloudPvminstancesVpmemVolumesPostBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the pcloud pvminstances vpmem volumes post bad request response
func (o *PcloudPvminstancesVpmemVolumesPostBadRequest) Code() int {
	return 400
}

func (o *PcloudPvminstancesVpmemVolumesPostBadRequest) Error() string {
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/vpmem-volumes][%d] pcloudPvminstancesVpmemVolumesPostBadRequest  %+v", 400, o.Payload)
}

func (o *PcloudPvminstancesVpmemVolumesPostBadRequest) String() string {
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/vpmem-volumes][%d] pcloudPvminstancesVpmemVolumesPostBadRequest  %+v", 400, o.Payload)
}

func (o *PcloudPvminstancesVpmemVolumesPostBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *PcloudPvminstancesVpmemVolumesPostBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPcloudPvminstancesVpmemVolumesPostUnauthorized creates a PcloudPvminstancesVpmemVolumesPostUnauthorized with default headers values
func NewPcloudPvminstancesVpmemVolumesPostUnauthorized() *PcloudPvminstancesVpmemVolumesPostUnauthorized {
	return &PcloudPvminstancesVpmemVolumesPostUnauthorized{}
}

/*
PcloudPvminstancesVpmemVolumesPostUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PcloudPvminstancesVpmemVolumesPostUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this pcloud pvminstances vpmem volumes post unauthorized response has a 2xx status code
func (o *PcloudPvminstancesVpmemVolumesPostUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this pcloud pvminstances vpmem volumes post unauthorized response has a 3xx status code
func (o *PcloudPvminstancesVpmemVolumesPostUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud pvminstances vpmem volumes post unauthorized response has a 4xx status code
func (o *PcloudPvminstancesVpmemVolumesPostUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this pcloud pvminstances vpmem volumes post unauthorized response has a 5xx status code
func (o *PcloudPvminstancesVpmemVolumesPostUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this pcloud pvminstances vpmem volumes post unauthorized response a status code equal to that given
func (o *PcloudPvminstancesVpmemVolumesPostUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the pcloud pvminstances vpmem volumes post unauthorized response
func (o *PcloudPvminstancesVpmemVolumesPostUnauthorized) Code() int {
	return 401
}

func (o *PcloudPvminstancesVpmemVolumesPostUnauthorized) Error() string {
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/vpmem-volumes][%d] pcloudPvminstancesVpmemVolumesPostUnauthorized  %+v", 401, o.Payload)
}

func (o *PcloudPvminstancesVpmemVolumesPostUnauthorized) String() string {
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/vpmem-volumes][%d] pcloudPvminstancesVpmemVolumesPostUnauthorized  %+v", 401, o.Payload)
}

func (o *PcloudPvminstancesVpmemVolumesPostUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *PcloudPvminstancesVpmemVolumesPostUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPcloudPvminstancesVpmemVolumesPostForbidden creates a PcloudPvminstancesVpmemVolumesPostForbidden with default headers values
func NewPcloudPvminstancesVpmemVolumesPostForbidden() *PcloudPvminstancesVpmemVolumesPostForbidden {
	return &PcloudPvminstancesVpmemVolumesPostForbidden{}
}

/*
PcloudPvminstancesVpmemVolumesPostForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type PcloudPvminstancesVpmemVolumesPostForbidden struct {
	Payload *models.Error
}

// IsSuccess returns true when this pcloud pvminstances vpmem volumes post forbidden response has a 2xx status code
func (o *PcloudPvminstancesVpmemVolumesPostForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this pcloud pvminstances vpmem volumes post forbidden response has a 3xx status code
func (o *PcloudPvminstancesVpmemVolumesPostForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud pvminstances vpmem volumes post forbidden response has a 4xx status code
func (o *PcloudPvminstancesVpmemVolumesPostForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this pcloud pvminstances vpmem volumes post forbidden response has a 5xx status code
func (o *PcloudPvminstancesVpmemVolumesPostForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this pcloud pvminstances vpmem volumes post forbidden response a status code equal to that given
func (o *PcloudPvminstancesVpmemVolumesPostForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the pcloud pvminstances vpmem volumes post forbidden response
func (o *PcloudPvminstancesVpmemVolumesPostForbidden) Code() int {
	return 403
}

func (o *PcloudPvminstancesVpmemVolumesPostForbidden) Error() string {
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/vpmem-volumes][%d] pcloudPvminstancesVpmemVolumesPostForbidden  %+v", 403, o.Payload)
}

func (o *PcloudPvminstancesVpmemVolumesPostForbidden) String() string {
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/vpmem-volumes][%d] pcloudPvminstancesVpmemVolumesPostForbidden  %+v", 403, o.Payload)
}

func (o *PcloudPvminstancesVpmemVolumesPostForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *PcloudPvminstancesVpmemVolumesPostForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPcloudPvminstancesVpmemVolumesPostNotFound creates a PcloudPvminstancesVpmemVolumesPostNotFound with default headers values
func NewPcloudPvminstancesVpmemVolumesPostNotFound() *PcloudPvminstancesVpmemVolumesPostNotFound {
	return &PcloudPvminstancesVpmemVolumesPostNotFound{}
}

/*
PcloudPvminstancesVpmemVolumesPostNotFound describes a response with status code 404, with default header values.

Not Found
*/
type PcloudPvminstancesVpmemVolumesPostNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this pcloud pvminstances vpmem volumes post not found response has a 2xx status code
func (o *PcloudPvminstancesVpmemVolumesPostNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this pcloud pvminstances vpmem volumes post not found response has a 3xx status code
func (o *PcloudPvminstancesVpmemVolumesPostNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud pvminstances vpmem volumes post not found response has a 4xx status code
func (o *PcloudPvminstancesVpmemVolumesPostNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this pcloud pvminstances vpmem volumes post not found response has a 5xx status code
func (o *PcloudPvminstancesVpmemVolumesPostNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this pcloud pvminstances vpmem volumes post not found response a status code equal to that given
func (o *PcloudPvminstancesVpmemVolumesPostNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the pcloud pvminstances vpmem volumes post not found response
func (o *PcloudPvminstancesVpmemVolumesPostNotFound) Code() int {
	return 404
}

func (o *PcloudPvminstancesVpmemVolumesPostNotFound) Error() string {
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/vpmem-volumes][%d] pcloudPvminstancesVpmemVolumesPostNotFound  %+v", 404, o.Payload)
}

func (o *PcloudPvminstancesVpmemVolumesPostNotFound) String() string {
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/vpmem-volumes][%d] pcloudPvminstancesVpmemVolumesPostNotFound  %+v", 404, o.Payload)
}

func (o *PcloudPvminstancesVpmemVolumesPostNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *PcloudPvminstancesVpmemVolumesPostNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPcloudPvminstancesVpmemVolumesPostConflict creates a PcloudPvminstancesVpmemVolumesPostConflict with default headers values
func NewPcloudPvminstancesVpmemVolumesPostConflict() *PcloudPvminstancesVpmemVolumesPostConflict {
	return &PcloudPvminstancesVpmemVolumesPostConflict{}
}

/*
PcloudPvminstancesVpmemVolumesPostConflict describes a response with status code 409, with default header values.

Conflict
*/
type PcloudPvminstancesVpmemVolumesPostConflict struct {
	Payload *models.Error
}

// IsSuccess returns true when this pcloud pvminstances vpmem volumes post conflict response has a 2xx status code
func (o *PcloudPvminstancesVpmemVolumesPostConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this pcloud pvminstances vpmem volumes post conflict response has a 3xx status code
func (o *PcloudPvminstancesVpmemVolumesPostConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud pvminstances vpmem volumes post conflict response has a 4xx status code
func (o *PcloudPvminstancesVpmemVolumesPostConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this pcloud pvminstances vpmem volumes post conflict response has a 5xx status code
func (o *PcloudPvminstancesVpmemVolumesPostConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this pcloud pvminstances vpmem volumes post conflict response a status code equal to that given
func (o *PcloudPvminstancesVpmemVolumesPostConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the pcloud pvminstances vpmem volumes post conflict response
func (o *PcloudPvminstancesVpmemVolumesPostConflict) Code() int {
	return 409
}

func (o *PcloudPvminstancesVpmemVolumesPostConflict) Error() string {
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/vpmem-volumes][%d] pcloudPvminstancesVpmemVolumesPostConflict  %+v", 409, o.Payload)
}

func (o *PcloudPvminstancesVpmemVolumesPostConflict) String() string {
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/vpmem-volumes][%d] pcloudPvminstancesVpmemVolumesPostConflict  %+v", 409, o.Payload)
}

func (o *PcloudPvminstancesVpmemVolumesPostConflict) GetPayload() *models.Error {
	return o.Payload
}

func (o *PcloudPvminstancesVpmemVolumesPostConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPcloudPvminstancesVpmemVolumesPostInternalServerError creates a PcloudPvminstancesVpmemVolumesPostInternalServerError with default headers values
func NewPcloudPvminstancesVpmemVolumesPostInternalServerError() *PcloudPvminstancesVpmemVolumesPostInternalServerError {
	return &PcloudPvminstancesVpmemVolumesPostInternalServerError{}
}

/*
PcloudPvminstancesVpmemVolumesPostInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PcloudPvminstancesVpmemVolumesPostInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this pcloud pvminstances vpmem volumes post internal server error response has a 2xx status code
func (o *PcloudPvminstancesVpmemVolumesPostInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this pcloud pvminstances vpmem volumes post internal server error response has a 3xx status code
func (o *PcloudPvminstancesVpmemVolumesPostInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud pvminstances vpmem volumes post internal server error response has a 4xx status code
func (o *PcloudPvminstancesVpmemVolumesPostInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this pcloud pvminstances vpmem volumes post internal server error response has a 5xx status code
func (o *PcloudPvminstancesVpmemVolumesPostInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this pcloud pvminstances vpmem volumes post internal server error response a status code equal to that given
func (o *PcloudPvminstancesVpmemVolumesPostInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the pcloud pvminstances vpmem volumes post internal server error response
func (o *PcloudPvminstancesVpmemVolumesPostInternalServerError) Code() int {
	return 500
}

func (o *PcloudPvminstancesVpmemVolumesPostInternalServerError) Error() string {
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/vpmem-volumes][%d] pcloudPvminstancesVpmemVolumesPostInternalServerError  %+v", 500, o.Payload)
}

func (o *PcloudPvminstancesVpmemVolumesPostInternalServerError) String() string {
	return fmt.Sprintf("[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/pvm-instances/{pvm_instance_id}/vpmem-volumes][%d] pcloudPvminstancesVpmemVolumesPostInternalServerError  %+v", 500, o.Payload)
}

func (o *PcloudPvminstancesVpmemVolumesPostInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *PcloudPvminstancesVpmemVolumesPostInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
