// Code generated by go-swagger; DO NOT EDIT.

package internal_operations_shared_processor_pools

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/IBM-Cloud/power-go-client/power/models"
)

// NewInternalV1OperationsSharedprocessorpoolsPostParams creates a new InternalV1OperationsSharedprocessorpoolsPostParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewInternalV1OperationsSharedprocessorpoolsPostParams() *InternalV1OperationsSharedprocessorpoolsPostParams {
	return &InternalV1OperationsSharedprocessorpoolsPostParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewInternalV1OperationsSharedprocessorpoolsPostParamsWithTimeout creates a new InternalV1OperationsSharedprocessorpoolsPostParams object
// with the ability to set a timeout on a request.
func NewInternalV1OperationsSharedprocessorpoolsPostParamsWithTimeout(timeout time.Duration) *InternalV1OperationsSharedprocessorpoolsPostParams {
	return &InternalV1OperationsSharedprocessorpoolsPostParams{
		timeout: timeout,
	}
}

// NewInternalV1OperationsSharedprocessorpoolsPostParamsWithContext creates a new InternalV1OperationsSharedprocessorpoolsPostParams object
// with the ability to set a context for a request.
func NewInternalV1OperationsSharedprocessorpoolsPostParamsWithContext(ctx context.Context) *InternalV1OperationsSharedprocessorpoolsPostParams {
	return &InternalV1OperationsSharedprocessorpoolsPostParams{
		Context: ctx,
	}
}

// NewInternalV1OperationsSharedprocessorpoolsPostParamsWithHTTPClient creates a new InternalV1OperationsSharedprocessorpoolsPostParams object
// with the ability to set a custom HTTPClient for a request.
func NewInternalV1OperationsSharedprocessorpoolsPostParamsWithHTTPClient(client *http.Client) *InternalV1OperationsSharedprocessorpoolsPostParams {
	return &InternalV1OperationsSharedprocessorpoolsPostParams{
		HTTPClient: client,
	}
}

/*
InternalV1OperationsSharedprocessorpoolsPostParams contains all the parameters to send to the API endpoint

	for the internal v1 operations sharedprocessorpools post operation.

	Typically these are written to a http.Request.
*/
type InternalV1OperationsSharedprocessorpoolsPostParams struct {

	/* Body.

	   Parameters for creating a Shared Processor Pool CRN
	*/
	Body *models.InternalOperationsRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the internal v1 operations sharedprocessorpools post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *InternalV1OperationsSharedprocessorpoolsPostParams) WithDefaults() *InternalV1OperationsSharedprocessorpoolsPostParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the internal v1 operations sharedprocessorpools post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *InternalV1OperationsSharedprocessorpoolsPostParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the internal v1 operations sharedprocessorpools post params
func (o *InternalV1OperationsSharedprocessorpoolsPostParams) WithTimeout(timeout time.Duration) *InternalV1OperationsSharedprocessorpoolsPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the internal v1 operations sharedprocessorpools post params
func (o *InternalV1OperationsSharedprocessorpoolsPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the internal v1 operations sharedprocessorpools post params
func (o *InternalV1OperationsSharedprocessorpoolsPostParams) WithContext(ctx context.Context) *InternalV1OperationsSharedprocessorpoolsPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the internal v1 operations sharedprocessorpools post params
func (o *InternalV1OperationsSharedprocessorpoolsPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the internal v1 operations sharedprocessorpools post params
func (o *InternalV1OperationsSharedprocessorpoolsPostParams) WithHTTPClient(client *http.Client) *InternalV1OperationsSharedprocessorpoolsPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the internal v1 operations sharedprocessorpools post params
func (o *InternalV1OperationsSharedprocessorpoolsPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the internal v1 operations sharedprocessorpools post params
func (o *InternalV1OperationsSharedprocessorpoolsPostParams) WithBody(body *models.InternalOperationsRequest) *InternalV1OperationsSharedprocessorpoolsPostParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the internal v1 operations sharedprocessorpools post params
func (o *InternalV1OperationsSharedprocessorpoolsPostParams) SetBody(body *models.InternalOperationsRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *InternalV1OperationsSharedprocessorpoolsPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
