// Code generated by go-swagger; DO NOT EDIT.

package p_cloud_async_jobs

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/IBM-Cloud/power-go-client/power/models"
)

// PcloudV1CloudinstancesAsyncjobsGetallReader is a Reader for the PcloudV1CloudinstancesAsyncjobsGetall structure.
type PcloudV1CloudinstancesAsyncjobsGetallReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PcloudV1CloudinstancesAsyncjobsGetallReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPcloudV1CloudinstancesAsyncjobsGetallOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPcloudV1CloudinstancesAsyncjobsGetallBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPcloudV1CloudinstancesAsyncjobsGetallUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPcloudV1CloudinstancesAsyncjobsGetallForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPcloudV1CloudinstancesAsyncjobsGetallNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPcloudV1CloudinstancesAsyncjobsGetallInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /pcloud/v1/cloud-instances/{cloud_instance_id}/async-jobs] pcloud.v1.cloudinstances.asyncjobs.getall", response, response.Code())
	}
}

// NewPcloudV1CloudinstancesAsyncjobsGetallOK creates a PcloudV1CloudinstancesAsyncjobsGetallOK with default headers values
func NewPcloudV1CloudinstancesAsyncjobsGetallOK() *PcloudV1CloudinstancesAsyncjobsGetallOK {
	return &PcloudV1CloudinstancesAsyncjobsGetallOK{}
}

/*
PcloudV1CloudinstancesAsyncjobsGetallOK describes a response with status code 200, with default header values.

OK
*/
type PcloudV1CloudinstancesAsyncjobsGetallOK struct {
	Payload *models.AsyncJobs
}

// IsSuccess returns true when this pcloud v1 cloudinstances asyncjobs getall o k response has a 2xx status code
func (o *PcloudV1CloudinstancesAsyncjobsGetallOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this pcloud v1 cloudinstances asyncjobs getall o k response has a 3xx status code
func (o *PcloudV1CloudinstancesAsyncjobsGetallOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud v1 cloudinstances asyncjobs getall o k response has a 4xx status code
func (o *PcloudV1CloudinstancesAsyncjobsGetallOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this pcloud v1 cloudinstances asyncjobs getall o k response has a 5xx status code
func (o *PcloudV1CloudinstancesAsyncjobsGetallOK) IsServerError() bool {
	return false
}

// IsCode returns true when this pcloud v1 cloudinstances asyncjobs getall o k response a status code equal to that given
func (o *PcloudV1CloudinstancesAsyncjobsGetallOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the pcloud v1 cloudinstances asyncjobs getall o k response
func (o *PcloudV1CloudinstancesAsyncjobsGetallOK) Code() int {
	return 200
}

func (o *PcloudV1CloudinstancesAsyncjobsGetallOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /pcloud/v1/cloud-instances/{cloud_instance_id}/async-jobs][%d] pcloudV1CloudinstancesAsyncjobsGetallOK %s", 200, payload)
}

func (o *PcloudV1CloudinstancesAsyncjobsGetallOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /pcloud/v1/cloud-instances/{cloud_instance_id}/async-jobs][%d] pcloudV1CloudinstancesAsyncjobsGetallOK %s", 200, payload)
}

func (o *PcloudV1CloudinstancesAsyncjobsGetallOK) GetPayload() *models.AsyncJobs {
	return o.Payload
}

func (o *PcloudV1CloudinstancesAsyncjobsGetallOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AsyncJobs)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPcloudV1CloudinstancesAsyncjobsGetallBadRequest creates a PcloudV1CloudinstancesAsyncjobsGetallBadRequest with default headers values
func NewPcloudV1CloudinstancesAsyncjobsGetallBadRequest() *PcloudV1CloudinstancesAsyncjobsGetallBadRequest {
	return &PcloudV1CloudinstancesAsyncjobsGetallBadRequest{}
}

/*
PcloudV1CloudinstancesAsyncjobsGetallBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PcloudV1CloudinstancesAsyncjobsGetallBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this pcloud v1 cloudinstances asyncjobs getall bad request response has a 2xx status code
func (o *PcloudV1CloudinstancesAsyncjobsGetallBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this pcloud v1 cloudinstances asyncjobs getall bad request response has a 3xx status code
func (o *PcloudV1CloudinstancesAsyncjobsGetallBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud v1 cloudinstances asyncjobs getall bad request response has a 4xx status code
func (o *PcloudV1CloudinstancesAsyncjobsGetallBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this pcloud v1 cloudinstances asyncjobs getall bad request response has a 5xx status code
func (o *PcloudV1CloudinstancesAsyncjobsGetallBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this pcloud v1 cloudinstances asyncjobs getall bad request response a status code equal to that given
func (o *PcloudV1CloudinstancesAsyncjobsGetallBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the pcloud v1 cloudinstances asyncjobs getall bad request response
func (o *PcloudV1CloudinstancesAsyncjobsGetallBadRequest) Code() int {
	return 400
}

func (o *PcloudV1CloudinstancesAsyncjobsGetallBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /pcloud/v1/cloud-instances/{cloud_instance_id}/async-jobs][%d] pcloudV1CloudinstancesAsyncjobsGetallBadRequest %s", 400, payload)
}

func (o *PcloudV1CloudinstancesAsyncjobsGetallBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /pcloud/v1/cloud-instances/{cloud_instance_id}/async-jobs][%d] pcloudV1CloudinstancesAsyncjobsGetallBadRequest %s", 400, payload)
}

func (o *PcloudV1CloudinstancesAsyncjobsGetallBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *PcloudV1CloudinstancesAsyncjobsGetallBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPcloudV1CloudinstancesAsyncjobsGetallUnauthorized creates a PcloudV1CloudinstancesAsyncjobsGetallUnauthorized with default headers values
func NewPcloudV1CloudinstancesAsyncjobsGetallUnauthorized() *PcloudV1CloudinstancesAsyncjobsGetallUnauthorized {
	return &PcloudV1CloudinstancesAsyncjobsGetallUnauthorized{}
}

/*
PcloudV1CloudinstancesAsyncjobsGetallUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PcloudV1CloudinstancesAsyncjobsGetallUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this pcloud v1 cloudinstances asyncjobs getall unauthorized response has a 2xx status code
func (o *PcloudV1CloudinstancesAsyncjobsGetallUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this pcloud v1 cloudinstances asyncjobs getall unauthorized response has a 3xx status code
func (o *PcloudV1CloudinstancesAsyncjobsGetallUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud v1 cloudinstances asyncjobs getall unauthorized response has a 4xx status code
func (o *PcloudV1CloudinstancesAsyncjobsGetallUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this pcloud v1 cloudinstances asyncjobs getall unauthorized response has a 5xx status code
func (o *PcloudV1CloudinstancesAsyncjobsGetallUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this pcloud v1 cloudinstances asyncjobs getall unauthorized response a status code equal to that given
func (o *PcloudV1CloudinstancesAsyncjobsGetallUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the pcloud v1 cloudinstances asyncjobs getall unauthorized response
func (o *PcloudV1CloudinstancesAsyncjobsGetallUnauthorized) Code() int {
	return 401
}

func (o *PcloudV1CloudinstancesAsyncjobsGetallUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /pcloud/v1/cloud-instances/{cloud_instance_id}/async-jobs][%d] pcloudV1CloudinstancesAsyncjobsGetallUnauthorized %s", 401, payload)
}

func (o *PcloudV1CloudinstancesAsyncjobsGetallUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /pcloud/v1/cloud-instances/{cloud_instance_id}/async-jobs][%d] pcloudV1CloudinstancesAsyncjobsGetallUnauthorized %s", 401, payload)
}

func (o *PcloudV1CloudinstancesAsyncjobsGetallUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *PcloudV1CloudinstancesAsyncjobsGetallUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPcloudV1CloudinstancesAsyncjobsGetallForbidden creates a PcloudV1CloudinstancesAsyncjobsGetallForbidden with default headers values
func NewPcloudV1CloudinstancesAsyncjobsGetallForbidden() *PcloudV1CloudinstancesAsyncjobsGetallForbidden {
	return &PcloudV1CloudinstancesAsyncjobsGetallForbidden{}
}

/*
PcloudV1CloudinstancesAsyncjobsGetallForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type PcloudV1CloudinstancesAsyncjobsGetallForbidden struct {
	Payload *models.Error
}

// IsSuccess returns true when this pcloud v1 cloudinstances asyncjobs getall forbidden response has a 2xx status code
func (o *PcloudV1CloudinstancesAsyncjobsGetallForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this pcloud v1 cloudinstances asyncjobs getall forbidden response has a 3xx status code
func (o *PcloudV1CloudinstancesAsyncjobsGetallForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud v1 cloudinstances asyncjobs getall forbidden response has a 4xx status code
func (o *PcloudV1CloudinstancesAsyncjobsGetallForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this pcloud v1 cloudinstances asyncjobs getall forbidden response has a 5xx status code
func (o *PcloudV1CloudinstancesAsyncjobsGetallForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this pcloud v1 cloudinstances asyncjobs getall forbidden response a status code equal to that given
func (o *PcloudV1CloudinstancesAsyncjobsGetallForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the pcloud v1 cloudinstances asyncjobs getall forbidden response
func (o *PcloudV1CloudinstancesAsyncjobsGetallForbidden) Code() int {
	return 403
}

func (o *PcloudV1CloudinstancesAsyncjobsGetallForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /pcloud/v1/cloud-instances/{cloud_instance_id}/async-jobs][%d] pcloudV1CloudinstancesAsyncjobsGetallForbidden %s", 403, payload)
}

func (o *PcloudV1CloudinstancesAsyncjobsGetallForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /pcloud/v1/cloud-instances/{cloud_instance_id}/async-jobs][%d] pcloudV1CloudinstancesAsyncjobsGetallForbidden %s", 403, payload)
}

func (o *PcloudV1CloudinstancesAsyncjobsGetallForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *PcloudV1CloudinstancesAsyncjobsGetallForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPcloudV1CloudinstancesAsyncjobsGetallNotFound creates a PcloudV1CloudinstancesAsyncjobsGetallNotFound with default headers values
func NewPcloudV1CloudinstancesAsyncjobsGetallNotFound() *PcloudV1CloudinstancesAsyncjobsGetallNotFound {
	return &PcloudV1CloudinstancesAsyncjobsGetallNotFound{}
}

/*
PcloudV1CloudinstancesAsyncjobsGetallNotFound describes a response with status code 404, with default header values.

Not Found
*/
type PcloudV1CloudinstancesAsyncjobsGetallNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this pcloud v1 cloudinstances asyncjobs getall not found response has a 2xx status code
func (o *PcloudV1CloudinstancesAsyncjobsGetallNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this pcloud v1 cloudinstances asyncjobs getall not found response has a 3xx status code
func (o *PcloudV1CloudinstancesAsyncjobsGetallNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud v1 cloudinstances asyncjobs getall not found response has a 4xx status code
func (o *PcloudV1CloudinstancesAsyncjobsGetallNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this pcloud v1 cloudinstances asyncjobs getall not found response has a 5xx status code
func (o *PcloudV1CloudinstancesAsyncjobsGetallNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this pcloud v1 cloudinstances asyncjobs getall not found response a status code equal to that given
func (o *PcloudV1CloudinstancesAsyncjobsGetallNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the pcloud v1 cloudinstances asyncjobs getall not found response
func (o *PcloudV1CloudinstancesAsyncjobsGetallNotFound) Code() int {
	return 404
}

func (o *PcloudV1CloudinstancesAsyncjobsGetallNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /pcloud/v1/cloud-instances/{cloud_instance_id}/async-jobs][%d] pcloudV1CloudinstancesAsyncjobsGetallNotFound %s", 404, payload)
}

func (o *PcloudV1CloudinstancesAsyncjobsGetallNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /pcloud/v1/cloud-instances/{cloud_instance_id}/async-jobs][%d] pcloudV1CloudinstancesAsyncjobsGetallNotFound %s", 404, payload)
}

func (o *PcloudV1CloudinstancesAsyncjobsGetallNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *PcloudV1CloudinstancesAsyncjobsGetallNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPcloudV1CloudinstancesAsyncjobsGetallInternalServerError creates a PcloudV1CloudinstancesAsyncjobsGetallInternalServerError with default headers values
func NewPcloudV1CloudinstancesAsyncjobsGetallInternalServerError() *PcloudV1CloudinstancesAsyncjobsGetallInternalServerError {
	return &PcloudV1CloudinstancesAsyncjobsGetallInternalServerError{}
}

/*
PcloudV1CloudinstancesAsyncjobsGetallInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PcloudV1CloudinstancesAsyncjobsGetallInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this pcloud v1 cloudinstances asyncjobs getall internal server error response has a 2xx status code
func (o *PcloudV1CloudinstancesAsyncjobsGetallInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this pcloud v1 cloudinstances asyncjobs getall internal server error response has a 3xx status code
func (o *PcloudV1CloudinstancesAsyncjobsGetallInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pcloud v1 cloudinstances asyncjobs getall internal server error response has a 4xx status code
func (o *PcloudV1CloudinstancesAsyncjobsGetallInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this pcloud v1 cloudinstances asyncjobs getall internal server error response has a 5xx status code
func (o *PcloudV1CloudinstancesAsyncjobsGetallInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this pcloud v1 cloudinstances asyncjobs getall internal server error response a status code equal to that given
func (o *PcloudV1CloudinstancesAsyncjobsGetallInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the pcloud v1 cloudinstances asyncjobs getall internal server error response
func (o *PcloudV1CloudinstancesAsyncjobsGetallInternalServerError) Code() int {
	return 500
}

func (o *PcloudV1CloudinstancesAsyncjobsGetallInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /pcloud/v1/cloud-instances/{cloud_instance_id}/async-jobs][%d] pcloudV1CloudinstancesAsyncjobsGetallInternalServerError %s", 500, payload)
}

func (o *PcloudV1CloudinstancesAsyncjobsGetallInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /pcloud/v1/cloud-instances/{cloud_instance_id}/async-jobs][%d] pcloudV1CloudinstancesAsyncjobsGetallInternalServerError %s", 500, payload)
}

func (o *PcloudV1CloudinstancesAsyncjobsGetallInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *PcloudV1CloudinstancesAsyncjobsGetallInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
