// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AsyncJob async job
//
// swagger:model AsyncJob
type AsyncJob struct {

	// The action being performed in the job
	// Required: true
	Action *string `json:"action"`

	// Array of child jobs
	ChildJobs []*ChildAsyncJob `json:"childJobs,omitempty"`

	// Date job completed
	// Format: date-time
	CompletionDate strfmt.DateTime `json:"completionDate,omitempty"`

	// Date job was created
	// Required: true
	// Format: date-time
	CreationDate *strfmt.DateTime `json:"creationDate"`

	// Detailed information of error encountered during job processing
	ErrorMessage string `json:"errorMessage,omitempty"`

	// ID of asynchronous job
	// Required: true
	ID *string `json:"id"`

	// Input values of the operation being tracked by the job
	InputValues map[string]any `json:"inputValues,omitempty"`

	// Date job was last updated
	// Format: date-time
	LastUpdateDate strfmt.DateTime `json:"lastUpdateDate,omitempty"`

	// Input values of the operation being tracked by the job
	OutputValues map[string]any `json:"outputValues,omitempty"`

	// ID of the parent async job
	ParentAsyncJobID string `json:"parentAsyncJobID,omitempty"`

	// Percentage of how much of the job has completed
	// Required: true
	ProgressPercent *int64 `json:"progressPercent"`

	// ID of the resource being acted upon in job
	// Required: true
	ResourceID *string `json:"resourceID"`

	// Type of resource being acted upon in job
	// Required: true
	ResourceType *string `json:"resourceType"`

	// Status of the job
	// Required: true
	Status *string `json:"status"`
}

// Validate validates this async job
func (m *AsyncJob) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAction(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateChildJobs(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCompletionDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreationDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLastUpdateDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProgressPercent(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResourceID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResourceType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AsyncJob) validateAction(formats strfmt.Registry) error {

	if err := validate.Required("action", "body", m.Action); err != nil {
		return err
	}

	return nil
}

func (m *AsyncJob) validateChildJobs(formats strfmt.Registry) error {
	if swag.IsZero(m.ChildJobs) { // not required
		return nil
	}

	for i := 0; i < len(m.ChildJobs); i++ {
		if swag.IsZero(m.ChildJobs[i]) { // not required
			continue
		}

		if m.ChildJobs[i] != nil {
			if err := m.ChildJobs[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("childJobs" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("childJobs" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *AsyncJob) validateCompletionDate(formats strfmt.Registry) error {
	if swag.IsZero(m.CompletionDate) { // not required
		return nil
	}

	if err := validate.FormatOf("completionDate", "body", "date-time", m.CompletionDate.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *AsyncJob) validateCreationDate(formats strfmt.Registry) error {

	if err := validate.Required("creationDate", "body", m.CreationDate); err != nil {
		return err
	}

	if err := validate.FormatOf("creationDate", "body", "date-time", m.CreationDate.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *AsyncJob) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *AsyncJob) validateLastUpdateDate(formats strfmt.Registry) error {
	if swag.IsZero(m.LastUpdateDate) { // not required
		return nil
	}

	if err := validate.FormatOf("lastUpdateDate", "body", "date-time", m.LastUpdateDate.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *AsyncJob) validateProgressPercent(formats strfmt.Registry) error {

	if err := validate.Required("progressPercent", "body", m.ProgressPercent); err != nil {
		return err
	}

	return nil
}

func (m *AsyncJob) validateResourceID(formats strfmt.Registry) error {

	if err := validate.Required("resourceID", "body", m.ResourceID); err != nil {
		return err
	}

	return nil
}

func (m *AsyncJob) validateResourceType(formats strfmt.Registry) error {

	if err := validate.Required("resourceType", "body", m.ResourceType); err != nil {
		return err
	}

	return nil
}

func (m *AsyncJob) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("status", "body", m.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this async job based on the context it is used
func (m *AsyncJob) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateChildJobs(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AsyncJob) contextValidateChildJobs(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ChildJobs); i++ {

		if m.ChildJobs[i] != nil {

			if swag.IsZero(m.ChildJobs[i]) { // not required
				return nil
			}

			if err := m.ChildJobs[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("childJobs" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("childJobs" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *AsyncJob) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AsyncJob) UnmarshalBinary(b []byte) error {
	var res AsyncJob
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
