// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AsyncJobs async jobs
//
// swagger:model AsyncJobs
type AsyncJobs struct {

	// List of asynchronous jobs
	// Required: true
	AsyncJobs []*AsyncJob `json:"asyncJobs"`
}

// Validate validates this async jobs
func (m *AsyncJobs) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAsyncJobs(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AsyncJobs) validateAsyncJobs(formats strfmt.Registry) error {

	if err := validate.Required("asyncJobs", "body", m.AsyncJobs); err != nil {
		return err
	}

	for i := 0; i < len(m.AsyncJobs); i++ {
		if swag.IsZero(m.AsyncJobs[i]) { // not required
			continue
		}

		if m.AsyncJobs[i] != nil {
			if err := m.AsyncJobs[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("asyncJobs" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("asyncJobs" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this async jobs based on the context it is used
func (m *AsyncJobs) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAsyncJobs(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AsyncJobs) contextValidateAsyncJobs(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.AsyncJobs); i++ {

		if m.AsyncJobs[i] != nil {

			if swag.IsZero(m.AsyncJobs[i]) { // not required
				return nil
			}

			if err := m.AsyncJobs[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("asyncJobs" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("asyncJobs" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *AsyncJobs) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AsyncJobs) UnmarshalBinary(b []byte) error {
	var res AsyncJobs
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
