// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AuthnInfo authn info
//
// swagger:model AuthnInfo
type AuthnInfo struct {

	// authentication iam id
	ID string `json:"id,omitempty"`

	// authentication name
	Name string `json:"name,omitempty"`

	// authentication subject id
	Subject string `json:"subject,omitempty"`
}

// Validate validates this authn info
func (m *AuthnInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this authn info based on context it is used
func (m *AuthnInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AuthnInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AuthnInfo) UnmarshalBinary(b []byte) error {
	var res AuthnInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
