// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// BulkNaming bulk naming
//
// swagger:model BulkNaming
type BulkNaming struct {

	// Bulk naming will consist of 4 parts. The 1st part will be the prefix "clone-". The 2nd part will be the user supplied baseName. The 3rd part is an optional user selected suffix.  The 4th and final part will be a dash (-) plus an ascending sequence number, starting with 1. If the VOLUME-NAME is selected for the 2nd part baseName, then part 4 will only be added if the volume name will not be unique.
	// Required: true
	BaseName *string `json:"baseName"`

	// Each cloned volume name may be appended by an optional suffix. A suffix can be one of; "DATE-TIME" or "5-RANDOM-DIGITS". If DATE-TIME is specified, then the current UTC date and time will be used in the format (yyyy-mm-dd_hh-mm-ss.nnn). If 5-RANDOM-DIGITS is specified, then a random 5-digit number will be generated.
	Suffix string `json:"suffix,omitempty"`
}

// Validate validates this bulk naming
func (m *BulkNaming) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBaseName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BulkNaming) validateBaseName(formats strfmt.Registry) error {

	if err := validate.Required("baseName", "body", m.BaseName); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this bulk naming based on context it is used
func (m *BulkNaming) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BulkNaming) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BulkNaming) UnmarshalBinary(b []byte) error {
	var res BulkNaming
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
