// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ChildAsyncJob child async job
//
// swagger:model ChildAsyncJob
type ChildAsyncJob struct {

	// Action of the job
	// Required: true
	Action *string `json:"action"`

	// ID of child job
	// Required: true
	ID *string `json:"id"`

	// Progress percentage of the job
	ProgressPercent int64 `json:"progressPercent,omitempty"`

	// ID of the resource being acted upon in job
	// Required: true
	ResourceID *string `json:"resourceID"`

	// Type of resource being acted upon in job
	// Required: true
	ResourceType *string `json:"resourceType"`

	// Status of the job
	// Required: true
	Status *string `json:"status"`
}

// Validate validates this child async job
func (m *ChildAsyncJob) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAction(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResourceID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResourceType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ChildAsyncJob) validateAction(formats strfmt.Registry) error {

	if err := validate.Required("action", "body", m.Action); err != nil {
		return err
	}

	return nil
}

func (m *ChildAsyncJob) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *ChildAsyncJob) validateResourceID(formats strfmt.Registry) error {

	if err := validate.Required("resourceID", "body", m.ResourceID); err != nil {
		return err
	}

	return nil
}

func (m *ChildAsyncJob) validateResourceType(formats strfmt.Registry) error {

	if err := validate.Required("resourceType", "body", m.ResourceType); err != nil {
		return err
	}

	return nil
}

func (m *ChildAsyncJob) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("status", "body", m.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this child async job based on context it is used
func (m *ChildAsyncJob) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ChildAsyncJob) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ChildAsyncJob) UnmarshalBinary(b []byte) error {
	var res ChildAsyncJob
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
