// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CloneVolumeNamingScheme clone volume naming scheme
//
// swagger:model CloneVolumeNamingScheme
type CloneVolumeNamingScheme struct {

	// Bulk naming will consist of 4 parts. The 1st part will be the prefix "clone-". The 2nd part will be the user supplied baseName. The 3rd part is an optional user selected suffix.  The 4th and final part will be a dash (-) plus an ascending sequence number, starting with 1. If the VOLUME-NAME is selected for the 2nd part baseName, then part 4 will only be added if the volume name will not be unique.
	BulkNaming *BulkNaming `json:"bulkNaming,omitempty"`

	// A list of source to clone volume names
	VolumeNaming []*VolumeNaming `json:"volumeNaming,omitempty"`
}

// Validate validates this clone volume naming scheme
func (m *CloneVolumeNamingScheme) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBulkNaming(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVolumeNaming(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CloneVolumeNamingScheme) validateBulkNaming(formats strfmt.Registry) error {
	if swag.IsZero(m.BulkNaming) { // not required
		return nil
	}

	if m.BulkNaming != nil {
		if err := m.BulkNaming.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("bulkNaming")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("bulkNaming")
			}

			return err
		}
	}

	return nil
}

func (m *CloneVolumeNamingScheme) validateVolumeNaming(formats strfmt.Registry) error {
	if swag.IsZero(m.VolumeNaming) { // not required
		return nil
	}

	for i := 0; i < len(m.VolumeNaming); i++ {
		if swag.IsZero(m.VolumeNaming[i]) { // not required
			continue
		}

		if m.VolumeNaming[i] != nil {
			if err := m.VolumeNaming[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("volumeNaming" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("volumeNaming" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this clone volume naming scheme based on the context it is used
func (m *CloneVolumeNamingScheme) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateBulkNaming(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateVolumeNaming(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CloneVolumeNamingScheme) contextValidateBulkNaming(ctx context.Context, formats strfmt.Registry) error {

	if m.BulkNaming != nil {

		if swag.IsZero(m.BulkNaming) { // not required
			return nil
		}

		if err := m.BulkNaming.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("bulkNaming")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("bulkNaming")
			}

			return err
		}
	}

	return nil
}

func (m *CloneVolumeNamingScheme) contextValidateVolumeNaming(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.VolumeNaming); i++ {

		if m.VolumeNaming[i] != nil {

			if swag.IsZero(m.VolumeNaming[i]) { // not required
				return nil
			}

			if err := m.VolumeNaming[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("volumeNaming" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("volumeNaming" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *CloneVolumeNamingScheme) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CloneVolumeNamingScheme) UnmarshalBinary(b []byte) error {
	var res CloneVolumeNamingScheme
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
