// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// CloneVolumesResponse clone volumes response
// swagger:model CloneVolumesResponse
type CloneVolumesResponse struct {

	// A map of volume IDs to cloned volume IDs
	ClonedVolumes map[string]string `json:"clonedVolumes,omitempty"`
}

// Validate validates this clone volumes response
func (m *CloneVolumesResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CloneVolumesResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CloneVolumesResponse) UnmarshalBinary(b []byte) error {
	var res CloneVolumesResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
