// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ClonedVolumeSnapshot cloned volume snapshot
//
// swagger:model ClonedVolumeSnapshot
type ClonedVolumeSnapshot struct {

	// CRN of the cloned volume PDS resource
	// Required: true
	CloneCRN *CRN `json:"cloneCRN"`

	// External UUID of the cloned volume PDS resource
	// Required: true
	CloneID *string `json:"cloneID"`

	// Name of the cloned volume PDS resource
	// Required: true
	CloneName *string `json:"cloneName"`

	// CRN of the source volume to be cloned
	// Required: true
	SrcVolumeCRN *CRN `json:"srcVolumeCRN"`

	// user tags
	UserTags Tags `json:"userTags,omitempty"`
}

// Validate validates this cloned volume snapshot
func (m *ClonedVolumeSnapshot) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCloneCRN(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCloneID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCloneName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSrcVolumeCRN(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserTags(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ClonedVolumeSnapshot) validateCloneCRN(formats strfmt.Registry) error {

	if err := validate.Required("cloneCRN", "body", m.CloneCRN); err != nil {
		return err
	}

	if m.CloneCRN != nil {
		if err := m.CloneCRN.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("cloneCRN")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("cloneCRN")
			}

			return err
		}
	}

	return nil
}

func (m *ClonedVolumeSnapshot) validateCloneID(formats strfmt.Registry) error {

	if err := validate.Required("cloneID", "body", m.CloneID); err != nil {
		return err
	}

	return nil
}

func (m *ClonedVolumeSnapshot) validateCloneName(formats strfmt.Registry) error {

	if err := validate.Required("cloneName", "body", m.CloneName); err != nil {
		return err
	}

	return nil
}

func (m *ClonedVolumeSnapshot) validateSrcVolumeCRN(formats strfmt.Registry) error {

	if err := validate.Required("srcVolumeCRN", "body", m.SrcVolumeCRN); err != nil {
		return err
	}

	if m.SrcVolumeCRN != nil {
		if err := m.SrcVolumeCRN.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("srcVolumeCRN")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("srcVolumeCRN")
			}

			return err
		}
	}

	return nil
}

func (m *ClonedVolumeSnapshot) validateUserTags(formats strfmt.Registry) error {
	if swag.IsZero(m.UserTags) { // not required
		return nil
	}

	if err := m.UserTags.Validate(formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("userTags")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("userTags")
		}

		return err
	}

	return nil
}

// ContextValidate validate this cloned volume snapshot based on the context it is used
func (m *ClonedVolumeSnapshot) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCloneCRN(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSrcVolumeCRN(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUserTags(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ClonedVolumeSnapshot) contextValidateCloneCRN(ctx context.Context, formats strfmt.Registry) error {

	if m.CloneCRN != nil {

		if err := m.CloneCRN.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("cloneCRN")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("cloneCRN")
			}

			return err
		}
	}

	return nil
}

func (m *ClonedVolumeSnapshot) contextValidateSrcVolumeCRN(ctx context.Context, formats strfmt.Registry) error {

	if m.SrcVolumeCRN != nil {

		if err := m.SrcVolumeCRN.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("srcVolumeCRN")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("srcVolumeCRN")
			}

			return err
		}
	}

	return nil
}

func (m *ClonedVolumeSnapshot) contextValidateUserTags(ctx context.Context, formats strfmt.Registry) error {

	if err := m.UserTags.ContextValidate(ctx, formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("userTags")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("userTags")
		}

		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ClonedVolumeSnapshot) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClonedVolumeSnapshot) UnmarshalBinary(b []byte) error {
	var res ClonedVolumeSnapshot
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
