// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CloneSnapshotRequest clone snapshot request
//
// swagger:model CloneSnapshotRequest
type CloneSnapshotRequest struct {

	// Provide the cloned volume naming scheme(s) that will be used to determine the name of each new cloned volume created from the instance snapshot.
	// Required: true
	CloneVolumeNamingScheme *CloneVolumeNamingScheme `json:"cloneVolumeNamingScheme"`

	// Target storage tier for the cloned volumes. Use to clone a set of volumes from one storage tier to a different storage tier. Only valid for an in-place instance snapshot.
	TargetStorageTier string `json:"targetStorageTier,omitempty"`

	// user tags
	UserTags Tags `json:"userTags,omitempty"`
}

// Validate validates this clone snapshot request
func (m *CloneSnapshotRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCloneVolumeNamingScheme(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserTags(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CloneSnapshotRequest) validateCloneVolumeNamingScheme(formats strfmt.Registry) error {

	if err := validate.Required("cloneVolumeNamingScheme", "body", m.CloneVolumeNamingScheme); err != nil {
		return err
	}

	if m.CloneVolumeNamingScheme != nil {
		if err := m.CloneVolumeNamingScheme.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("cloneVolumeNamingScheme")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("cloneVolumeNamingScheme")
			}

			return err
		}
	}

	return nil
}

func (m *CloneSnapshotRequest) validateUserTags(formats strfmt.Registry) error {
	if swag.IsZero(m.UserTags) { // not required
		return nil
	}

	if err := m.UserTags.Validate(formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("userTags")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("userTags")
		}

		return err
	}

	return nil
}

// ContextValidate validate this clone snapshot request based on the context it is used
func (m *CloneSnapshotRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCloneVolumeNamingScheme(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUserTags(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CloneSnapshotRequest) contextValidateCloneVolumeNamingScheme(ctx context.Context, formats strfmt.Registry) error {

	if m.CloneVolumeNamingScheme != nil {

		if err := m.CloneVolumeNamingScheme.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("cloneVolumeNamingScheme")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("cloneVolumeNamingScheme")
			}

			return err
		}
	}

	return nil
}

func (m *CloneSnapshotRequest) contextValidateUserTags(ctx context.Context, formats strfmt.Registry) error {

	if err := m.UserTags.ContextValidate(ctx, formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("userTags")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("userTags")
		}

		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CloneSnapshotRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CloneSnapshotRequest) UnmarshalBinary(b []byte) error {
	var res CloneSnapshotRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
