// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CopyVolume copy volume
//
// swagger:model CopyVolume
type CopyVolume struct {

	// The CRN of the copy volume
	// Required: true
	CopyVolumeCRN *CRN `json:"copyVolumeCRN"`

	// The ID of the copy volume
	// Required: true
	CopyVolumeID *string `json:"copyVolumeID"`

	// The Name of the copy volume
	// Required: true
	CopyVolumeName *string `json:"copyVolumeName"`

	// User tags associated with the copy volume
	CopyVolumeUserTags Tags `json:"copyVolumeUserTags,omitempty"`

	// The CRN of the source volume
	// Required: true
	SrcVolumeCRN *CRN `json:"srcVolumeCRN"`
}

// Validate validates this copy volume
func (m *CopyVolume) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCopyVolumeCRN(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCopyVolumeID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCopyVolumeName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCopyVolumeUserTags(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSrcVolumeCRN(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CopyVolume) validateCopyVolumeCRN(formats strfmt.Registry) error {

	if err := validate.Required("copyVolumeCRN", "body", m.CopyVolumeCRN); err != nil {
		return err
	}

	if m.CopyVolumeCRN != nil {
		if err := m.CopyVolumeCRN.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("copyVolumeCRN")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("copyVolumeCRN")
			}

			return err
		}
	}

	return nil
}

func (m *CopyVolume) validateCopyVolumeID(formats strfmt.Registry) error {

	if err := validate.Required("copyVolumeID", "body", m.CopyVolumeID); err != nil {
		return err
	}

	return nil
}

func (m *CopyVolume) validateCopyVolumeName(formats strfmt.Registry) error {

	if err := validate.Required("copyVolumeName", "body", m.CopyVolumeName); err != nil {
		return err
	}

	return nil
}

func (m *CopyVolume) validateCopyVolumeUserTags(formats strfmt.Registry) error {
	if swag.IsZero(m.CopyVolumeUserTags) { // not required
		return nil
	}

	if err := m.CopyVolumeUserTags.Validate(formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("copyVolumeUserTags")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("copyVolumeUserTags")
		}

		return err
	}

	return nil
}

func (m *CopyVolume) validateSrcVolumeCRN(formats strfmt.Registry) error {

	if err := validate.Required("srcVolumeCRN", "body", m.SrcVolumeCRN); err != nil {
		return err
	}

	if m.SrcVolumeCRN != nil {
		if err := m.SrcVolumeCRN.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("srcVolumeCRN")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("srcVolumeCRN")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this copy volume based on the context it is used
func (m *CopyVolume) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCopyVolumeCRN(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCopyVolumeUserTags(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSrcVolumeCRN(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CopyVolume) contextValidateCopyVolumeCRN(ctx context.Context, formats strfmt.Registry) error {

	if m.CopyVolumeCRN != nil {

		if err := m.CopyVolumeCRN.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("copyVolumeCRN")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("copyVolumeCRN")
			}

			return err
		}
	}

	return nil
}

func (m *CopyVolume) contextValidateCopyVolumeUserTags(ctx context.Context, formats strfmt.Registry) error {

	if err := m.CopyVolumeUserTags.ContextValidate(ctx, formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("copyVolumeUserTags")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("copyVolumeUserTags")
		}

		return err
	}

	return nil
}

func (m *CopyVolume) contextValidateSrcVolumeCRN(ctx context.Context, formats strfmt.Registry) error {

	if m.SrcVolumeCRN != nil {

		if err := m.SrcVolumeCRN.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("srcVolumeCRN")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("srcVolumeCRN")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CopyVolume) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CopyVolume) UnmarshalBinary(b []byte) error {
	var res CopyVolume
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
