// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DisasterRecovery disaster recovery
//
// swagger:model DisasterRecovery
type DisasterRecovery struct {

	// Disaster Recovery Information
	// Required: true
	ReplicationServices *ReplicationServices `json:"replicationServices"`
}

// Validate validates this disaster recovery
func (m *DisasterRecovery) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateReplicationServices(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DisasterRecovery) validateReplicationServices(formats strfmt.Registry) error {

	if err := validate.Required("replicationServices", "body", m.ReplicationServices); err != nil {
		return err
	}

	if m.ReplicationServices != nil {
		if err := m.ReplicationServices.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("replicationServices")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("replicationServices")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this disaster recovery based on the context it is used
func (m *DisasterRecovery) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateReplicationServices(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DisasterRecovery) contextValidateReplicationServices(ctx context.Context, formats strfmt.Registry) error {

	if m.ReplicationServices != nil {

		if err := m.ReplicationServices.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("replicationServices")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("replicationServices")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DisasterRecovery) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DisasterRecovery) UnmarshalBinary(b []byte) error {
	var res DisasterRecovery
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
