// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HostResourceCapacity host resource capacity
//
// swagger:model HostResourceCapacity
type HostResourceCapacity struct {

	// available
	Available float64 `json:"available,omitempty"`

	// reserved
	Reserved float64 `json:"reserved,omitempty"`

	// total
	Total float64 `json:"total,omitempty"`

	// used
	Used float64 `json:"used,omitempty"`
}

// Validate validates this host resource capacity
func (m *HostResourceCapacity) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this host resource capacity based on context it is used
func (m *HostResourceCapacity) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HostResourceCapacity) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HostResourceCapacity) UnmarshalBinary(b []byte) error {
	var res HostResourceCapacity
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
