// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NFSNetbootConfig NFS boot configuration for D-Mode IPL.
//
// swagger:model NFSNetbootConfig
type NFSNetbootConfig struct {

	// NFS directory containing the boot/installation image.
	// Required: true
	ServerDirectory *string `json:"serverDirectory"`

	// IP address of the NFS server.
	// Required: true
	ServerIPAddress *string `json:"serverIPAddress"`
}

// Validate validates this n f s netboot config
func (m *NFSNetbootConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateServerDirectory(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateServerIPAddress(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NFSNetbootConfig) validateServerDirectory(formats strfmt.Registry) error {

	if err := validate.Required("serverDirectory", "body", m.ServerDirectory); err != nil {
		return err
	}

	return nil
}

func (m *NFSNetbootConfig) validateServerIPAddress(formats strfmt.Registry) error {

	if err := validate.Required("serverIPAddress", "body", m.ServerIPAddress); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this n f s netboot config based on context it is used
func (m *NFSNetbootConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NFSNetbootConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NFSNetbootConfig) UnmarshalBinary(b []byte) error {
	var res NFSNetbootConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
