// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NetworkPeerCreate network peer create parameters
//
// swagger:model NetworkPeerCreate
type NetworkPeerCreate struct {
	NetworkPeerBase

	NetworkPeerCreateAllOf1
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *NetworkPeerCreate) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 NetworkPeerBase
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.NetworkPeerBase = aO0

	// AO1
	var aO1 NetworkPeerCreateAllOf1
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.NetworkPeerCreateAllOf1 = aO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m NetworkPeerCreate) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.NetworkPeerBase)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(m.NetworkPeerCreateAllOf1)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this network peer create
func (m *NetworkPeerCreate) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with NetworkPeerBase
	if err := m.NetworkPeerBase.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with NetworkPeerCreateAllOf1

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validate this network peer create based on the context it is used
func (m *NetworkPeerCreate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with NetworkPeerBase
	if err := m.NetworkPeerBase.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with NetworkPeerCreateAllOf1

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *NetworkPeerCreate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NetworkPeerCreate) UnmarshalBinary(b []byte) error {
	var res NetworkPeerCreate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// NetworkPeerCreateAllOf1 network peer create all of1
//
// swagger:model NetworkPeerCreateAllOf1
type NetworkPeerCreateAllOf1 interface{}
