// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NetworkInterfaceUpdate network interface update
//
// swagger:model NetworkInterfaceUpdate
type NetworkInterfaceUpdate struct {

	// Name of the Network Interface
	Name *string `json:"name,omitempty"`

	// ID of the Network Security Group the network interface will be added to, if empty detaches from Network Security Group
	NetworkSecurityGroupID string `json:"networkSecurityGroupID,omitempty"`

	// If supplied populated it attaches to the PVMInstanceID, if empty detaches from PVMInstanceID
	PvmInstanceID *string `json:"pvmInstanceID,omitempty"`
}

// Validate validates this network interface update
func (m *NetworkInterfaceUpdate) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this network interface update based on context it is used
func (m *NetworkInterfaceUpdate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NetworkInterfaceUpdate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NetworkInterfaceUpdate) UnmarshalBinary(b []byte) error {
	var res NetworkInterfaceUpdate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
