// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NetworkSecurityGroupRulePort network security group rule port
//
// swagger:model NetworkSecurityGroupRulePort
type NetworkSecurityGroupRulePort struct {

	// The end of the port range, if applicable, If values are not present then all ports are in the range
	Maximum float64 `json:"maximum,omitempty"`

	// The start of the port range, if applicable. If values are not present then all ports are in the range
	Minimum float64 `json:"minimum,omitempty"`
}

// Validate validates this network security group rule port
func (m *NetworkSecurityGroupRulePort) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this network security group rule port based on context it is used
func (m *NetworkSecurityGroupRulePort) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NetworkSecurityGroupRulePort) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NetworkSecurityGroupRulePort) UnmarshalBinary(b []byte) error {
	var res NetworkSecurityGroupRulePort
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
