// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	"encoding/json"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PVMInstanceUnshelve p VM instance unshelve
//
// swagger:model PVMInstanceUnshelve
type PVMInstanceUnshelve struct {

	// The dedicated host or host group where the VSI is to be placed.
	DeploymentTarget *DeploymentTarget `json:"deploymentTarget,omitempty"`

	// Amount of memory to allocate (in GiB).
	Memory *float64 `json:"memory,omitempty"`

	// The placement group for the VSI.
	PlacementGroup *string `json:"placementGroup,omitempty"`

	// Preferred processor compatibility mode.
	PreferredProcessorCompatibilityMode *string `json:"preferredProcessorCompatibilityMode,omitempty"`

	// Processor type (dedicated, shared, capped). When changing processor type without specifying processors, the system automatically converts the current core allocation, similar to how it is done when updating an existing VSI.
	// Enum: ["dedicated","shared","capped"]
	ProcType *string `json:"procType,omitempty"`

	// Number of processors to allocate.
	Processors *float64 `json:"processors,omitempty"`

	// SAP profile ID to use when unshelving the VSI. Only valid for VSI's already using an SAP profile.
	SapProfileID *string `json:"sapProfileID,omitempty"`

	// The shared processor pool on which the VSI is to be placed.
	SharedProcessorPool *string `json:"sharedProcessorPool,omitempty"`

	// System type used to host the instance.
	SysType *string `json:"sysType,omitempty"`

	// The VSI's virtual CPU information.
	VirtualCores *VirtualCores `json:"virtualCores,omitempty"`

	// virtual serial number
	VirtualSerialNumber *UnshelveVirtualSerialNumber `json:"virtualSerialNumber,omitempty"`
}

// Validate validates this p VM instance unshelve
func (m *PVMInstanceUnshelve) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDeploymentTarget(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProcType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVirtualCores(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVirtualSerialNumber(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PVMInstanceUnshelve) validateDeploymentTarget(formats strfmt.Registry) error {
	if swag.IsZero(m.DeploymentTarget) { // not required
		return nil
	}

	if m.DeploymentTarget != nil {
		if err := m.DeploymentTarget.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("deploymentTarget")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("deploymentTarget")
			}

			return err
		}
	}

	return nil
}

var pVmInstanceUnshelveTypeProcTypePropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["dedicated","shared","capped"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		pVmInstanceUnshelveTypeProcTypePropEnum = append(pVmInstanceUnshelveTypeProcTypePropEnum, v)
	}
}

const (

	// PVMInstanceUnshelveProcTypeDedicated captures enum value "dedicated"
	PVMInstanceUnshelveProcTypeDedicated string = "dedicated"

	// PVMInstanceUnshelveProcTypeShared captures enum value "shared"
	PVMInstanceUnshelveProcTypeShared string = "shared"

	// PVMInstanceUnshelveProcTypeCapped captures enum value "capped"
	PVMInstanceUnshelveProcTypeCapped string = "capped"
)

// prop value enum
func (m *PVMInstanceUnshelve) validateProcTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, pVmInstanceUnshelveTypeProcTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PVMInstanceUnshelve) validateProcType(formats strfmt.Registry) error {
	if swag.IsZero(m.ProcType) { // not required
		return nil
	}

	// value enum
	if err := m.validateProcTypeEnum("procType", "body", *m.ProcType); err != nil {
		return err
	}

	return nil
}

func (m *PVMInstanceUnshelve) validateVirtualCores(formats strfmt.Registry) error {
	if swag.IsZero(m.VirtualCores) { // not required
		return nil
	}

	if m.VirtualCores != nil {
		if err := m.VirtualCores.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("virtualCores")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("virtualCores")
			}

			return err
		}
	}

	return nil
}

func (m *PVMInstanceUnshelve) validateVirtualSerialNumber(formats strfmt.Registry) error {
	if swag.IsZero(m.VirtualSerialNumber) { // not required
		return nil
	}

	if m.VirtualSerialNumber != nil {
		if err := m.VirtualSerialNumber.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("virtualSerialNumber")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("virtualSerialNumber")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this p VM instance unshelve based on the context it is used
func (m *PVMInstanceUnshelve) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDeploymentTarget(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateVirtualCores(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateVirtualSerialNumber(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PVMInstanceUnshelve) contextValidateDeploymentTarget(ctx context.Context, formats strfmt.Registry) error {

	if m.DeploymentTarget != nil {

		if swag.IsZero(m.DeploymentTarget) { // not required
			return nil
		}

		if err := m.DeploymentTarget.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("deploymentTarget")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("deploymentTarget")
			}

			return err
		}
	}

	return nil
}

func (m *PVMInstanceUnshelve) contextValidateVirtualCores(ctx context.Context, formats strfmt.Registry) error {

	if m.VirtualCores != nil {

		if swag.IsZero(m.VirtualCores) { // not required
			return nil
		}

		if err := m.VirtualCores.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("virtualCores")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("virtualCores")
			}

			return err
		}
	}

	return nil
}

func (m *PVMInstanceUnshelve) contextValidateVirtualSerialNumber(ctx context.Context, formats strfmt.Registry) error {

	if m.VirtualSerialNumber != nil {

		if swag.IsZero(m.VirtualSerialNumber) { // not required
			return nil
		}

		if err := m.VirtualSerialNumber.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("virtualSerialNumber")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("virtualSerialNumber")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PVMInstanceUnshelve) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PVMInstanceUnshelve) UnmarshalBinary(b []byte) error {
	var res PVMInstanceUnshelve
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
