// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RegionalSnapshot regional snapshot
//
// swagger:model RegionalSnapshot
type RegionalSnapshot struct {

	// Description of the regional snapshot
	// Max Length: 255
	Description string `json:"description,omitempty"`

	// Name of the regional snapshot
	// Required: true
	// Max Length: 120
	// Pattern: ^[a-zA-Z0-9_.-]+$
	Name *string `json:"name"`

	// Indicates whether or not any user supplied tags will be propagated to the copy volumes of the regional snapshot.
	PropagateUserTags *bool `json:"propagateUserTags,omitempty"`

	// User supplied tags that will be associated with the regional snapshot.
	UserTags Tags `json:"userTags,omitempty"`

	// CRN of the user's workspace in the remote regional data center that will own the regional snapshot data. Required if the user has multiple workspaces in the remote regional data center.
	WorkspaceCRN CRN `json:"workspaceCRN,omitempty"`
}

// Validate validates this regional snapshot
func (m *RegionalSnapshot) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDescription(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserTags(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateWorkspaceCRN(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RegionalSnapshot) validateDescription(formats strfmt.Registry) error {
	if swag.IsZero(m.Description) { // not required
		return nil
	}

	if err := validate.MaxLength("description", "body", m.Description, 255); err != nil {
		return err
	}

	return nil
}

func (m *RegionalSnapshot) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	if err := validate.MaxLength("name", "body", *m.Name, 120); err != nil {
		return err
	}

	if err := validate.Pattern("name", "body", *m.Name, `^[a-zA-Z0-9_.-]+$`); err != nil {
		return err
	}

	return nil
}

func (m *RegionalSnapshot) validateUserTags(formats strfmt.Registry) error {
	if swag.IsZero(m.UserTags) { // not required
		return nil
	}

	if err := m.UserTags.Validate(formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("userTags")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("userTags")
		}

		return err
	}

	return nil
}

func (m *RegionalSnapshot) validateWorkspaceCRN(formats strfmt.Registry) error {
	if swag.IsZero(m.WorkspaceCRN) { // not required
		return nil
	}

	if err := m.WorkspaceCRN.Validate(formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("workspaceCRN")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("workspaceCRN")
		}

		return err
	}

	return nil
}

// ContextValidate validate this regional snapshot based on the context it is used
func (m *RegionalSnapshot) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateUserTags(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateWorkspaceCRN(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RegionalSnapshot) contextValidateUserTags(ctx context.Context, formats strfmt.Registry) error {

	if err := m.UserTags.ContextValidate(ctx, formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("userTags")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("userTags")
		}

		return err
	}

	return nil
}

func (m *RegionalSnapshot) contextValidateWorkspaceCRN(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.WorkspaceCRN) { // not required
		return nil
	}

	if err := m.WorkspaceCRN.ContextValidate(ctx, formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("workspaceCRN")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("workspaceCRN")
		}

		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RegionalSnapshot) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RegionalSnapshot) UnmarshalBinary(b []byte) error {
	var res RegionalSnapshot
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
