// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RemotePeerSnapshot remote peer snapshot
//
// swagger:model RemotePeerSnapshot
type RemotePeerSnapshot struct {

	// Date when the remote peer snapshot completed
	// Format: date-time
	CompletionDate strfmt.DateTime `json:"completionDate,omitempty"`

	// CRN of the remote peer snapshot.
	// Required: true
	Crn *CRN `json:"crn"`

	// ID of the remote peer snapshot
	// Required: true
	ID *string `json:"id"`

	// Name of the remote peer snapshot
	Name string `json:"name,omitempty"`

	// status of the remote peer snapshot
	// Required: true
	Status *string `json:"status"`
}

// Validate validates this remote peer snapshot
func (m *RemotePeerSnapshot) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCompletionDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCrn(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RemotePeerSnapshot) validateCompletionDate(formats strfmt.Registry) error {
	if swag.IsZero(m.CompletionDate) { // not required
		return nil
	}

	if err := validate.FormatOf("completionDate", "body", "date-time", m.CompletionDate.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *RemotePeerSnapshot) validateCrn(formats strfmt.Registry) error {

	if err := validate.Required("crn", "body", m.Crn); err != nil {
		return err
	}

	if m.Crn != nil {
		if err := m.Crn.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("crn")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("crn")
			}

			return err
		}
	}

	return nil
}

func (m *RemotePeerSnapshot) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *RemotePeerSnapshot) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("status", "body", m.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this remote peer snapshot based on the context it is used
func (m *RemotePeerSnapshot) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCrn(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RemotePeerSnapshot) contextValidateCrn(ctx context.Context, formats strfmt.Registry) error {

	if m.Crn != nil {

		if err := m.Crn.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("crn")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("crn")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RemotePeerSnapshot) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RemotePeerSnapshot) UnmarshalBinary(b []byte) error {
	var res RemotePeerSnapshot
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
