// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RouteSwitchEnabledRequest route switch enabled request
//
// swagger:model RouteSwitchEnabledRequest
type RouteSwitchEnabledRequest struct {

	// CRN of the route to disable
	DisabledRouteCRN *string `json:"disabledRouteCRN,omitempty"`
}

// Validate validates this route switch enabled request
func (m *RouteSwitchEnabledRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this route switch enabled request based on context it is used
func (m *RouteSwitchEnabledRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RouteSwitchEnabledRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RouteSwitchEnabledRequest) UnmarshalBinary(b []byte) error {
	var res RouteSwitchEnabledRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
