// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ServerVirtualSerialNumber server virtual serial number
//
// swagger:model ServerVirtualSerialNumber
type ServerVirtualSerialNumber struct {

	// Description of the Virtual Serial Number
	Description string `json:"description,omitempty"`

	// Provide an existing reserved Virtual Serial Number or specify 'auto-assign' for auto generated Virtual Serial Number.
	// Required: true
	Serial *string `json:"serial"`
}

// Validate validates this server virtual serial number
func (m *ServerVirtualSerialNumber) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSerial(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ServerVirtualSerialNumber) validateSerial(formats strfmt.Registry) error {

	if err := validate.Required("serial", "body", m.Serial); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this server virtual serial number based on context it is used
func (m *ServerVirtualSerialNumber) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ServerVirtualSerialNumber) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServerVirtualSerialNumber) UnmarshalBinary(b []byte) error {
	var res ServerVirtualSerialNumber
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
