// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SharedProcessorPoolCreate shared processor pool create
//
// swagger:model SharedProcessorPoolCreate
type SharedProcessorPoolCreate struct {

	// The host group identifier; a system type name or a dedicated host group ID. A host from the group is automatically selected based on available resources, unless `hostID` is also provided to target a specific host within a dedicated host group. For example, `s922` or `c3a5119c-65b5-4eb3-9b4a-6d840912c0cf`.
	// Required: true
	HostGroup *string `json:"hostGroup"`

	// The unique identifier of a host in a dedicated host group. Only available for dedicated hosts.
	HostID string `json:"hostID,omitempty"`

	// The name of the shared processor pool.
	// Required: true
	// Max Length: 12
	// Min Length: 2
	// Pattern: ^[a-zA-Z0-9_]+$
	Name *string `json:"name"`

	// The unique identifier of the placement group.
	PlacementGroupID string `json:"placementGroupID,omitempty"`

	// The number of processor cores to reserve for the shared processor pool.
	// Required: true
	ReservedCores *int64 `json:"reservedCores"`

	// user tags
	UserTags Tags `json:"userTags,omitempty"`
}

// Validate validates this shared processor pool create
func (m *SharedProcessorPoolCreate) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateHostGroup(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateReservedCores(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserTags(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SharedProcessorPoolCreate) validateHostGroup(formats strfmt.Registry) error {

	if err := validate.Required("hostGroup", "body", m.HostGroup); err != nil {
		return err
	}

	return nil
}

func (m *SharedProcessorPoolCreate) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	if err := validate.MinLength("name", "body", *m.Name, 2); err != nil {
		return err
	}

	if err := validate.MaxLength("name", "body", *m.Name, 12); err != nil {
		return err
	}

	if err := validate.Pattern("name", "body", *m.Name, `^[a-zA-Z0-9_]+$`); err != nil {
		return err
	}

	return nil
}

func (m *SharedProcessorPoolCreate) validateReservedCores(formats strfmt.Registry) error {

	if err := validate.Required("reservedCores", "body", m.ReservedCores); err != nil {
		return err
	}

	return nil
}

func (m *SharedProcessorPoolCreate) validateUserTags(formats strfmt.Registry) error {
	if swag.IsZero(m.UserTags) { // not required
		return nil
	}

	if err := m.UserTags.Validate(formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("userTags")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("userTags")
		}

		return err
	}

	return nil
}

// ContextValidate validate this shared processor pool create based on the context it is used
func (m *SharedProcessorPoolCreate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateUserTags(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SharedProcessorPoolCreate) contextValidateUserTags(ctx context.Context, formats strfmt.Registry) error {

	if err := m.UserTags.ContextValidate(ctx, formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("userTags")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("userTags")
		}

		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SharedProcessorPoolCreate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SharedProcessorPoolCreate) UnmarshalBinary(b []byte) error {
	var res SharedProcessorPoolCreate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
