// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SharedProcPoolCreate shared proc pool create
//
// swagger:model SharedProcPoolCreate
type SharedProcPoolCreate struct {

	// The host group where the host will be chosen if not provided
	// Required: true
	HostGroup *string `json:"hostGroup"`

	// The maximum number of processors defined for the pool
	// Required: true
	MaxProcUnits *float64 `json:"maxProcUnits"`

	// The name of the Processor Pool
	// Required: true
	Name *string `json:"name"`

	// The ID of the placement group
	PlacementGroupID string `json:"placementGroupID,omitempty"`
}

// Validate validates this shared proc pool create
func (m *SharedProcPoolCreate) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateHostGroup(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMaxProcUnits(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SharedProcPoolCreate) validateHostGroup(formats strfmt.Registry) error {

	if err := validate.Required("hostGroup", "body", m.HostGroup); err != nil {
		return err
	}

	return nil
}

func (m *SharedProcPoolCreate) validateMaxProcUnits(formats strfmt.Registry) error {

	if err := validate.Required("maxProcUnits", "body", m.MaxProcUnits); err != nil {
		return err
	}

	return nil
}

func (m *SharedProcPoolCreate) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this shared proc pool create based on context it is used
func (m *SharedProcPoolCreate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SharedProcPoolCreate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SharedProcPoolCreate) UnmarshalBinary(b []byte) error {
	var res SharedProcPoolCreate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
