// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SharedProcessorPool shared processor pool
//
// swagger:model SharedProcessorPool
type SharedProcessorPool struct {

	// The number of allocated processor cores for the shared processor pool.
	// Required: true
	AllocatedCores *float64 `json:"allocatedCores"`

	// The number of available processor cores for the shared processor pool.
	// Required: true
	AvailableCores *float64 `json:"availableCores"`

	// The date and time the shared processor pool was created.
	// Format: date-time
	CreationDate *strfmt.DateTime `json:"creationDate,omitempty"`

	// crn
	Crn CRN `json:"crn,omitempty"`

	// The unique identifier of the dedicated host where the shared processor pool resides, if applicable.
	DedicatedHostID string `json:"dedicatedHostID,omitempty"`

	// The host group that the host belongs to.
	HostGroup string `json:"hostGroup,omitempty"`

	// The identifier of the host where the shared processor pool resides.
	HostID int64 `json:"hostID,omitempty"`

	// The unique identifier of the shared processor pool.
	// Required: true
	ID *string `json:"id"`

	// The name of the shared processor pool.
	// Required: true
	Name *string `json:"name"`

	// The number of reserved processor cores for the shared processor pool.
	// Required: true
	ReservedCores *int64 `json:"reservedCores"`

	// The list of placement groups the shared processor pool is a member of.
	SharedProcessorPoolPlacementGroups []*SharedProcessorPoolPlacementGroup `json:"sharedProcessorPoolPlacementGroups"`

	// The status of the shared processor pool.
	Status string `json:"status,omitempty"`

	// Additional details about the status of the shared processor pool.
	StatusDetail string `json:"statusDetail,omitempty"`

	// user tags
	UserTags Tags `json:"userTags,omitempty"`
}

// Validate validates this shared processor pool
func (m *SharedProcessorPool) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAllocatedCores(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAvailableCores(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreationDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCrn(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateReservedCores(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSharedProcessorPoolPlacementGroups(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserTags(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SharedProcessorPool) validateAllocatedCores(formats strfmt.Registry) error {

	if err := validate.Required("allocatedCores", "body", m.AllocatedCores); err != nil {
		return err
	}

	return nil
}

func (m *SharedProcessorPool) validateAvailableCores(formats strfmt.Registry) error {

	if err := validate.Required("availableCores", "body", m.AvailableCores); err != nil {
		return err
	}

	return nil
}

func (m *SharedProcessorPool) validateCreationDate(formats strfmt.Registry) error {
	if swag.IsZero(m.CreationDate) { // not required
		return nil
	}

	if err := validate.FormatOf("creationDate", "body", "date-time", m.CreationDate.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *SharedProcessorPool) validateCrn(formats strfmt.Registry) error {
	if swag.IsZero(m.Crn) { // not required
		return nil
	}

	if err := m.Crn.Validate(formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("crn")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("crn")
		}

		return err
	}

	return nil
}

func (m *SharedProcessorPool) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *SharedProcessorPool) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *SharedProcessorPool) validateReservedCores(formats strfmt.Registry) error {

	if err := validate.Required("reservedCores", "body", m.ReservedCores); err != nil {
		return err
	}

	return nil
}

func (m *SharedProcessorPool) validateSharedProcessorPoolPlacementGroups(formats strfmt.Registry) error {
	if swag.IsZero(m.SharedProcessorPoolPlacementGroups) { // not required
		return nil
	}

	for i := 0; i < len(m.SharedProcessorPoolPlacementGroups); i++ {
		if swag.IsZero(m.SharedProcessorPoolPlacementGroups[i]) { // not required
			continue
		}

		if m.SharedProcessorPoolPlacementGroups[i] != nil {
			if err := m.SharedProcessorPoolPlacementGroups[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("sharedProcessorPoolPlacementGroups" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("sharedProcessorPoolPlacementGroups" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *SharedProcessorPool) validateUserTags(formats strfmt.Registry) error {
	if swag.IsZero(m.UserTags) { // not required
		return nil
	}

	if err := m.UserTags.Validate(formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("userTags")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("userTags")
		}

		return err
	}

	return nil
}

// ContextValidate validate this shared processor pool based on the context it is used
func (m *SharedProcessorPool) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCrn(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSharedProcessorPoolPlacementGroups(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUserTags(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SharedProcessorPool) contextValidateCrn(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.Crn) { // not required
		return nil
	}

	if err := m.Crn.ContextValidate(ctx, formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("crn")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("crn")
		}

		return err
	}

	return nil
}

func (m *SharedProcessorPool) contextValidateSharedProcessorPoolPlacementGroups(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.SharedProcessorPoolPlacementGroups); i++ {

		if m.SharedProcessorPoolPlacementGroups[i] != nil {

			if swag.IsZero(m.SharedProcessorPoolPlacementGroups[i]) { // not required
				return nil
			}

			if err := m.SharedProcessorPoolPlacementGroups[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("sharedProcessorPoolPlacementGroups" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("sharedProcessorPoolPlacementGroups" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *SharedProcessorPool) contextValidateUserTags(ctx context.Context, formats strfmt.Registry) error {

	if err := m.UserTags.ContextValidate(ctx, formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("userTags")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("userTags")
		}

		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SharedProcessorPool) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SharedProcessorPool) UnmarshalBinary(b []byte) error {
	var res SharedProcessorPool
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
