// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SnapshotRecoveryLocation snapshot recovery location
//
// swagger:model SnapshotRecoveryLocation
type SnapshotRecoveryLocation struct {

	// The name of the datacenter
	Location string `json:"location,omitempty"`

	// The list of storage pools that support zonal snapshots
	ZonalSnapshotPools []*ZonalSnapshotPool `json:"zonalSnapshotPools"`
}

// Validate validates this snapshot recovery location
func (m *SnapshotRecoveryLocation) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateZonalSnapshotPools(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SnapshotRecoveryLocation) validateZonalSnapshotPools(formats strfmt.Registry) error {
	if swag.IsZero(m.ZonalSnapshotPools) { // not required
		return nil
	}

	for i := 0; i < len(m.ZonalSnapshotPools); i++ {
		if swag.IsZero(m.ZonalSnapshotPools[i]) { // not required
			continue
		}

		if m.ZonalSnapshotPools[i] != nil {
			if err := m.ZonalSnapshotPools[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("zonalSnapshotPools" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("zonalSnapshotPools" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this snapshot recovery location based on the context it is used
func (m *SnapshotRecoveryLocation) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateZonalSnapshotPools(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SnapshotRecoveryLocation) contextValidateZonalSnapshotPools(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ZonalSnapshotPools); i++ {

		if m.ZonalSnapshotPools[i] != nil {

			if swag.IsZero(m.ZonalSnapshotPools[i]) { // not required
				return nil
			}

			if err := m.ZonalSnapshotPools[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("zonalSnapshotPools" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("zonalSnapshotPools" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *SnapshotRecoveryLocation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SnapshotRecoveryLocation) UnmarshalBinary(b []byte) error {
	var res SnapshotRecoveryLocation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
