// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UnshelveVirtualSerialNumber The software tier when the VSI is unshelved.
//
// swagger:model UnshelveVirtualSerialNumber
type UnshelveVirtualSerialNumber struct {

	// software tier
	// Required: true
	SoftwareTier *SoftwareTier `json:"softwareTier"`
}

// Validate validates this unshelve virtual serial number
func (m *UnshelveVirtualSerialNumber) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSoftwareTier(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UnshelveVirtualSerialNumber) validateSoftwareTier(formats strfmt.Registry) error {

	if err := validate.Required("softwareTier", "body", m.SoftwareTier); err != nil {
		return err
	}

	if m.SoftwareTier != nil {
		if err := m.SoftwareTier.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("softwareTier")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("softwareTier")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this unshelve virtual serial number based on the context it is used
func (m *UnshelveVirtualSerialNumber) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSoftwareTier(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UnshelveVirtualSerialNumber) contextValidateSoftwareTier(ctx context.Context, formats strfmt.Registry) error {

	if m.SoftwareTier != nil {

		if err := m.SoftwareTier.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("softwareTier")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("softwareTier")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *UnshelveVirtualSerialNumber) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UnshelveVirtualSerialNumber) UnmarshalBinary(b []byte) error {
	var res UnshelveVirtualSerialNumber
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
