// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// VPMemVolumeUpdate v p mem volume update
//
// swagger:model VPMemVolumeUpdate
type VPMemVolumeUpdate struct {

	// Volume base name for creation
	// Max Length: 20
	// Min Length: 1
	// Pattern: ^[a-zA-Z0-9-_]+$
	Name string `json:"name,omitempty"`

	// Volume size (GB) for creation
	// Minimum: 1
	Size int64 `json:"size,omitempty"`

	// Volume ID for removal
	VolumeID string `json:"volumeID,omitempty"`
}

// Validate validates this v p mem volume update
func (m *VPMemVolumeUpdate) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSize(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VPMemVolumeUpdate) validateName(formats strfmt.Registry) error {
	if swag.IsZero(m.Name) { // not required
		return nil
	}

	if err := validate.MinLength("name", "body", m.Name, 1); err != nil {
		return err
	}

	if err := validate.MaxLength("name", "body", m.Name, 20); err != nil {
		return err
	}

	if err := validate.Pattern("name", "body", m.Name, `^[a-zA-Z0-9-_]+$`); err != nil {
		return err
	}

	return nil
}

func (m *VPMemVolumeUpdate) validateSize(formats strfmt.Registry) error {
	if swag.IsZero(m.Size) { // not required
		return nil
	}

	if err := validate.MinimumInt("size", "body", m.Size, 1, false); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this v p mem volume update based on context it is used
func (m *VPMemVolumeUpdate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VPMemVolumeUpdate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VPMemVolumeUpdate) UnmarshalBinary(b []byte) error {
	var res VPMemVolumeUpdate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
