// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// VirtualSerialNumberResponse virtual serial number response
//
// swagger:model VirtualSerialNumberResponse
type VirtualSerialNumberResponse struct {

	// Description of the VSN
	// Required: true
	Description *string `json:"description"`

	// VSN ID of a reserved VSN or specify 'auto-assign' to have a new VSN ID generated.
	// Required: true
	Serial *string `json:"serial"`
}

// Validate validates this virtual serial number response
func (m *VirtualSerialNumberResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDescription(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSerial(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VirtualSerialNumberResponse) validateDescription(formats strfmt.Registry) error {

	if err := validate.Required("description", "body", m.Description); err != nil {
		return err
	}

	return nil
}

func (m *VirtualSerialNumberResponse) validateSerial(formats strfmt.Registry) error {

	if err := validate.Required("serial", "body", m.Serial); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this virtual serial number response based on context it is used
func (m *VirtualSerialNumberResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VirtualSerialNumberResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VirtualSerialNumberResponse) UnmarshalBinary(b []byte) error {
	var res VirtualSerialNumberResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
