// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// VirtualSerialNumber VSN Details
//
// swagger:model VirtualSerialNumber
type VirtualSerialNumber struct {

	// Description of the retained VSN
	Description string `json:"description,omitempty"`

	// HostID of the  retained VSN
	Host string `json:"host,omitempty"`

	// ID of the retained VSN
	VirtualSerialNumber string `json:"virtual-serial-number,omitempty"`
}

// Validate validates this virtual serial number
func (m *VirtualSerialNumber) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this virtual serial number based on context it is used
func (m *VirtualSerialNumber) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VirtualSerialNumber) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VirtualSerialNumber) UnmarshalBinary(b []byte) error {
	var res VirtualSerialNumber
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
