// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ZonalSnapshotPool zonal snapshot pool
//
// swagger:model ZonalSnapshotPool
type ZonalSnapshotPool struct {

	// List of remote region locations where regional snapshots can be created
	RegionalSnapshotLocations []string `json:"regionalSnapshotLocations,omitempty"`

	// Name of the storage that supports zonal snapshots
	StoragePool string `json:"storagePool,omitempty"`
}

// Validate validates this zonal snapshot pool
func (m *ZonalSnapshotPool) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this zonal snapshot pool based on context it is used
func (m *ZonalSnapshotPool) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ZonalSnapshotPool) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ZonalSnapshotPool) UnmarshalBinary(b []byte) error {
	var res ZonalSnapshotPool
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
