// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ZonalSnapshots zonal snapshots
//
// swagger:model ZonalSnapshots
type ZonalSnapshots struct {

	// Zonal snapshots enabled
	// Required: true
	Enabled *bool `json:"enabled"`

	// List of storage pools supporting zonal snapshots
	// Required: true
	StoragePools []string `json:"storagePools"`
}

// Validate validates this zonal snapshots
func (m *ZonalSnapshots) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEnabled(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStoragePools(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ZonalSnapshots) validateEnabled(formats strfmt.Registry) error {

	if err := validate.Required("enabled", "body", m.Enabled); err != nil {
		return err
	}

	return nil
}

func (m *ZonalSnapshots) validateStoragePools(formats strfmt.Registry) error {

	if err := validate.Required("storagePools", "body", m.StoragePools); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this zonal snapshots based on context it is used
func (m *ZonalSnapshots) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ZonalSnapshots) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ZonalSnapshots) UnmarshalBinary(b []byte) error {
	var res ZonalSnapshots
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
