// Code generated by go-swagger; DO NOT EDIT.

package p_cloud_ssh_keys

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/IBM-Cloud/power-go-client/power/models"
)

// NewPcloudSshkeysPutParams creates a new PcloudSshkeysPutParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPcloudSshkeysPutParams() *PcloudSshkeysPutParams {
	return &PcloudSshkeysPutParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPcloudSshkeysPutParamsWithTimeout creates a new PcloudSshkeysPutParams object
// with the ability to set a timeout on a request.
func NewPcloudSshkeysPutParamsWithTimeout(timeout time.Duration) *PcloudSshkeysPutParams {
	return &PcloudSshkeysPutParams{
		timeout: timeout,
	}
}

// NewPcloudSshkeysPutParamsWithContext creates a new PcloudSshkeysPutParams object
// with the ability to set a context for a request.
func NewPcloudSshkeysPutParamsWithContext(ctx context.Context) *PcloudSshkeysPutParams {
	return &PcloudSshkeysPutParams{
		Context: ctx,
	}
}

// NewPcloudSshkeysPutParamsWithHTTPClient creates a new PcloudSshkeysPutParams object
// with the ability to set a custom HTTPClient for a request.
func NewPcloudSshkeysPutParamsWithHTTPClient(client *http.Client) *PcloudSshkeysPutParams {
	return &PcloudSshkeysPutParams{
		HTTPClient: client,
	}
}

/*
PcloudSshkeysPutParams contains all the parameters to send to the API endpoint

	for the pcloud sshkeys put operation.

	Typically these are written to a http.Request.
*/
type PcloudSshkeysPutParams struct {

	/* Body.

	   Parameter for updating SSH key
	*/
	Body *models.UpdateWorkspaceSSHKey

	/* SshkeyID.

	   SSH Key ID
	*/
	SshkeyID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the pcloud sshkeys put params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PcloudSshkeysPutParams) WithDefaults() *PcloudSshkeysPutParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the pcloud sshkeys put params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PcloudSshkeysPutParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the pcloud sshkeys put params
func (o *PcloudSshkeysPutParams) WithTimeout(timeout time.Duration) *PcloudSshkeysPutParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the pcloud sshkeys put params
func (o *PcloudSshkeysPutParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the pcloud sshkeys put params
func (o *PcloudSshkeysPutParams) WithContext(ctx context.Context) *PcloudSshkeysPutParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the pcloud sshkeys put params
func (o *PcloudSshkeysPutParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the pcloud sshkeys put params
func (o *PcloudSshkeysPutParams) WithHTTPClient(client *http.Client) *PcloudSshkeysPutParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the pcloud sshkeys put params
func (o *PcloudSshkeysPutParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the pcloud sshkeys put params
func (o *PcloudSshkeysPutParams) WithBody(body *models.UpdateWorkspaceSSHKey) *PcloudSshkeysPutParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the pcloud sshkeys put params
func (o *PcloudSshkeysPutParams) SetBody(body *models.UpdateWorkspaceSSHKey) {
	o.Body = body
}

// WithSshkeyID adds the sshkeyID to the pcloud sshkeys put params
func (o *PcloudSshkeysPutParams) WithSshkeyID(sshkeyID string) *PcloudSshkeysPutParams {
	o.SetSshkeyID(sshkeyID)
	return o
}

// SetSshkeyID adds the sshkeyId to the pcloud sshkeys put params
func (o *PcloudSshkeysPutParams) SetSshkeyID(sshkeyID string) {
	o.SshkeyID = sshkeyID
}

// WriteToRequest writes these params to a swagger request
func (o *PcloudSshkeysPutParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param sshkey_id
	if err := r.SetPathParam("sshkey_id", o.SshkeyID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
