// Code generated by go-swagger; DO NOT EDIT.

package internal_operations_network_security_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewInternalV1OperationsNetworksecuritygroupsDeleteParams creates a new InternalV1OperationsNetworksecuritygroupsDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewInternalV1OperationsNetworksecuritygroupsDeleteParams() *InternalV1OperationsNetworksecuritygroupsDeleteParams {
	return &InternalV1OperationsNetworksecuritygroupsDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewInternalV1OperationsNetworksecuritygroupsDeleteParamsWithTimeout creates a new InternalV1OperationsNetworksecuritygroupsDeleteParams object
// with the ability to set a timeout on a request.
func NewInternalV1OperationsNetworksecuritygroupsDeleteParamsWithTimeout(timeout time.Duration) *InternalV1OperationsNetworksecuritygroupsDeleteParams {
	return &InternalV1OperationsNetworksecuritygroupsDeleteParams{
		timeout: timeout,
	}
}

// NewInternalV1OperationsNetworksecuritygroupsDeleteParamsWithContext creates a new InternalV1OperationsNetworksecuritygroupsDeleteParams object
// with the ability to set a context for a request.
func NewInternalV1OperationsNetworksecuritygroupsDeleteParamsWithContext(ctx context.Context) *InternalV1OperationsNetworksecuritygroupsDeleteParams {
	return &InternalV1OperationsNetworksecuritygroupsDeleteParams{
		Context: ctx,
	}
}

// NewInternalV1OperationsNetworksecuritygroupsDeleteParamsWithHTTPClient creates a new InternalV1OperationsNetworksecuritygroupsDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewInternalV1OperationsNetworksecuritygroupsDeleteParamsWithHTTPClient(client *http.Client) *InternalV1OperationsNetworksecuritygroupsDeleteParams {
	return &InternalV1OperationsNetworksecuritygroupsDeleteParams{
		HTTPClient: client,
	}
}

/*
InternalV1OperationsNetworksecuritygroupsDeleteParams contains all the parameters to send to the API endpoint

	for the internal v1 operations networksecuritygroups delete operation.

	Typically these are written to a http.Request.
*/
type InternalV1OperationsNetworksecuritygroupsDeleteParams struct {

	/* ResourceCrn.

	   Encoded resource CRN, "/" to be encoded into "%2F", example 'crn:v1:staging:public:power-iaas:satloc_dal_clp2joc20ppo19876n50:a%2Fc7e6bd2517ad44eabbd61fcc25cf68d5:79bffc73-0035-4e7b-b34a-15da38927424:network:d8d51d44-053b-4df3-90b6-31fbe72ba600'
	*/
	ResourceCrn string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the internal v1 operations networksecuritygroups delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *InternalV1OperationsNetworksecuritygroupsDeleteParams) WithDefaults() *InternalV1OperationsNetworksecuritygroupsDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the internal v1 operations networksecuritygroups delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *InternalV1OperationsNetworksecuritygroupsDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the internal v1 operations networksecuritygroups delete params
func (o *InternalV1OperationsNetworksecuritygroupsDeleteParams) WithTimeout(timeout time.Duration) *InternalV1OperationsNetworksecuritygroupsDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the internal v1 operations networksecuritygroups delete params
func (o *InternalV1OperationsNetworksecuritygroupsDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the internal v1 operations networksecuritygroups delete params
func (o *InternalV1OperationsNetworksecuritygroupsDeleteParams) WithContext(ctx context.Context) *InternalV1OperationsNetworksecuritygroupsDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the internal v1 operations networksecuritygroups delete params
func (o *InternalV1OperationsNetworksecuritygroupsDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the internal v1 operations networksecuritygroups delete params
func (o *InternalV1OperationsNetworksecuritygroupsDeleteParams) WithHTTPClient(client *http.Client) *InternalV1OperationsNetworksecuritygroupsDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the internal v1 operations networksecuritygroups delete params
func (o *InternalV1OperationsNetworksecuritygroupsDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithResourceCrn adds the resourceCrn to the internal v1 operations networksecuritygroups delete params
func (o *InternalV1OperationsNetworksecuritygroupsDeleteParams) WithResourceCrn(resourceCrn string) *InternalV1OperationsNetworksecuritygroupsDeleteParams {
	o.SetResourceCrn(resourceCrn)
	return o
}

// SetResourceCrn adds the resourceCrn to the internal v1 operations networksecuritygroups delete params
func (o *InternalV1OperationsNetworksecuritygroupsDeleteParams) SetResourceCrn(resourceCrn string) {
	o.ResourceCrn = resourceCrn
}

// WriteToRequest writes these params to a swagger request
func (o *InternalV1OperationsNetworksecuritygroupsDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param resource_crn
	if err := r.SetPathParam("resource_crn", o.ResourceCrn); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
